import { useEffect, useState } from 'react';

import useApi from '@hooks/useApi';
import useCustomReactQuery from '@hooks/useCustomReactQuery';

import { ShareExperienceResponseTypes } from './types';

const aaa = {
  selfTitleText: 'تجربه‌های من',
  groupsTitleText: 'تالار تجربه',
  otherTitleText: 'جدیدترین‌ها',
  inputText: 'اینجا تجربه‌هات رو با بقیه به اشتراک بذار',
  text: 'هر کسی تجربه‌های منحصربفرد خودش رو برای گذروندن چالش‌ها داره. اینجا می‌تونی تجربه‌هات رو با بقیه ایمپویی‌هایی که حال و هوای تو رو دارن به اشتراک بذاری',
  topics: [
    {
      image: 'https://c328642.parspack.net/c328642/topics/Delayedperiod.webp',
      name: 'عقب افتادن پریود',
      inputText: ' اینجا  تجربه‌هات رو بنویس',
      coverImage: 'https://c328642.parspack.net/c328642/topics/Delayedperiod.webp',
      bio: '',
      id: 'a30e1c55-09b9-4ee3-91f9-dc178d42f2dc',
    },
    {
      image: 'https://c328642.parspack.net/c328642/topics/tryingtogetpregnant.webp',
      name: 'اقدام به بارداری',
      inputText: ' اینجا  تجربه‌هات رو بنویس',
      coverImage: 'https://c328642.parspack.net/c328642/topics/tryingtogetpregnant.webp',
      bio: '',
      id: '13603542-d9a7-4c7d-b1ff-0a1193f26075',
    },
    {
      image: 'https://c328642.parspack.net/c328642/topics/Preventionofpregnancy.webp',
      name: 'پیشگیری از بارداری',
      inputText: ' اینجا  تجربه‌هات رو بنویس',
      coverImage: 'https://c328642.parspack.net/c328642/topics/Preventionofpregnancy.webp',
      bio: '',
      id: '265d01f4-b40d-4577-92eb-1d666afaceaa',
    },
    {
      image: 'https://c328642.parspack.net/c328642/topics/pregnancy.webp',
      name: 'بارداری',
      inputText: ' اینجا  تجربه‌هات رو بنویس',
      coverImage: 'https://c328642.parspack.net/c328642/topics/pregnancy.webp',
      bio: '',
      id: 'cd233f1f-6115-470a-be4a-44e3cdae288e',
    },
  ],
  expirences: [
    {
      topicName: '',
      isEdit: false,
      text: 'هااااای',
      userId: '673b32c56c660c08abad7bef',
      image: '',
      isPin: true,
      id: '20da9a3d-2600-4ee9-b440-2c10876647dc',
      createTime: '2024-11-19 08:33:37',
      name: 'قتن',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar11.webp',
      approvedProfile: false,
      likeCount: 1,
      disliked: 4,
      state: 0,
      commentCount: 63,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'تجربه نوتیف دار',
      userId: '6853d4f60d15eb7eec09d1e0',
      image: '',
      isPin: false,
      id: 'af4b46d8-2dbb-4d6a-bd2d-b8026ecf989f',
      createTime: '2025-12-16 10:48:18',
      name: 'ex',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar1.webp',
      approvedProfile: false,
      likeCount: 1,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'سلام دکتر هستم ریپورت کنید جونتون دربیاد',
      userId: '693ffa32504f9c805db07d4a',
      image: '',
      isPin: false,
      id: 'cc6f85e4-18c9-40ea-832b-ba9c4937ef95',
      createTime: '2025-12-16 09:40:56',
      name: 'آقای دکتر رستمی',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: '',
      approvedProfile: true,
      likeCount: 1,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'تجربه جانان\nخودش پنج تا کامنت میذاره',
      userId: '6926da57c7590afcce222790',
      image: '',
      isPin: false,
      id: '95bf353c-8238-4525-a106-e4416e7ab292',
      createTime: '2025-11-26 15:07:24',
      name: 'جانان',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar14.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 6,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'تجربه‌ی نورا',
      userId: '6846a82be41f3f73b96d666c',
      image: '',
      isPin: false,
      id: 'e8688180-a31e-47f5-9c03-508bc7273b8e',
      createTime: '2025-11-26 10:59:56',
      name: 'سوگند',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar11.webp',
      approvedProfile: false,
      likeCount: 1,
      disliked: 0,
      state: 0,
      commentCount: 5,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'برلد',
      userId: '691445889e74409bc9db4742',
      image: '63eb56b314074ed2960f9cb444f9ccb8.jpg',
      isPin: false,
      id: 'd4c55672-cf69-42a5-935b-2aa7fde2695b',
      createTime: '2025-11-16 11:52:32',
      name: 'بارداری ',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar1.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 1,
      state: 0,
      commentCount: 7,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'رذد',
      userId: '691445889e74409bc9db4742',
      image: '85e7cd2ce6984381986de7562b62050a.jpg',
      isPin: false,
      id: '32db4739-b38e-4079-86a7-5ab0c7b97a7d',
      createTime: '2025-11-16 11:52:08',
      name: 'بارداری ',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar1.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'بلد',
      userId: '691445889e74409bc9db4742',
      image: '',
      isPin: false,
      id: '33fdb709-3d31-49cb-abfd-b34c918c5d82',
      createTime: '2025-11-16 11:52:00',
      name: 'بارداری ',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar1.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 2,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'بلات',
      userId: '691445889e74409bc9db4742',
      image: 'bc3edecfd2b640999f065df4296277d0.jpg',
      isPin: false,
      id: 'f41b84d8-7d42-403a-9e5f-9bdc0a44171a',
      createTime: '2025-11-16 11:51:52',
      name: 'بارداری ',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar1.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'بیلا',
      userId: '691445889e74409bc9db4742',
      image: '60e6865d0a7f41b0b17258199ad22d03.jpg',
      isPin: false,
      id: '642f2e8d-0ce7-4e9f-b2c3-a45141aa16ec',
      createTime: '2025-11-16 11:51:34',
      name: 'بارداری ',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar1.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: false,
    },
    {
      topicName: '',
      isEdit: false,
      text: '۱۲۳',
      userId: '691445889e74409bc9db4742',
      image: '346e82cdd89d4b81b31a5eb3efbdbf19.jpg',
      isPin: false,
      id: '8087d4c9-8c9a-4e5c-8fdf-00d48997d736',
      createTime: '2025-11-16 11:51:11',
      name: 'بارداری ',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar1.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: false,
    },
  ],
  profile: {
    userId: '684663a3f20e4c04079a7fc2',
    medicalNumber: '',
    username: 'ایرانسل',
    expertise: '',
    biography: '',
    avatarImage: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar2.webp',
  },
  categories: [
    {
      id: '1',
      title: 'همه',
      isSelected: true,
      icon: '',
    },
    {
      id: '2',
      title: 'دنبال کننده ها',
      isSelected: false,
      icon: '',
    },
    {
      id: '3',
      title: 'ذخیره شده ها',
      isSelected: false,
      icon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/shareexp/bookmark.webp',
    },
  ],
};

const useShareExperienceGetData = () => {
  const [data, setData] = useState<ShareExperienceResponseTypes | undefined>(undefined);
  const { refetchQuery } = useCustomReactQuery();

  const successHandler = (v: ShareExperienceResponseTypes) => {
    setData(v);
    console.log(v);
  };

  const { isLoading, callApi } = useApi<ShareExperienceResponseTypes>({
    queryKey: ['shareExperience'],
    api: 'shareeexperience/v3',
    onSuccess: successHandler,
    method: 'GET',
    fetchOnMount: false,
    // initialData: aaa,
  });

  useEffect(() => {
    callApi();
  }, []);

  const onSuccessNewHandler = () => {
    refetchQuery({ queryKey: ['shareExperience'] });
    setData(undefined);
  };

  return { isLoading, data, onSuccessNewHandler };
};

export default useShareExperienceGetData;
