import type { Config } from 'tailwindcss';
import colors from 'tailwindcss/colors';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: ['class'],
  theme: {
    extend: {
      gridTemplateColumns: {
        24: 'repeat(24, minmax(0, 1fr))',
      },
      gridTemplateRows: {
        24: 'repeat(24, minmax(0, 1fr))',
      },
      keyframes: {
        pageNavigation: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(10%)' },
        },
        fadeSlideIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        pageNavigation: 'pageNavigation 5s linear forwards',
        fadeSlideIn: 'fadeSlideIn 0.4s ease-out',
        fadeIn: 'fadeIn 0.5s ease-out',
      },
    },

    boxShadow: {
      impo_Shadow_White: '0 0 16px 0 #6c23371f',
      impo_Shadow_Black: '0 0 16px 0 #777777',
    },

    colors: {
      ...colors,
      impo_Transparent: 'transparent',
      impo_Black: 'var(--color-Black)',
      impo_White: 'var(--color-White)',
      impo_OnBlack: 'var(--color-OnBlack)',
      impo_Primary_Primary: 'var(--color-Primary_Primary)',
      impo_Primary_OnPrimary: 'var(--color-Primary_OnPrimary)',
      impo_Primary_PrimaryContainer: 'var(--color-Primary_PrimaryContainer)',
      impo_Primary_OnPrimaryContainer: 'var(--color-Primary_OnPrimaryContainer)',
      impo_PrimaryMan_PrimaryMan: 'var(--color-PrimaryMan_PrimaryMan)',
      impo_PrimaryMan_OnPrimaryMan: 'var(--color-PrimaryMan_OnPrimaryMan)',
      impo_PrimaryMan_PrimaryContainerMan: 'var(--color-PrimaryMan_PrimaryContainerMan)',
      impo_PrimaryMan_OnPrimaryContainerMan: 'var(--color-PrimaryMan_OnPrimaryContainerMan)',
      impo_Cycle_Pms_Eyebrow: 'var(--color-Cycle_Pms_Eyebrow)',
      impo_Cycle_Pms_Title: 'var(--color-Cycle_Pms_Title)',
      impo_Cycle_Pms_Subtitle: 'var(--color-Cycle_Pms_Subtitle)',
      impo_Cycle_Pms_Frame: 'var(--color-Cycle_Pms_Frame)',
      impo_Cycle_Ovulation_Eyebrow: 'var(--color-Cycle_Ovulation_Eyebrow)',
      impo_Cycle_Ovulation_Title: 'var(--color-Cycle_Ovulation_Title)',
      impo_Cycle_Ovulation_Subtitle: 'var(--color-Cycle_Ovulation_Subtitle)',
      impo_Cycle_Ovulation_Frame: 'var(--color-Cycle_Ovulation_Frame)',
      impo_Cycle_Normal_Eyebrow: 'var(--color-Cycle_Normal_Eyebrow)',
      impo_Cycle_Normal_Title: 'var(--color-Cycle_Normal_Title)',
      impo_Cycle_Normal_Subtitle: 'var(--color-Cycle_Normal_Subtitle)',
      impo_Cycle_Normal_Frame: 'var(--color-Cycle_Normal_Frame)',
      impo_Cycle_Period_Eyebrow: 'var(--color-Cycle_Period_Eyebrow)',
      impo_Cycle_Period_Title: 'var(--color-Cycle_Period_Title)',
      impo_Cycle_Period_Subtitle: 'var(--color-Cycle_Period_Subtitle)',
      impo_Cycle_Period_Frame: 'var(--color-Cycle_Period_Frame)',
      impo_Cycle_BabyTracker_Eyebrow: 'var(--color-Cycle_BabyTracker_Eyebrow)',
      impo_Cycle_BabyTracker_Title: 'var(--color-Cycle_BabyTracker_Title)',
      impo_Cycle_BabyTracker_Subtitle: 'var(--color-Cycle_BabyTracker_Subtitle)',
      impo_Cycle_BabyTracker_Frame: 'var(--color-Cycle_BabyTracker_Frame)',
      impo_Cycle_Feeding_Eyebrow: 'var(--color-Cycle_Feeding_Eyebrow)',
      impo_Cycle_Feeding_Title: 'var(--color-Cycle_Feeding_Title)',
      impo_Cycle_Feeding_Subtitle: 'var(--color-Cycle_Feeding_Subtitle)',
      impo_Cycle_Feeding_Frame: 'var(--color-Cycle_Feeding_Frame)',
      impo_Secondary_Secondary: 'var(--color-Secondary_Secondary)',
      impo_Success_Success: 'var(--color-Success_Success)',
      impo_Success_SuccessContainer: 'var(--color-Success_SuccessContainer)',
      impo_Success_OnSuccess: 'var(--color-Success_OnSuccess)',
      impo_Success_OnSuccessContainer: 'var(--color-Success_OnSuccessContainer)',
      impo_Neutral_Background: 'var(--color-Neutral_Background)',
      impo_Neutral_OnBackground: 'var(--color-Neutral_OnBackground)',
      impo_Neutral_Surface: 'var(--color-Neutral_Surface)',
      impo_Neutral_OnSurface: 'var(--color-Neutral_OnSurface)',
      impo_Error_Error: 'var(--color-Error_Error)',
      impo_Error_OnError: 'var(--color-Error_OnError)',
      impo_Error_ErrorContainer: 'var(--color-Error_ErrorContainer)',
      impo_Error_OnErrorContainer: 'var(--color-Error_OnErrorContainer)',
      impo_Warning_Warning: 'var(--color-Warning_Warning)',
      impo_Warning_OnWarning: 'var(--color-Warning_OnWarning)',
      impo_Warning_WarininContainer: 'var(--color-Warning_WarininContainer)',
      impo_Warning_OnWarininContainer: 'var(--color-Warning_OnWarininContainer)',
      impo_Surface_Scrim: 'var(--color-Surface_Scrim)',
      impo_Surface_Outline: 'var(--color-Surface_Outline)',
      impo_Surface_OutlineVariant: 'var(--color-Surface_OutlineVariant)',
      impo_Surface_SurfaceVariant: 'var(--color-Surface_SurfaceVariant)',
      impo_Surface_OnSurfaceVariant: 'var(--color-Surface_OnSurfaceVariant)',
      impo_Surface_InverseSurface: 'var(--color-Surface_InverseSurface)',
      impo_Surface_InverseOnSurface: 'var(--color-Surface_InverseOnSurface)',
      impo_Calendar_PMS_Background: 'var(--color-Calendar_PMS_Background)',
      impo_Calendar_PMS_OnBackground: 'var(--color-Calendar_PMS_OnBackground)',
      impo_Calendar_Period_Background: 'var(--color-Calendar_Period_Background)',
      impo_Calendar_Period_OnBackground: 'var(--color-Calendar_Period_OnBackground)',
      impo_Calendar_Fertility_Background: 'var(--color-Calendar_Fertility_Background)',
      impo_Calendar_Fertility_OnBackground: 'var(--color-Calendar_Fertility_OnBackground)',
      impo_Calendar_Fertility_Ovulation: 'var(--color-Calendar_Fertility_Ovulation)',
      impo_Calendar_Pregnancy_Background1: 'var(--color-Calendar_Pregnancy_Background1)',
      impo_Calendar_Pregnancy_Background2: 'var(--color-Calendar_Pregnancy_Background2)',
      impo_Calendar_Pregnancy_OnBackground: 'var(--color-Calendar_Pregnancy_OnBackground)',
      impo_Calendar_Breastfeeding_Background1: 'var(--color-Calendar_Breastfeeding_Background1)',
      impo_Calendar_Breastfeeding_Background2: 'var(--color-Calendar_Breastfeeding_Background2)',
      impo_Calendar_Breastfeeding_OnBackground: 'var(--color-Calendar_Breastfeeding_OnBackground)',
      impo_Grey_50: 'var(--color-Grey_50)',
      impo_Grey_100: 'var(--color-Grey_100)',
      impo_Grey_200: 'var(--color-Grey_200)',
      impo_Grey_300: 'var(--color-Grey_300)',
      impo_Grey_400: 'var(--color-Grey_400)',
      impo_Grey_500: 'var(--color-Grey_500)',
      impo_Grey_600: 'var(--color-Grey_600)',
      impo_Grey_700: 'var(--color-Grey_700)',
      impo_Grey_800: 'var(--color-Grey_800)',
      impo_Grey_900: 'var(--color-Grey_900)',
      impo_Pink: 'var(--color-Pink)',
      impo_Pink_50: 'var(--color-Pink_50)',
      impo_Pink_100: 'var(--color-Pink_100)',
      impo_Pink_200: 'var(--color-Pink_200)',
      impo_Pink_300: 'var(--color-Pink_300)',
      impo_Pink_400: 'var(--color-Pink_400)',
      impo_Pink_500: 'var(--color-Pink_500)',
      impo_Pink_600: 'var(--color-Pink_600)',
      impo_Pink_700: 'var(--color-Pink_700)',
      impo_Pink_800: 'var(--color-Pink_800)',
      impo_Pink_900: 'var(--color-Pink_900)',
      impo_Purple_50: 'var(--color-Purple_50)',
      impo_Purple_100: 'var(--color-Purple_100)',
      impo_Purple_200: 'var(--color-Purple_200)',
      impo_Purple_300: 'var(--color-Purple_300)',
      impo_Purple_400: 'var(--color-Purple_400)',
      impo_Purple_500: 'var(--color-Purple_500)',
      impo_Purple_600: 'var(--color-Purple_600)',
      impo_Purple_700: 'var(--color-Purple_700)',
      impo_Purple_800: 'var(--color-Purple_800)',
      impo_Purple_900: 'var(--color-Purple_900)',
      impo_Blue_50: 'var(--color-Blue_50)',
      impo_Blue_100: 'var(--color-Blue_100)',
      impo_Blue_200: 'var(--color-Blue_200)',
      impo_Blue_300: 'var(--color-Blue_300)',
      impo_Blue_400: 'var(--color-Blue_400)',
      impo_Blue_500: 'var(--color-Blue_500)',
      impo_Blue_600: 'var(--color-Blue_600)',
      impo_Blue_700: 'var(--color-Blue_700)',
      impo_Blue_800: 'var(--color-Blue_800)',
      impo_Blue_900: 'var(--color-Blue_900)',
      impo_Cyan_50: 'var(--color-Cyan_50)',
      impo_Cyan_100: 'var(--color-Cyan_100)',
      impo_Cyan_200: 'var(--color-Cyan_200)',
      impo_Cyan_300: 'var(--color-Cyan_300)',
      impo_Cyan_400: 'var(--color-Cyan_400)',
      impo_Cyan_500: 'var(--color-Cyan_500)',
      impo_Cyan_600: 'var(--color-Cyan_600)',
      impo_Cyan_700: 'var(--color-Cyan_700)',
      impo_Cyan_800: 'var(--color-Cyan_800)',
      impo_Cyan_900: 'var(--color-Cyan_900)',
      impo_Green_50: 'var(--color-Green_50)',
      impo_Green_100: 'var(--color-Green_100)',
      impo_Green_200: 'var(--color-Green_200)',
      impo_Green_300: 'var(--color-Green_300)',
      impo_Green_400: 'var(--color-Green_400)',
      impo_Green_500: 'var(--color-Green_500)',
      impo_Green_600: 'var(--color-Green_600)',
      impo_Green_700: 'var(--color-Green_700)',
      impo_Green_800: 'var(--color-Green_800)',
      impo_Green_900: 'var(--color-Green_900)',
      impo_Yellow: 'var(--color-Yellow)',
      impo_Yellow_50: 'var(--color-Yellow_50)',
      impo_Yellow_100: 'var(--color-Yellow_100)',
      impo_Yellow_200: 'var(--color-Yellow_200)',
      impo_Yellow_300: 'var(--color-Yellow_300)',
      impo_Yellow_400: 'var(--color-Yellow_400)',
      impo_Yellow_500: 'var(--color-Yellow_500)',
      impo_Yellow_600: 'var(--color-Yellow_600)',
      impo_Yellow_700: 'var(--color-Yellow_700)',
      impo_Yellow_800: 'var(--color-Yellow_800)',
      impo_Yellow_900: 'var(--color-Yellow_900)',
      impo_Orange_50: 'var(--color-Orange_50)',
      impo_Orange_100: 'var(--color-Orange_100)',
      impo_Orange_200: 'var(--color-Orange_200)',
      impo_Orange_300: 'var(--color-Orange_300)',
      impo_Orange_400: 'var(--color-Orange_400)',
      impo_Orange_500: 'var(--color-Orange_500)',
      impo_Orange_600: 'var(--color-Orange_600)',
      impo_Orange_700: 'var(--color-Orange_700)',
      impo_Orange_800: 'var(--color-Orange_800)',
      impo_Orange_900: 'var(--color-Orange_900)',
      impo_Red_50: 'var(--color-Red_50)',
      impo_Red_100: 'var(--color-Red_100)',
      impo_Red_200: 'var(--color-Red_200)',
      impo_Red_300: 'var(--color-Red_300)',
      impo_Red_400: 'var(--color-Red_400)',
      impo_Red_500: 'var(--color-Red_500)',
      impo_Red_600: 'var(--color-Red_600)',
      impo_Red_700: 'var(--color-Red_700)',
      impo_Red_800: 'var(--color-Red_800)',
      impo_Red_900: 'var(--color-Red_900)',
    },
  },
};
export default config;
