export const MODAL_QUERY_NAME = 'modal';
export const PREVIEW_IMAGE = 'PREVIEW_IMAGE';
export const WIDGET_POPUP = 'WIDGET_POPUP';
export const STORY_MODAL_ID = 'STORY_MODAL_ID';
export const TEST_KITS_LIST_DELETE = 'TEST_KITS_LIST_DELETE';
export const TEST_KITS_LIST_BABYCHECK = 'TEST_KITS_LIST_BABYCHECK';
export const TEST_KITS_LIST_OVULATION = 'TEST_KITS_LIST_OVULATION';
export const TEST_KITS_BABYCHECK = 'TEST_KITS_BABYCHECK';
