import { QueryExperiencesDataTypes } from '../../../ShareExperienceContainer/ShareExperienceExperiences/__hooks__/useExperiences/types';

export const EXPERIENCE_DATA: QueryExperiencesDataTypes = {
  expirences: [
    {
      topicName: '',
      isEdit: false,
      text: 'نوتیف-۱',
      userId: '6974a1dc4343eb851b226bd3',
      image: '',
      isPin: false,
      id: 'b47ba29d-4104-4979-9850-549e91be59fb',
      createTime: '2026-02-03 15:18:23',
      name: 'کاربر-1',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar3.webp',
      approvedProfile: false,
      likeCount: 1,
      disliked: 0,
      state: 0,
      commentCount: 1,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'نوتیف تست ',
      userId: '684fa36d60726246bbc19d03',
      image: '',
      isPin: false,
      id: '08fea843-ad6f-4b53-83fa-b5aca3e9b1b5',
      createTime: '2026-02-03 14:35:28',
      name: 'نازنین',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar6.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'تست نوتیف',
      userId: '684fa36d60726246bbc19d03',
      image: '',
      isPin: false,
      id: 'fda57d94-fe8c-449e-b7b5-6070f3c92010',
      createTime: '2026-02-03 14:14:57',
      name: 'نازنین',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar6.webp',
      approvedProfile: false,
      likeCount: 1,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'ت',
      userId: '6846a82be41f3f73b96d666c',
      image: '',
      isPin: false,
      id: 'bc4f25b3-dd80-4d84-891f-c0626c7bc68c',
      createTime: '2026-01-26 16:12:19',
      name: 'سوگند',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar11.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 1,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'تجربه از تالار',
      userId: '6846a82be41f3f73b96d666c',
      image: '',
      isPin: false,
      id: 'ae31bc4d-3b08-44e8-a88c-45a2f28c1d17',
      createTime: '2026-01-26 16:12:07',
      name: 'سوگند',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar11.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'سلام',
      userId: '6846a82be41f3f73b96d666c',
      image: '',
      isPin: false,
      id: 'b765a88d-6eb2-4780-958e-024dea62a29e',
      createTime: '2026-01-26 12:13:00',
      name: 'سوگند',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar11.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'ترکر ۲۰ به بالا',
      userId: '68f77dfae50debb6cb7700f5',
      image: '',
      isPin: false,
      id: '88b170ea-ba9c-454d-9144-050817aec91e',
      createTime: '2026-01-18 14:31:02',
      name: 'نام تجربه',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar7.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'ترکر ۲۰ به بالا',
      userId: '68f77dfae50debb6cb7700f5',
      image: '',
      isPin: false,
      id: '88b170ea-ba9c-454d-9144-050817aec91e',
      createTime: '2026-01-18 14:31:02',
      name: 'نام تجربه',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar7.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'ترکر ۲۰ به بالا',
      userId: '68f77dfae50debb6cb7700f5',
      image: '',
      isPin: false,
      id: '88b170ea-ba9c-454d-9144-050817aec91e',
      createTime: '2026-01-18 14:31:02',
      name: 'نام تجربه',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar7.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
    {
      topicName: '',
      isEdit: false,
      text: 'ترکر ۲۰ به بالا',
      userId: '68f77dfae50debb6cb7700f5',
      image: '',
      isPin: false,
      id: '88b170ea-ba9c-454d-9144-050817aec91e',
      createTime: '2026-01-18 14:31:02',
      name: 'نام تجربه',
      selfExperience: false,
      self: false,
      prohibtComment: false,
      avatar: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/Avatar/Avatar7.webp',
      approvedProfile: false,
      likeCount: 0,
      disliked: 0,
      state: 0,
      commentCount: 0,
      isBookmarked: false,
      isFollow: true,
    },
  ],
};
