export const PERSIAN_BOY_NAME_DICTIONARY = {
  ا: {
    category: 'ا',
    list: [
      { title: 'ارشان', description: 'والا مقام', rootName: 'فارسی' },
      { title: 'ایلیار', description: 'حامی مردم', rootName: 'ترکی' },
      { title: 'ابراد', description: 'پاک و خالص', rootName: 'عربی' },
      { title: 'ارشیا', description: 'جایگاه شاهانه', rootName: 'فارسی' },
      { title: 'اوان', description: 'نور', rootName: 'ارمنی' },
      { title: 'اردوان', description: 'بافرهنگ', rootName: 'فارسی' },
      { title: 'ارمیا', description: 'نام یکی از پیامبران', rootName: 'عبری' },
      { title: 'اورهان', description: 'امپراطور', rootName: 'ترکی' },
      { title: 'اِلوین', description: 'بزرگ خانواده', rootName: 'ترکی' },
      { title: 'الحان', description: 'بزرگ ایل', rootName: 'ترکی' },
      { title: 'امیریل', description: ' قوی و شجاع', rootName: 'فارسی' },
      { title: 'ایلماز', description: 'جاویدان', rootName: 'ترکی' },
      { title: 'ایرمان', description: 'مهمان', rootName: 'فارسی' },
      { title: 'اَرشام', description: 'نیرو و قدرت ', rootName: 'فارسی' },
      { title: 'ايلشَن', description: 'شادی بخش ایل', rootName: 'ترکی' },
      { title: 'ایلکان', description: 'فرمانده ایل', rootName: 'ترکی' },
      { title: 'اَرتاش', description: ' مرد و پهلوان', rootName: 'ترکی' },
      { title: 'اَرکين', description: 'آزاد و مستقل', rootName: 'ترکی' },
      { title: 'اِريس', description: 'زیرک', rootName: 'عربی' },
      { title: 'اَردين', description: 'راستین', rootName: 'فارسی' },
    ],
  },
  آ: {
    category: 'آ',
    list: [
      { title: 'آراد', description: 'جوانمرد', rootName: 'فارسی' },
      { title: 'آیراد', description: 'ماه جوانمرد', rootName: 'ترکی' },
      { title: 'آرتان', description: 'نام برادر داريوش', rootName: 'فارسی' },
      { title: 'آیان', description: 'آشکار و هویدا', rootName: 'ترکی' },
      { title: 'آریو', description: 'آریایی', rootName: 'فارسی' },
      { title: 'آدرین', description: 'آتشین', rootName: 'لاتین' },
      { title: 'آیکان', description: 'اصیل ', rootName: 'ترکی' },
      { title: 'آرسین', description: 'سر آریایی', rootName: 'فارسی' },
      { title: 'آرتیا', description: 'مرد پاک', rootName: 'فارسی' },
      { title: 'آوش', description: 'مانند آب پاک و زلال', rootName: 'فارسی' },
      { title: 'آبتین', description: ' صاحب گفتار و کردار نیک', rootName: 'فارسی ' },
      { title: 'آران', description: 'نام قدیمی ایران', rootName: 'فارسی' },
      { title: 'آیهان', description: 'پادشاه ماه ', rootName: 'ترکی' },
      { title: 'آرکان', description: 'کسی که سرشت و خون او پاک است', rootName: 'ترکی' },
      { title: 'آراز', description: 'قهرمان منسوب به طایفه آس', rootName: 'ترکی' },
      { title: 'آرتا', description: 'درست کردار', rootName: 'فارسی ' },
      { title: 'آرات', description: 'شجاع و دلیر', rootName: 'ترکی ' },
      { title: 'آزاد', description: 'رها و فارغ ', rootName: 'فارسی ' },
      { title: 'آتامان', description: 'مانند پدر رهبر و فرمانده', rootName: 'ترکی ' },
      { title: 'آدریا', description: ' نگهدارنده آتش', rootName: 'لاتین' },
    ],
  },
  B: {
    category: 'ب',
    list: [
      { title: 'بهنود', description: 'پسر عزیز', rootName: 'فارسی' },
      { title: 'باراک', description: 'رعد', rootName: 'عبری' },
      { title: 'باریش', description: 'صلح', rootName: 'ترکی' },
      { title: 'بِهبد', description: 'نگهبان خوبی و نیکی', rootName: 'فارسی باستان' },
      { title: 'بهتاش', description: 'صاحب اخلاق و رفتار نیکو', rootName: 'ترکی' },
      { title: 'برهان', description: 'روشنی', rootName: 'عربی' },
      { title: 'بهراد', description: 'جوانمرد نیکو', rootName: 'فارسی' },
      { title: 'بهنیا', description: 'اصیل', rootName: 'فارسی' },
      { title: 'بردیا', description: 'نام دومین پسر کوروش', rootName: 'فارسی' },
      { title: 'برسام', description: ' آتش بزرگ', rootName: 'فارسی' },
      { title: 'برنا', description: 'دلاور', rootName: 'فارسی' },
      { title: 'باراد', description: ' غیور و جوانمرد ', rootName: 'فارسی' },
      { title: 'باربد', description: 'بزرگی و منزلت', rootName: 'فارسی' },
      { title: 'بارمان', description: 'شخص محترم دارای روح بزرگ', rootName: 'کردی' },
      { title: 'بِنسان', description: 'پسر برکت', rootName: 'عربی' },
      { title: 'بَسيم', description: 'شادمان', rootName: 'عربی' },
      { title: 'بوراک', description: 'درخشش', rootName: 'ترکی' },
      { title: 'برسان', description: 'خوشبو', rootName: 'فارسی' },
      { title: 'بُرزان', description: 'نیرومند و باشکوه', rootName: 'کردی' },
      { title: 'بِهداد', description: 'در کمال عدل و داد', rootName: 'فارسی' },
    ],
  },
  P: {
    category: 'پ',
    list: [
      { title: 'پاشا', description: ' بزرگ', rootName: 'فارسی' },
      { title: 'پندار', description: 'فکر و اندیشه', rootName: 'فارسی' },
      { title: 'پرهام', description: ' فرشته‌ خوبی', rootName: 'فارسی' },
      { title: 'پوژن', description: 'زمین پاک', rootName: 'فارسی' },
      { title: 'پاکداد', description: 'عادل', rootName: 'فارسی' },
      { title: 'پورنا', description: ' اسم یکی از فرماندهان ساسانی', rootName: 'فارسی باستان' },
      { title: 'پاسیار', description: 'نگهبان', rootName: 'فارسی' },
      { title: 'پادیان', description: 'محافظ', rootName: 'فارسی' },
      { title: 'پاکیار', description: 'دارنده پاکی', rootName: 'فارسی' },
      { title: 'پورداد', description: ' پسر با عدالت', rootName: 'فارسی' },
      { title: 'پاکراد', description: 'جوانمرد پاک', rootName: 'فارسی' },
      { title: 'پوریار', description: 'پسر همراه', rootName: 'فارسی' },
      { title: 'پورشان', description: 'پسر باارزش', rootName: 'فارسی' },
    ],
  },
  T1: {
    category: 'ت',
    list: [
      { title: 'تکین', description: 'پهلوان', rootName: 'ترکی' },
      { title: 'تاینور', description: 'مانند نور', rootName: 'ترکی' },
      { title: 'تُخشا', description: ' کوشا', rootName: 'فارسی' },
      { title: 'تَهمان', description: 'قدرتمند', rootName: 'فارسی' },
      { title: 'تايماز', description: 'پابرجا ', rootName: 'ترکی' },
      { title: 'تاراز', description: 'نام یکی از قله‌های زاگرس', rootName: 'ترکی' },
      { title: 'تیامین', description: 'فدایی چشمان', rootName: 'لری' },
      { title: 'تامر', description: 'خداوند خرما', rootName: 'عربی' },
      { title: 'تاویار', description: 'نگهبان آتش', rootName: 'کردی' },
      { title: 'تامیار', description: 'یار کامل', rootName: 'فارسی' },
      { title: 'تیامو', description: 'عزیز من', rootName: 'لری' },
      { title: 'تَلیمان', description: 'از شخصیتهای شاهنامه', rootName: 'فارسی' },
      { title: 'تاشکین', description: 'جوشان و خروشان', rootName: 'ترکی' },
    ],
  },
  S1: {
    category: 'ث',
    list: [
      { title: 'ثَوبان', description: 'نام یکی از صحابه پیامبر اسلام', rootName: 'عربی' },
      { title: 'ثامر', description: 'مثمر', rootName: 'عربی' },
      { title: 'ثاقب', description: 'هوشیار', rootName: 'عربی' },
    ],
  },
  J: {
    category: 'ج',
    list: [
      { title: 'جنید', description: 'سرباز', rootName: 'عربی' },
      { title: 'جاوید', description: 'جاویدان', rootName: 'فارسی' },
      { title: 'جانیار', description: 'یاری دهنده جان', rootName: 'فارسی' },
      { title: 'جانمهر', description: 'دوستدار جان', rootName: 'فارسی' },
      { title: 'جابان', description: ' دوست', rootName: 'فارسی' },
      { title: 'جهانور ', description: 'جهاندار', rootName: 'فارسی' },
      { title: 'جاهد', description: 'کوشا', rootName: 'عربی' },
      { title: 'جمزاد', description: 'بزرگ زاده', rootName: 'فارسی' },
      { title: 'جاستین', description: 'صالح و درستکار', rootName: 'لاتین' },
      { title: 'جهانشیر', description: 'دلاور در جهان', rootName: 'فارسی' },
      { title: 'جهانیار', description: 'یاور مردم جهان', rootName: 'فارسی' },
    ],
  },
  CH: {
    category: 'چ',
    list: [
      { title: 'چاووش', description: 'مامور تشریفات دربار', rootName: 'ترکی' },
      { title: 'چِکاد', description: 'قله کوه', rootName: 'فارسی' },
      { title: 'چیاکو', description: 'کوه کوچک ', rootName: 'کردی' },
      { title: 'چاولان', description: 'آبشار', rootName: 'ترکی' },
      { title: 'چیاوا', description: 'نگهبان کوه', rootName: 'کردی' },
    ],
  },
  H1: {
    category: 'ح',
    list: [
      { title: 'حامین', description: 'حمایت کننده', rootName: 'عربی' },
      { title: 'حسان', description: 'بسیار نیکو', rootName: 'عربی' },
      { title: 'حسام', description: 'شمشیر برنده و تیز ', rootName: 'عربی' },
      { title: 'حامی', description: 'پشتیبان', rootName: 'عربی' },
      { title: 'حسیب', description: 'بزرگوار', rootName: 'عربی' },
      { title: 'حمود', description: 'پسندیده ', rootName: 'عربی' },
      { title: 'حیان', description: 'زنده', rootName: 'عربی' },
      { title: 'حامیم', description: 'ستوده و با عظمت ', rootName: 'عربی' },
    ],
  },
  KH: {
    category: 'خ',
    list: [
      { title: 'خوزان', description: 'نام پهلوانی ایرانی', rootName: 'فارسی' },
      { title: 'خورزاد', description: 'نام یکی از پسران خسروپرویز', rootName: 'فارسی' },
      { title: 'خدایار', description: 'آن که خداوند یار اوست', rootName: 'فارسی' },
      { title: 'خورشاد', description: 'خورشید', rootName: 'فارسی' },
      { title: 'خسرو', description: 'نیک‌نام', rootName: 'فارسی باستان' },
      { title: 'خطیب', description: 'سخنران', rootName: 'عربی' },
      { title: 'خدیو', description: 'پادشاه ', rootName: 'فارسی' },
    ],
  },
  D: {
    category: 'د',
    list: [
      { title: 'دامیار', description: 'شکارچی', rootName: 'فارسی' },
      { title: 'دِمیر', description: 'قدرتمند', rootName: 'ترکی' },
      { title: 'دامور', description: 'آواز نرم و لطیف', rootName: 'ترکی' },
      { title: 'دادمهر', description: 'داده خورشید', rootName: 'فارسی' },
      { title: 'دایا', description: 'زر سرخ و طلا', rootName: 'یونانی' },
      { title: 'داژیار', description: 'روزی', rootName: 'کردی' },
      { title: 'دانیار', description: 'دارنده دانش و آگاهی', rootName: 'کردی' },
      { title: 'داریو', description: 'داریوش', rootName: 'فارسی' },
      { title: 'دومان', description: 'مه و غبار', rootName: 'ترکی' },
      { title: 'دارا', description: 'دارنده', rootName: 'فارسی' },
      { title: 'داوین', description: 'دامنه کوه', rootName: 'کردی' },
      { title: 'داتام', description: 'آفریننده و مخلوق', rootName: 'فارسی' },
      { title: 'داریا', description: 'دارا', rootName: 'فارسی' },
      { title: 'دیان', description: 'داور', rootName: 'عربی' },
      { title: 'دیار', description: ' سرزمین', rootName: 'عربی' },
      { title: 'دایان', description: 'سرافرازی', rootName: 'کردی' },
      { title: 'دیاکو', description: 'نام نخستين پادشاه ایران از سلسله‌ی ماد', rootName: 'کردی' },
      { title: 'دامون', description: 'دشت و صحرا', rootName: 'فارسی' },
      { title: 'دِژان', description: 'قلعه مستحکم', rootName: 'کردی' },
      { title: 'دارمان', description: 'از شخصیتهای شاهنامه', rootName: 'فارسی' },
    ],
  },
  Z1: {
    category: 'ذ',
    list: [
      { title: 'ذهین', description: 'زیرک', rootName: 'عربی' },
      { title: 'ذَکا ', description: 'هوشمندي', rootName: 'عربی' },
    ],
  },
  R: {
    category: 'ر',
    list: [
      { title: 'روماک', description: 'درست کردار', rootName: 'مازندرانی' },
      { title: 'رامون', description: 'راهنما', rootName: 'فارسی' },
      { title: 'راسین', description: 'نام یکی از سرداران ایرانی', rootName: 'فارسی' },
      { title: 'رامیاد', description: 'دوستدار اهورامزدا', rootName: 'فارسی' },
      { title: 'رامبد', description: ' نگهبان آرامش', rootName: 'فارسی' },
      { title: 'رشاد', description: 'رستگاری', rootName: 'عربی' },
      { title: 'رافد', description: 'یاری گر', rootName: 'عربی' },
      { title: 'رادبد', description: 'نگهبان جوانمردی', rootName: 'فارسی' },
      { title: 'رَهاد', description: 'جهانگرد', rootName: 'فارسی' },
      { title: 'رائین', description: 'دانا و خردمند', rootName: 'فارسی' },
      { title: 'رادنیک', description: 'جوانمرد نیکوسرشت', rootName: 'فارسی ' },
      { title: 'راثین', description: 'نام یکی از سرداران ایرانی ', rootName: 'فارسی' },
      { title: 'رایمون', description: ' پسر باهوش', rootName: 'گیلکی' },
      { title: 'رادمین', description: 'جوانمرد کوچک', rootName: 'کردی' },
      { title: 'رایبد', description: 'دانشمند', rootName: 'کردی' },
      { title: 'راسان', description: 'کوهستان', rootName: 'کردی' },
      { title: 'رادمهر', description: 'بخشنده چون خورشید', rootName: 'فارسی' },
      { title: 'رادمان', description: 'با سخاوت', rootName: 'فارسی' },
      { title: 'راستین', description: 'درستی و حقیقت', rootName: 'فارسی' },
      { title: 'رائیک', description: 'پسندیده', rootName: 'فارسی باستان' },
    ],
  },
  Z2: {
    category: 'ز',
    list: [
      { title: 'زانکو', description: 'دانش طلب', rootName: 'کردی' },
      { title: 'زانیار', description: 'دانشمند و دانا', rootName: 'کردی' },
      { title: 'زَمَران', description: 'نام پسر ابراهیم (ع)', rootName: 'عبری' },
      { title: 'زادمهر', description: 'نام یکی از نوازندگان ایرانی', rootName: 'فارسی' },
      { title: 'زبید', description: 'بخشش', rootName: 'عربی' },
      { title: 'زاهد', description: 'باتقوا', rootName: 'عربی' },
      { title: 'زبیر', description: 'مرد نیرومند و مقاوم ', rootName: 'عربی' },
      { title: 'زهیر', description: 'درخت پر شکوفه', rootName: 'عربی' },
      { title: 'زروان', description: 'ایزدِ زمانِ بی پایان ', rootName: 'فارسی باستان' },
    ],
  },
  ZH: {
    category: 'ژ',
    list: [
      { title: 'ژوبین', description: 'نوعی نیزه', rootName: 'فارسی' },
      { title: 'ژینار', description: 'زندگی ', rootName: 'کردی' },
      { title: 'ژیکان', description: 'زیبا و آرامش بخش', rootName: 'کردی' },
      { title: 'ژیرو', description: 'دانا و عاقل', rootName: 'کردی' },
      { title: 'ژیکو', description: 'هوشمند و زیرک ', rootName: 'کردی' },
      { title: 'ژیوان', description: 'نگهبان زندگی', rootName: 'کردی' },
    ],
  },
  S2: {
    category: 'س',
    list: [
      { title: 'سیحان', description: 'روان شدن آب بر روی زمین', rootName: 'فارسی' },
      { title: 'سِپَنتام', description: 'سپيد و پاك', rootName: ' فارسی باستان' },
      { title: 'سارکو', description: 'کوه بلند', rootName: 'فارسی' },
      { title: 'سَهیراد', description: '  جوانمرد بلند قامت', rootName: 'فارسی ' },
      { title: 'سپهرداد', description: 'نام داماد داریوش که در شجاعت ممتاز بود ', rootName: 'فارسی' },
      { title: 'سِرحان', description: 'شیر', rootName: 'فارسی' },
      { title: 'سِنان', description: 'نابودکننده دشمن ', rootName: 'عربی' },
      { title: 'سینان', description: 'فریبنده', rootName: 'ترکی' },
      { title: 'ساشا', description: 'مدافع و محافظ مردان', rootName: 'یونانی' },
      { title: 'سَمير', description: 'قصه گو ', rootName: 'عربی' },
      { title: 'ساتیار', description: 'یار صاف و ساده ', rootName: 'فارسی' },
      { title: 'سیروان', description: 'زیبا', rootName: 'کردی' },
      { title: 'سپنتا', description: 'پاک و مقدس', rootName: 'فارسی باستان' },
      { title: 'سورنا', description: 'نام سردار دلیر ایرانی', rootName: 'فارسی' },
      { title: 'سانیار', description: 'دارای عزت و قدرت', rootName: 'فارسی' },
      { title: ' سامین', description: 'منسوب به سام', rootName: 'فارسی' },
      { title: 'سامیار', description: 'محافظ آتش', rootName: 'فارسی' },
      { title: 'سپندار', description: 'بردباري و فروتني مقدس', rootName: 'فارسی' },
      { title: 'سایهان', description: 'خدای عدالت ', rootName: 'فارسی' },
      { title: 'ساعد', description: 'کمک کننده', rootName: 'عربی' },
    ],
  },
  SH: {
    category: 'ش',
    list: [
      { title: 'شانیا', description: 'مصمم', rootName: 'هندی' },
      { title: 'شَهنام', description: 'نيكنام', rootName: 'فارسی' },
      { title: 'شهمیر', description: 'امير و سلطان ', rootName: 'فارسی' },
      { title: 'شادمان', description: 'خوشحال و مسرور ', rootName: 'فارسی' },
      { title: 'شهداد', description: 'آفریده خداوند', rootName: 'فارسی' },
      { title: 'شیث', description: ' از پیامبران الهی', rootName: 'عربی' },
      { title: 'شاهو', description: 'شکوهمند چون شاه', rootName: 'فارسی' },
      { title: 'شوذب', description: 'نیکو خوی ', rootName: 'عربی' },
      { title: 'شَهيار', description: 'بلندمرتبه', rootName: 'فارسی ' },
      { title: 'شائق', description: 'مشتاق ', rootName: 'عربی' },
      { title: 'شهان', description: ' پادشاهان', rootName: 'فارسی' },
      { title: 'شَعيا', description: 'نام یکی از پیامبران بنی اسرائیل', rootName: 'عبری' },
      { title: 'شَهنور', description: 'نور خدا ', rootName: 'فارسی' },
      { title: 'شروین', description: 'نام انوشیروان دادگر', rootName: 'فارسی' },
      { title: 'شَنتيا', description: 'پیروز', rootName: 'عبری' },
      { title: 'شایراد', description: 'هاله و خرمن ماه ', rootName: 'فارسی' },
      { title: 'شایگان', description: 'گرانبها', rootName: 'فارسی' },
      { title: 'شایار', description: 'یار پدر', rootName: 'فارسی' },
      { title: 'شَهبُد ', description: ' صاحب اختیار ', rootName: 'فارسی' },
      { title: 'شاهان', description: 'منسوب به شاه', rootName: 'فارسی' },
    ],
  },
  S3: {
    category: 'ص',
    list: [
      { title: 'صدرا', description: 'بلندمرتبه', rootName: 'عربی' },
      { title: 'صنعان', description: 'شيخي عارف در ادبيات ايران', rootName: 'عربی' },
      { title: 'صُهَيب', description: ' از صحابه پيامبر اسلام(ص) ', rootName: 'عربی' },
      { title: 'صانِع', description: 'آفریننده', rootName: 'عربی' },
      { title: 'صامِد', description: 'باصلابت', rootName: 'عربی' },
      { title: 'صائِب', description: 'راستی و درستی', rootName: 'عربی' },
    ],
  },
  Z3: {
    category: 'ض',
    list: [
      { title: 'ضَرغام', description: 'شیر درنده', rootName: 'عربی' },
      { title: 'ضِيغم', description: 'شیر قوی', rootName: 'عربی' },
      { title: 'ضیا', description: 'روشنایی', rootName: 'عربی' },
    ],
  },
  T2: {
    category: 'ط',
    list: [
      { title: 'طوفان', description: 'هیاهو', rootName: 'عربی' },
      { title: 'طرفان', description: 'دو طرف چيزي ', rootName: 'عربی' },
      { title: 'طَهور', description: 'پاک کننده از آلودگیها', rootName: 'عربی' },
      { title: 'طورگ', description: 'از شخصیتهای شاهنامه', rootName: 'فارسی' },
      { title: 'طَرحان', description: 'گنج و ثروت', rootName: 'فارسی' },
      { title: 'طُغان', description: 'شاهین', rootName: 'ترکی' },
    ],
  },
  Z4: {
    category: 'ظ',
    list: [
      { title: 'ظهير', description: 'پشتیبان', rootName: 'عربی' },
      { title: 'ظافِر', description: 'پیروز', rootName: 'عربی' },
    ],
  },
  A2: {
    category: 'ع',
    list: [
      { title: 'عَلیتا', description: 'همتای علی', rootName: 'فارسی' },
      { title: 'عاکِف', description: 'گوشه گیرنده برای عبادت', rootName: 'عربی' },
      { title: 'علیداد', description: 'داده علی (ع) ', rootName: 'فارسی ' },
      { title: 'عابد', description: 'عبادت کننده', rootName: 'عربی' },
      { title: 'عَمار', description: 'بردبار', rootName: 'عربی' },
      { title: 'عَميد', description: 'عاشق و بی قرار ', rootName: 'عربی' },
      { title: 'عابِس', description: 'شجاع و بی باک', rootName: 'عربی' },
      { title: 'علیجان', description: 'انسان ارزشمند', rootName: 'ترکی' },
      { title: 'علیشاه', description: ' وزیر سلطان محمد خدابنده ', rootName: 'فارسی ' },
      { title: 'علیرام', description: 'مطیع حضرت علی ', rootName: 'عربی' },
      { title: 'علیسان', description: 'علی‌وار', rootName: 'فارسی' },
      { title: 'عَلیهان', description: 'هدیه خدا', rootName: 'ترکی' },
      { title: 'عِمران', description: 'نام پدر حضرت موسي(ع)', rootName: 'عبری' },
      { title: 'عرشیا', description: 'آسمانی و ملکوتی', rootName: 'فارسی' },
      { title: 'عَدنان', description: 'نام يكي از اجداد پیامبر اسلام', rootName: 'عربی' },
      { title: 'علیراد', description: 'بزرگ جوانمرد ', rootName: 'فارسی' },
      { title: 'عامِر', description: 'آباد كننده', rootName: 'عربی' },
      { title: 'عاصِم', description: 'نگه‌دارنده', rootName: 'عربی' },
    ],
  },
  GH1: {
    category: 'غ',
    list: [
      { title: 'غیاث', description: 'فریادرس ', rootName: 'عربی' },
      { title: 'غانِم', description: 'بهره‌مند', rootName: 'عربی' },
      { title: 'غاتفَر', description: 'از شخصیتهای تاریخی شاهنامه', rootName: 'فارسی' },
      { title: 'غفران', description: 'بخشايش ', rootName: 'عربی' },
    ],
  },
  F: {
    category: 'ف',
    list: [
      { title: 'فَرنود', description: 'برهان و دلیل', rootName: 'فارسی' },
      { title: 'فَرهود', description: 'مرد درشت اندام', rootName: 'عربی' },
      { title: 'فَرناد', description: 'توانایی', rootName: 'فارسی' },
      { title: 'فَرِهان', description: 'باشکوه و بزرگ ', rootName: 'فارسی' },
      { title: 'فَراز', description: 'اوج', rootName: 'فارسی' },
      { title: 'فَرهام', description: 'نیک اندیش', rootName: 'فارسی باستان' },
      { title: 'فَرحان', description: ' شاد و مسرور', rootName: 'عربی' },
      { title: 'فَردين', description: 'نگهبان پارسایی و پاکی در آیین زرتشت', rootName: 'فارسی' },
      { title: 'فواد', description: 'دل', rootName: 'عربی' },
      { title: 'فَرداد', description: 'زاده با شکوه ', rootName: 'فارسی' },
      { title: 'فَرسام', description: 'دارای شکوه و عظمتی چون سام ', rootName: 'فارسی' },
      { title: 'فَرنام', description: ' بالاترین نام ', rootName: 'فارسی' },
      { title: 'فَرخان', description: '   نام یکی از سرداران خسروپرویز', rootName: 'فارسی' },
      { title: 'فَربُد', description: 'شکوهمند', rootName: 'فارسی' },
      { title: 'فاروق', description: 'از صحابه پیامبر اسلام', rootName: 'عربی' },
    ],
  },
  GH2: {
    category: 'ق',
    list: [
      { title: 'قُباد', description: 'محبوب', rootName: 'فارسی' },
      { title: 'قائد', description: 'رهبر', rootName: 'عربی' },
      { title: 'قارِن', description: 'نام پسر کاوه آهنگر', rootName: 'فارسی' },
      { title: 'قَيس', description: 'از اصحاب پیامبر اسلام', rootName: 'عربی' },
    ],
  },
  K: {
    category: 'ک',
    list: [
      { title: 'کامبد', description: 'نگهبان آرزوها', rootName: 'فارسی' },
      { title: 'کوشان', description: 'تلاش‌گر', rootName: 'فارسی' },
      { title: 'کایِر', description: 'یاری', rootName: 'مازندرانی' },
      { title: 'کوشاد', description: 'ریشه گیاهی خوشرنگ', rootName: 'فارسی' },
      { title: 'کارِن', description: 'جنگجو', rootName: 'فارسی' },
      { title: 'کياشا', description: 'فرمانروا', rootName: 'فارسی' },
      { title: 'کیارش', description: 'پادشاه و شهریار دلیر', rootName: 'فارسی' },
      { title: 'کِيسان', description: 'از بزرگان و پادشاهان ', rootName: 'فارسی' },
      { title: 'کوهیار', description: 'استوار و پابرجا', rootName: 'فارسی' },
      { title: 'کایان', description: 'آب تندی که از قله کوه جاری میشود', rootName: 'ترکی' },
      { title: 'کاوان', description: 'صخره ', rootName: 'کردی' },
      { title: 'کیارام', description: ' الفت گرفته با پادشاهان  ', rootName: 'فارسی' },
      { title: 'کیاسا', description: 'مانند شاه', rootName: 'فارسی' },
      { title: 'کاریا', description: 'مرد جنگجو', rootName: 'کردی' },
    ],
  },
  G: {
    category: 'گ',
    list: [
      { title: 'گوشیار', description: 'نام حکیمی از فارس ', rootName: 'فارسی' },
      { title: 'گئومات', description: 'پسر کوروش', rootName: 'فارسی' },
      { title: 'گایار', description: 'یار قدرتمند ', rootName: 'کردی' },
      { title: 'گُردیا', description: 'شجاع و دلير ', rootName: 'فارسی' },
      { title: 'گَرشا', description: 'پادشاه كوه ', rootName: 'فارسی باستان' },
      { title: 'گشواد', description: 'نام یک پهلوان ايراني', rootName: 'فارسی' },
    ],
  },
  L: {
    category: 'ل',
    list: [
      { title: 'لیام', description: 'محافظ', rootName: 'فارسی' },
      { title: 'لیوراد', description: 'خورشید جوانمرد ', rootName: 'فارسی' },
      { title: 'لوران', description: 'زاده لر', rootName: 'لری' },
      { title: 'لاهور', description: 'یکتا', rootName: 'کردی' },
      { title: 'لَهاک', description: 'از شخصیتهای شاهنامه ', rootName: 'فارسی' },
    ],
  },
  M: {
    category: 'م',
    list: [
      { title: 'مانیاد', description: ' عزیز و گرامی ', rootName: 'فارسی' },
      { title: 'مِرآت', description: 'آینه', rootName: 'عربی' },
      { title: 'مادیار', description: 'ياور و كمك كننده مادر ', rootName: 'لری' },
      { title: 'مِهداد', description: 'داده ماه ', rootName: 'فارسی' },
      { title: 'میلان', description: ' آرزو', rootName: 'عربی' },
      { title: 'مَرتيا', description: 'جوانمرد', rootName: 'فارسی' },
      { title: 'مِهربد', description: 'نگهبان مهربانی', rootName: 'فارسی' },
      { title: 'معيد', description: ' ماهر', rootName: 'عربی' },
      { title: 'ماجد', description: 'بزرگوار ', rootName: 'عربی' },
      { title: 'مِهياد', description: 'دارای چهره‌ای زیبا چون ماه ', rootName: 'فارسی' },
      { title: 'میراث', description: 'ارث', rootName: 'عربی' },
      { title: 'مِهرزاد', description: 'زاده خورشید  ', rootName: 'فارسی' },
      { title: 'مَهزيار', description: ' صاحب کوهستان', rootName: 'فارسی' },
      { title: 'ماهِد', description: 'یکی از نام‌های خداوند ', rootName: 'عربی' },
      { title: 'میران', description: 'شاهانه', rootName: 'عربی' },
      { title: 'ماکان', description: 'شجاع', rootName: 'فارسی' },
      { title: 'مانیار', description: 'یار ماندگار ', rootName: 'فارسی' },
      { title: 'مَهبد', description: ' نگه‌دارنده ماه', rootName: 'فارسی' },
      { title: 'مَهديار', description: 'یار حضرت مهدی (عج) ', rootName: 'عربی' },
      { title: 'مسیحا', description: 'لقب حضرت عیسی (ع) ', rootName: 'فارسی' },
    ],
  },
  N: {
    category: 'ن',
    list: [
      { title: 'نویان', description: 'شاهزاده', rootName: 'ترکی' },
      { title: 'نیهاد', description: ' سرشت', rootName: 'کردی' },
      { title: 'نیکراد', description: 'جوانمرد صالح ', rootName: 'فارسی' },
      { title: 'نیکسام', description: ' پسر خورشید ', rootName: 'فارسی' },
      { title: 'نَريمان', description: 'از شخصیت‌های شاهنامه', rootName: 'فارسی باستان' },
      { title: 'نيکمِهر', description: ' داراي مهر و محبت ', rootName: 'فارسی' },
      { title: 'نیواد', description: 'شجاعت و دلیری', rootName: 'فارسی' },
      { title: 'نیکاد', description: 'خوشنام', rootName: 'ترکی' },
      { title: 'نوحا', description: 'راهنما ', rootName: 'عبری' },
      { title: 'نیاراد', description: 'از خاندان جوانمرد', rootName: 'فارسی' },
      { title: 'نیروان', description: 'رهایی از زندگی مادی', rootName: 'سانسکریت' },
      { title: 'نامبد', description: 'صاحب نام ', rootName: 'فارسی' },
      { title: 'نوتاش', description: 'همیشگی', rootName: 'فارسی' },
      { title: 'نیوراد', description: 'پهلوان جوانمرد ', rootName: 'فارسی' },
      { title: 'نیوسا', description: 'مانند پهلوان ', rootName: 'فارسی' },
      { title: 'ناسیکو', description: 'شکست ناپذیر', rootName: 'کردی' },
      { title: 'نیشام', description: 'فرشته نگهبان آذرخش ', rootName: 'فارسی' },
      { title: 'نامین', description: 'مشهور', rootName: 'فارسی' },
      { title: 'نیوزاد', description: ' زاده دلیر و شجاع  ', rootName: 'فارسی' },
      { title: 'نوژَن', description: 'صنوبر', rootName: 'فارسی' },
    ],
  },
  V: {
    category: 'و',
    list: [
      { title: 'ویهان', description: 'نیکان', rootName: 'فارسی  ' },
      { title: 'وِسام', description: 'خوبرویان', rootName: ' عربی ' },
      { title: 'والا', description: ' دارنده مقام و مرتبه مهم', rootName: 'فارسی' },
      { title: 'ویام', description: 'یاری کننده', rootName: 'فارسی باستان' },
      { title: 'وانیار', description: 'باسواد', rootName: 'کردی' },
      { title: 'وِداد', description: 'دوستی', rootName: 'عربی' },
      { title: 'وِهاد', description: 'مسیر مطمئن', rootName: 'عربی' },
      { title: 'وانتیار', description: 'نام پسر ایرج ', rootName: 'فارسی' },
      { title: 'وَهنیا', description: 'کسی که از نسل خوبان است ', rootName: 'فارسی' },
      { title: 'واتیار', description: 'سخنگو', rootName: 'کردی' },
      { title: 'وارتان', description: ' نام پسر بلاش اول پادشاه اشکانی ', rootName: 'ارمنی' },
      { title: 'وَسپار', description: 'آفریننده همه ', rootName: 'فارسی' },
      { title: 'وِریا', description: 'حقیقت', rootName: 'لاتین' },
      { title: 'والی', description: 'پادشاه', rootName: 'عربی' },
      { title: 'وَهان', description: 'جمع خوبان', rootName: 'فارسی' },
      { title: 'وَنداد', description: 'بشارت دهنده پیروزی', rootName: 'فارسی باستان' },
      { title: 'وَسیم', description: '  دارای نشان زیبایی', rootName: 'عربی' },
      { title: 'وَهرِز', description: ' نام سردار ایرانی ', rootName: 'فارسی' },
    ],
  },
  H2: {
    category: 'ه',
    list: [
      { title: 'هیرمان', description: 'به یاد ماندنی ', rootName: 'لری' },
      { title: 'هایان', description: 'پشتیبان', rootName: 'ترکی' },
      { title: 'هورزاد', description: 'زاده خورشید ', rootName: 'فارسی' },
      { title: 'هورداد', description: 'تابنده', rootName: 'فارسی' },
      { title: 'هودین', description: 'آئين نيك ', rootName: 'فارسی' },
      { title: 'هوپاد', description: 'نيك سرشت ', rootName: 'فارسی' },
      { title: 'هیرساد', description: 'خورشید پاک', rootName: 'فارسی' },
      { title: 'هیمن', description: 'موقر', rootName: 'کردی' },
      { title: 'هورام', description: 'پیرو نیکی ', rootName: 'عبری' },
      { title: 'هیروان', description: 'حافظ و نگهبان آتش ', rootName: 'فارسی' },
      { title: 'هامون', description: 'دشت و زمین هموار ', rootName: 'فارسی' },
      { title: 'هومان', description: 'دارنده‌ی روح خوب ', rootName: 'فارسی' },
      { title: 'هوراد', description: ' مرد نیک‌نام ', rootName: 'فارسی' },
      { title: 'هامین', description: 'تابستان', rootName: 'فارسی باستان' },
      { title: 'هاکان', description: 'امپراطور', rootName: 'ترکی' },
      { title: 'هیراد', description: 'خوشرو', rootName: 'فارسی' },
      { title: 'هيربَد', description: 'آموزگار', rootName: 'فارسی باستان' },
      { title: 'هارون', description: '  نگهبان', rootName: 'عبری' },
    ],
  },

  Y: {
    category: 'ی',
    list: [
      { title: 'یَلسان', description: 'مانند پهلوان', rootName: 'فارسی' },
      { title: 'یاشار', description: 'جاویدان', rootName: 'ترکی' },
      { title: 'یارا', description: 'توانایی', rootName: 'فارسی' },
      { title: 'يَزدان', description: ' ایزد', rootName: 'فارسی' },
      { title: 'یونا', description: ' نام دیگر حضرت یونس(ع) ', rootName: 'عبری' },
      { title: 'یاوان', description: 'نوه پسری نوح پیامبر', rootName: 'عبری' },
      { title: 'یاردا', description: 'یار مادر ', rootName: 'لری' },
      { title: 'یاشام', description: 'عمر و زندگی ', rootName: 'ترکی' },
    ],
  },
};

export const NAME_SELECTION_BANNER_NAME_2 = 'name2';
