export const DrList = [
  {
    image: '/assets/images/clinicLanding/drMahban.webp',
    drName: 'دکتر مهبان پروانه‌حسینی',
    speciality: 'رزیدنت زنان، زایمان و نازایی',
    nezamNumber: 'م-43004',
    averageResponse: '1 تا 2 ساعت',
    averageRate: 4.8,
    consNumber: 4487,
    drId: '123456',
  },
  {
    image: '/assets/images/clinicLanding/drMahban.webp',
    drName: 'دکتر مهبان پروانه‌حسینی',
    speciality: 'رزیدنت زنان، زایمان و نازایی',
    nezamNumber: 'م-43004',
    averageResponse: '1 تا 2 ساعت',
    averageRate: 4.8,
    consNumber: 4487,
    drId: '123456',
  },
  {
    image: '/assets/images/clinicLanding/drMahban.webp',
    drName: 'دکتر مهبان پروانه‌حسینی',
    speciality: 'رزیدنت زنان، زایمان و نازایی',
    nezamNumber: 'م-43004',
    averageResponse: '1 تا 2 ساعت',
    averageRate: 4.8,
    consNumber: 4487,
    drId: '123456',
  },
  {
    image: '/assets/images/clinicLanding/drMahban.webp',
    drName: 'دکتر مهبان پروانه‌حسینی',
    speciality: 'رزیدنت زنان، زایمان و نازایی',
    nezamNumber: 'م-43004',
    averageResponse: '1 تا 2 ساعت',
    averageRate: 4.8,
    consNumber: 4487,
    drId: '123456',
  },
  {
    image: '/assets/images/clinicLanding/drMahban.webp',
    drName: 'دکتر مهبان پروانه‌حسینی',
    speciality: 'رزیدنت زنان، زایمان و نازایی',
    nezamNumber: 'م-43004',
    averageResponse: '1 تا 2 ساعت',
    averageRate: 4.8,
    consNumber: 4487,
    drId: '123456',
  },
];
