import { AlphabetBtnsListTypes } from '@components/SelectName/AlphabetBtns/types';

export const PERSIAN_BOY_NAME_DICTIONARY: AlphabetBtnsListTypes = {
  ا: {
    category: 'ا',
    list: [
      { title: 'ابراهیم', description: 'دوست خدا، پدر قوم‌ها', rootName: 'پارسی، عبری' },
      { title: 'اردوان', description: 'مرد عادل، نگهبان حقیقت', rootName: 'پارسی' },
      { title: 'اردشیر', description: 'پادشاه نیک', rootName: 'پارسی' },
      { title: 'ارژنگ', description: 'ارزشمند، گران‌بها', rootName: 'پارسی' },
      { title: 'اسفندیار', description: 'نام شخصیت قهرمانی در شاهنامه، مقدس', rootName: 'پارسی' },
      { title: 'اشکان', description: 'بنیان‌گذار، مرتبط با سلسله اشکانیان', rootName: 'پارسی' },
      { title: 'امید', description: 'آرزو،  انتظار مثبت', rootName: 'پارسی' },
      { title: 'اردلان', description: 'مرد نیک، حقیقت مقدس', rootName: 'پارسی، کردی' },
      { title: 'اورنگ', description: 'تخت پادشاهی، شکوه و عظمت', rootName: 'پارسی' },
      { title: 'امان', description: 'آرامش، امنیت، پناه', rootName: 'پارسی' },
      { title: 'اَنوش', description: 'جاویدان، ابدی', rootName: 'پارسی' },
      { title: 'اَردا', description: 'مقدس، پاک', rootName: 'پارسی' },
      { title: 'امرتات', description: 'جاودانگی، بی‌مرگی، نام مقدس در فرهنگ زرتشتی', rootName: 'پارسی، اوستایی' },
      { title: 'اهورا', description: 'نام خدایان ایرانیان باستان و زرتشتیان، خداوند', rootName: 'پارسی، اوستایی' },
    ],
  },
  آ: {
    category: 'آ',
    list: [
      {
        title: 'آبان',
        description: 'نام روز دهم از هر ماه شمسی ایرانی، نام فرشته موکل آب و تدبیر امور مسائل آبان ماه',
        rootName: 'پارسی',
      },
      { title: 'آبتین', description: 'نیکوکار، نام پدر فریدون پادشاه پیشدادی', rootName: 'پارسی' },
      {
        title: 'آتروپات',
        description: 'آذرپناه، نگهبان آتش، یکی از سرداران هخامنشی و پارسی',
        rootName: 'پهلوی و اوستایی',
      },
      {
        title: 'آترین',
        description: 'شبیه به آتش، درخشان یا مقدس، نام پسر اوپدرم در زمان داريوش بزرگ.',
        rootName: 'پارسی',
      },
      {
        title: 'آذرباد',
        description: 'نگهبان آتش، کسی که مانند آتش نیرومند است، نام موبد موبدان روزگار شاپور دوم.',
        rootName: 'پارسی و اوستایی',
      },
      { title: 'آذرخش', description: 'رعد و برق، صاعقه', rootName: 'پارسی' },
      { title: 'آذین', description: 'زیور، آراستن، نام فرمانده لشکر بابک خرمدین', rootName: 'پارسی' },
      {
        title: 'آراد',
        description:
          'آزاد، سخاوتمند، نام فرشته‌ موکل بر دین و تدبیر امور روز آراد، نام روز بیست و پنجم ماه شمسی، (در پهلوی) آرای، آراینده',
        rootName: 'پارسی',
      },
      { title: 'آرتین', description: 'منسوب به آرت، پاکی و تقدس، نام هفتمین پادشاه ماد', rootName: 'پارسی' },
      {
        title: 'آرش',
        description: 'درخشنده، قهرمان اسطوره‌ای ایرانی که تیرانداز معروف داستان‌هاست.',
        rootName: 'پارسی و اوستایی',
      },
      {
        title: 'آرشام',
        description: 'قدرت و عظمت آریایی، نام پدر ویشتاسب، یکی از پادشاهان هخامنشی.',
        rootName: 'پارسی',
      },
      { title: 'آرشان', description: 'مرد، نام پسر اردشیر دوم پادشاه هخامنشی', rootName: 'پارسی' },
      { title: 'آرمان', description: 'آرزو، هدف، خواسته بزرگ', rootName: 'پارسی' },
      { title: 'آرمین', description: 'آرام، صلح‌جو، نام یکی از شخصیت‌های تاریخی پارسی.', rootName: 'پارسی' },
      {
        title: 'آریا',
        description: 'نجیب، اصیل، شریف، آزاد، فرمانده ارتش ایران در زمان کوروش',
        rootName: 'پارسی و اوستایی',
      },
      { title: 'آریو', description: 'شریف، نجیب، کوتاه‌شده آریوبرزن (سردار هخامنشی).', rootName: 'پارسی' },
      {
        title: 'آریوبرزن',
        description: 'آتش ایرانی، شکوه آریایی، دلاور و پهلوان، نام سردار هخامنشی، داریوش سوم',
        rootName: 'پارسی',
      },
      { title: 'آریامنش', description: 'دارای خوی و رفتار آریایی، نام پسر داریوش', rootName: 'پارسی' },
      { title: 'آرمیا', description: 'آرامش‌بخش، صلح‌جو', rootName: 'پارسی' },
      { title: 'آزاد', description: 'رها، صاحب اختیار', rootName: 'پارسی' },
      { title: 'آریاسب', description: 'دارنده اسب‌های نجیب، نام شخصیتی در اوستا.', rootName: 'پارسی و اوستایی' },
      {
        title: 'آریامهر',
        description: 'برخوردار از محبت آریایی، نام یکی از سرداران داریوش سوم پادشاه هخامنشی',
        rootName: 'پارسی',
      },
      { title: 'آوید', description: 'دانش و خرد، مشتاق', rootName: 'پارسی' },
    ],
  },
  B: {
    category: 'ب',
    list: [
      { title: 'بابک', description: 'پدر کوچک، نام قهرمان تاریخی ایرانی (بابک خرمدین).', rootName: 'پارسی' },
      { title: 'بارْبَد', description: 'نگهبان روشنی، نام نوازنده معروف دوره ساسانی.', rootName: 'پارسی' },
      { title: 'بامداد', description: 'سحرگاه، صبح زود، نام پدر مزدک', rootName: 'پارسی' },
      { title: 'بارمان', description: 'شایسته، با شکوه.', rootName: 'پارسی' },
      { title: 'بامشاد', description: 'شاد در سحر، نام یکی از موسیقی‌دانان دوره ساسانی', rootName: 'پارسی' },
      {
        title: 'بختیار',
        description: 'خوشبخت، دارای بخت و اقبال، از فرزندان رستم در روزگار خسرو پرویز',
        rootName: 'پارسی',
      },
      { title: 'برازمان', description: 'بلند اندیشه، شایسته و باشکوه', rootName: 'پارسی' },
      { title: 'بردیا', description: 'والا، نام پسر کوروش بزرگ و یکی از پادشاهان هخامنشی', rootName: 'پارسی' },
      { title: 'برزو', description: 'بلندقامت، نام پسر سهراب در شاهنامه', rootName: 'پارسی' },
      { title: 'برسام', description: 'آتش بزرگ، دارای شکوه و عظمت', rootName: 'پارسی' },
      { title: 'برمک', description: 'شکوهمند یا دارای عظمت، نام وزیر شیروی ساسانی', rootName: 'پارسی' },
      {
        title: 'بزرگمهر',
        description:
          'مهر والا، خورشید بزرگ، نام شخصیت تاریخی  معروف دوره ساسانی، بزرگمهر بن بختگان، وزیر و مشاور خردمند انوشیروان (خسرو اول)',
        rootName: 'پارسی',
      },
      {
        title: 'بهمن',
        description: 'نیک‌اندیش، نام ماه یازدهم تقویم ایرانی و ایزد نیک‌خواهی.',
        rootName: 'ریشه پارسی و اوستایی',
      },
      { title: 'بهراد', description: 'نیکی‌بخش، نیک‌مرد', rootName: 'پارسی' },
      {
        title: 'بهرام',
        description: 'پیروز، فاتح؛ نام ستاره مریخ و یکی از ایزدان زرتشتی.',
        rootName: 'ریشه پارسی و اوستایی',
      },
      { title: 'بهروز', description: 'روزگار نیک و خوش', rootName: 'پارسی' },
      { title: 'بهزاد', description: 'نیک‌زاده، کسی که از نژاد خوب است.', rootName: 'پارسی' },
      { title: 'بهمرد', description: 'مرد نیک، انسان شریف و خوب', rootName: 'پارسی' },
      { title: 'بهنام', description: 'نیک‌نام، دارای شهرت خوب.', rootName: 'پارسی' },
      { title: 'بیژن', description: 'جوانمرد، نام پسر گیو، یکی از پهلوانان شاهنامه', rootName: 'پارسی' },
      { title: 'بهشاد', description: 'شاد و نیک، دارای شادی و خیر', rootName: 'پارسی' },
    ],
  },
  P: {
    category: 'پ',
    list: [
      { title: 'پادرا', description: 'سرزمین باشکوه، نگهبان آتش', rootName: 'پارسی' },
      { title: 'پارسا', description: 'پرهیزکار، پاکدامن، پارسا و متدین', rootName: 'پارسی' },
      { title: 'پارسیا', description: 'متعلق به پارس، نجیب، شریف', rootName: 'پارسی' },
      { title: 'پاکان', description: 'پاکیزه، نیکوکار', rootName: 'پارسی' },
      { title: 'پاکزاد', description: 'زاده پاک، از نژاد نیک', rootName: 'پارسی' },
      { title: 'پاکمهر', description: 'دارای محبت پاک، شخص مهربان و نیک', rootName: 'پارسی' },
      { title: 'پدرام', description: 'نام نبیره سام؛ درود، شادباش، آراسته', rootName: 'پارسی' },
      { title: 'پرشان', description: 'رزمجو، پرشکوه، دارای عظمت و جلال', rootName: 'پارسی' },
      { title: 'پرشنگ', description: 'درخشان، پرنور، شاد و سرزنده', rootName: 'پارسی' },
      { title: 'پرهام', description: 'فرشته خوبی، صورت پارسی نام ابراهیم', rootName: 'پارسی، اوستایی' },
      { title: 'پرویز', description: 'شکست‌ناپذیر و پیروزمند؛ کنیه خسرو دوم ساسانی', rootName: 'پارسی' },
      { title: 'پژمان', description: 'دلتنگ، غمگین', rootName: 'پارسی' },
      {
        title: 'پوریا',
        description: 'پسر آریایی، پر از نور، شجاع، نام پهلوان معروف ایرانی، پوریای ولی',
        rootName: 'پارسی',
      },
      { title: 'پویا', description: 'جوینده، فعال، سرزنده و پرتحرک', rootName: 'پارسی' },
      { title: 'پوژان', description: 'پویا، سرزنده، گاهی به معنای جستجوگر', rootName: 'پارسی' },
      { title: 'پولاد', description: 'فولاد، نام پهلوانی در زمان کیقباد', rootName: 'پارسی' },
      { title: 'پیمان', description: 'عهد، سوگند، وعده؛ نماد وفاداری', rootName: 'پارسی' },
      { title: 'پیام', description: 'الهام، وحی، پیغام', rootName: 'پارسی' },
      { title: 'پیروز', description: 'فاتح، نام پادشاه ساسانی', rootName: 'پارسی' },
      { title: 'پیلتن', description: 'نیرومند، پهلوانی بوده از فرزندان رستم زال', rootName: 'پارسی' },
    ],
  },
  T1: {
    category: 'ت',
    list: [
      { title: 'تخشا', description: 'کوشنده، تلاشگر', rootName: 'پارسی' },
      {
        title: 'تَنسَر',
        description: 'نام موبد موبدان روزگار اردشیر بابکان، روحانی برجسته زرتشتی در دوره ساسانی',
        rootName: 'پارسی',
      },
      { title: 'تهماسب', description: 'طهماسب، به معنی دارنده اسب قوی', rootName: 'پارسی' },
      { title: 'تهمتن', description: 'بزرگ‌پیکر، نیرومند، لقب رستم پهلوان داستانی شاهنامه', rootName: 'پارسی' },
      { title: 'تهمین', description: 'پهلوان، شجاع، از القاب رستم پهلوان شاهنامه', rootName: 'پارسی' },
      { title: 'تهمورس', description: 'نیرومند، دلیر و پهلوان؛ نام دومین پادشاه خردمند پیشدادی', rootName: 'پارسی' },
      { title: 'تارخ', description: 'تاریک، شب، گاهی به معنای اسرارآمیز', rootName: 'پارسی' },
      { title: 'تامراد', description: 'آرزوی کامل، کسی که به اهدافش می‌رسد', rootName: 'پارسی' },
      { title: 'تاووس', description: 'پرنده طاووس، نماد زیبایی و شکوه', rootName: 'پارسی' },
      { title: 'ترسا', description: 'پاک‌دامن، پرهیزکار', rootName: 'پارسی' },
      { title: 'تیران', description: 'نام پسر اردشیر سوم، نامی اشکانی به معنای تیرانداز', rootName: 'پارسی' },
      { title: 'تیرداد', description: 'زاده‌شده در تیر، بخشنده تیر، نام پادشاه اشکانی', rootName: 'پارسی' },
      { title: 'تورج', description: 'دلیر، پهلوان؛ نام پسر بزرگ فریدون', rootName: 'پارسی' },
      { title: 'توس', description: 'نام پسر نوذر، پهلوان نامی ایران در شاهنامه', rootName: 'پارسی' },
      { title: 'توانا', description: 'نیرومند، زورمند', rootName: 'پارسی' },
    ],
  },
  S1: {
    category: '',
    list: [],
  },
  J: {
    category: 'ج',
    list: [
      {
        title: 'جاماسب',
        description: 'دارنده اسب درخشان، نام یکی از شخصیت‌های شاهنامه و اوستا، برادر گشتاسب',
        rootName: 'پارسی و اوستایی',
      },
      {
        title: 'جامشید',
        description: 'پادشاه درخشان، نام پادشاه اسطوره‌ای پیشدادی در شاهنامه، بنیان‌گذار نوروز',
        rootName: 'پارسی و اوستایی',
      },
      { title: 'جان‌نثار', description: 'فداکار، کسی که جان خود را نثار می‌کند', rootName: 'پارسی' },
      { title: 'جاوید', description: 'ابدی، جاودان', rootName: 'پارسی' },
      { title: 'جهان', description: 'گیتی، عالم', rootName: 'پارسی' },
      { title: 'جهانگیر', description: 'فاتح جهان، نام پسر رستم زال', rootName: 'پارسی' },
      { title: 'جانان', description: 'محبوب، دلیر، عزیز، روح و جان', rootName: 'پارسی' },
      { title: 'جهانشاه', description: 'پادشاه جهان، نامی با حس عظمت', rootName: 'پارسی' },
      { title: 'جمشید', description: 'از پادشاهان پیشدادی', rootName: 'پارسی' },
    ],
  },
  CH: {
    category: 'چ',
    list: [
      { title: 'چابک', description: 'سریع، فرز، چالاک', rootName: 'پارسی' },
      { title: 'چاوش', description: 'پیشرو، راهنما، کاروان‌سالار', rootName: 'پارسی' },
      { title: 'چهرزاد', description: 'زاده چهره زیبا، دارای ظاهر نیکو', rootName: 'پارسی' },
      { title: 'چینوَد', description: 'چگونه زیستن', rootName: 'ریشه پارسی اوستایی' },
    ],
  },
  H1: {
    category: 'ح',
    list: [
      { title: 'حانان', description: 'مهربان، عاشق، معشوق', rootName: 'پارسی' },
      { title: 'حامد', description: 'ستایشگر، شکرگزار', rootName: 'ریشه عربی و فارسی' },
      { title: 'حامی', description: 'پشتیبان، حامی، نگهبان', rootName: 'ریشه عربی و فارسی' },
      { title: 'حسام', description: 'شمشیر بران، نماد شجاعت و قدرت', rootName: 'ریشه عربی و فارسی' },
    ],
  },
  KH: {
    category: 'خ',
    list: [
      { title: 'خداداد', description: 'داده‌شده توسط خدا، نعمت الهی', rootName: 'پارسی' },
      { title: 'خدابخش', description: 'بخشیده‌شده توسط خدا، هدیه الهی', rootName: 'پارسی' },
      { title: 'خاور', description: 'شرق، مشرق، نماد طلوع خورشید و روشنایی', rootName: 'پارسی' },
      { title: 'خدیو', description: 'سرور، بلند جایگاه', rootName: 'پارسی' },
      { title: 'خردمند', description: 'نام یکی از پیروان دستور آذرکیوان', rootName: 'پارسی' },
      { title: 'خرم', description: 'شادمان، خوش', rootName: 'پارسی' },
      { title: 'خسرو', description: 'نیک آواز، نام پادشاه ساسانی', rootName: 'پارسی' },
      { title: 'خشایار', description: 'شاه دلیر، پادشاه قهرمان', rootName: 'ریشه پارسی و اوستایی' },
    ],
  },
  D: {
    category: 'د',
    list: [
      { title: 'داتام', description: 'آفریننده و مخلوق، نام یکی از فرماندهان پارسی کاپادوکیه', rootName: 'پارسی' },
      { title: 'داتیس', description: 'سرداری از مردم ماد و از سرداران داریوش هخامنشی', rootName: 'پارسی' },
      { title: 'دادمهر', description: 'عدالت دوست؛ نام چند تن از امیر زادگان و شاهزادگان در تاریخ', rootName: 'پارسی' },
      { title: 'دارا', description: 'برخوردار از چیزی، صاحب، مالک، ثروتمند', rootName: 'پارسی' },
      { title: 'دامون', description: 'دشت و صحرا؛ از حکمای قدیم یونان و از فیثاغوریان', rootName: 'پارسی' },
      { title: 'دانا', description: 'دارای عقل و تجربه، خردمند، عاقل، عالم', rootName: 'پارسی' },
      { title: 'دانوش', description: 'نام شخصی در داستان وامق و عذرا', rootName: 'پارسی' },
      { title: 'دایان', description: 'سرافرازی، تکیه گاه', rootName: 'پارسی' },
    ],
  },
  Z1: {
    category: 'ذ',
    list: [
      { title: 'ذهین', description: 'زیرک', rootName: 'عربی' },
      { title: 'ذَکا ', description: 'هوشمندي', rootName: 'عربی' },
    ],
  },
  R: {
    category: 'ر',
    list: [
      { title: 'رَسام', description: 'رسم کننده، طراح، نقاش', rootName: 'پارسی' },
      { title: 'رَها', description: 'نجات یافته و آزاد، آزادانه، رهایی', rootName: 'پارسی' },
      { title: 'رُهام', description: 'نام پهلوان ایرانی در شاهنامه', rootName: 'پارسی' },
      { title: 'راتین', description: 'رادترین، نام یکی از سرداران اردشیر دوم پادشاه ساسانی', rootName: 'پارسی' },
      {
        title: 'رادمان',
        description: 'رادمنش، کریم، با‌سخاوت، نام سرداری معاصر خسرو پرویز ساسانی.',
        rootName: 'پارسی',
      },
      { title: 'رادمهر', description: 'خورشید بخشنده، بخشنده همچون خورشید', rootName: 'پارسی' },
      { title: 'رادنوش', description: 'مرکب از راد (جوانمرد، بخشنده) + نوش (نیوشنده)', rootName: 'پارسی' },
      { title: 'رادوین', description: 'جوانمرد کوچک', rootName: 'پارسی' },
      { title: 'رادین', description: 'بخشنده، جوانمرد', rootName: 'پارسی' },
      {
        title: 'راژان',
        description: 'خوابیدن، جنبیدن گهواره، روستایی در بخش سیلوانا شهرستان ارومیه',
        rootName: 'پارسی و کردی',
      },
      { title: 'راستین', description: 'حقیقی، واقعی، راست قامت', rootName: 'پارسی' },
      { title: 'رامبُد', description: 'رئیس رامشگران؛ آرامش دهنده، فرشته', rootName: 'پارسی' },
      { title: 'رامتین', description: 'نوازنده، سازنده؛ نام شخصی که واضع چنگ بوده', rootName: 'پارسی' },
      { title: 'رامسین', description: 'گونه‌ی کهنه رامتین به معنی سازنده و نوازنده است.', rootName: 'پارسی' },
      { title: 'رایان', description: 'باهوش و دانشمند، نگهبان آسمان', rootName: 'پارسی' },
      {
        title: 'رستاک',
        description: 'شاخه‌ی تازه‌ای که از بیخ درخت برآید، زاده‌ی درخت مو، رویشگاه',
        rootName: 'پارسی',
      },
    ],
  },
  Z2: {
    category: 'ز',
    list: [
      { title: 'زانکو', description: 'دانش طلب', rootName: 'کردی' },
      { title: 'زانیار', description: 'دانشمند و دانا', rootName: 'کردی' },
      { title: 'زَمَران', description: 'نام پسر ابراهیم (ع)', rootName: 'عبری' },
      { title: 'زادمهر', description: 'نام یکی از نوازندگان ایرانی', rootName: 'فارسی' },
      { title: 'زبید', description: 'بخشش', rootName: 'عربی' },
      { title: 'زاهد', description: 'باتقوا', rootName: 'عربی' },
      { title: 'زبیر', description: 'مرد نیرومند و مقاوم ', rootName: 'عربی' },
      { title: 'زهیر', description: 'درخت پر شکوفه', rootName: 'عربی' },
      { title: 'زروان', description: 'ایزدِ زمانِ بی پایان ', rootName: 'فارسی باستان' },
    ],
  },
  ZH: {
    category: 'ژ',
    list: [
      { title: 'ژوبین', description: 'نوعی نیزه', rootName: 'فارسی' },
      { title: 'ژینار', description: 'زندگی ', rootName: 'کردی' },
      { title: 'ژیکان', description: 'زیبا و آرامش بخش', rootName: 'کردی' },
      { title: 'ژیرو', description: 'دانا و عاقل', rootName: 'کردی' },
      { title: 'ژیکو', description: 'هوشمند و زیرک ', rootName: 'کردی' },
      { title: 'ژیوان', description: 'نگهبان زندگی', rootName: 'کردی' },
    ],
  },
  S2: {
    category: 'س',
    list: [
      { title: 'سیحان', description: 'روان شدن آب بر روی زمین', rootName: 'فارسی' },
      { title: 'سِپَنتام', description: 'سپيد و پاك', rootName: ' فارسی باستان' },
      { title: 'سارکو', description: 'کوه بلند', rootName: 'فارسی' },
      { title: 'سَهیراد', description: '  جوانمرد بلند قامت', rootName: 'فارسی ' },
      { title: 'سپهرداد', description: 'نام داماد داریوش که در شجاعت ممتاز بود ', rootName: 'فارسی' },
      { title: 'سِرحان', description: 'شیر', rootName: 'فارسی' },
      { title: 'سِنان', description: 'نابودکننده دشمن ', rootName: 'عربی' },
      { title: 'سینان', description: 'فریبنده', rootName: 'ترکی' },
      { title: 'ساشا', description: 'مدافع و محافظ مردان', rootName: 'یونانی' },
      { title: 'سَمير', description: 'قصه گو ', rootName: 'عربی' },
      { title: 'ساتیار', description: 'یار صاف و ساده ', rootName: 'فارسی' },
      { title: 'سیروان', description: 'زیبا', rootName: 'کردی' },
      { title: 'سپنتا', description: 'پاک و مقدس', rootName: 'فارسی باستان' },
      { title: 'سورنا', description: 'نام سردار دلیر ایرانی', rootName: 'فارسی' },
      { title: 'سانیار', description: 'دارای عزت و قدرت', rootName: 'فارسی' },
      { title: ' سامین', description: 'منسوب به سام', rootName: 'فارسی' },
      { title: 'سامیار', description: 'محافظ آتش', rootName: 'فارسی' },
      { title: 'سپندار', description: 'بردباري و فروتني مقدس', rootName: 'فارسی' },
      { title: 'سایهان', description: 'خدای عدالت ', rootName: 'فارسی' },
      { title: 'ساعد', description: 'کمک کننده', rootName: 'عربی' },
    ],
  },
  SH: {
    category: 'ش',
    list: [
      { title: 'شانیا', description: 'مصمم', rootName: 'هندی' },
      { title: 'شَهنام', description: 'نيكنام', rootName: 'فارسی' },
      { title: 'شهمیر', description: 'امير و سلطان ', rootName: 'فارسی' },
      { title: 'شادمان', description: 'خوشحال و مسرور ', rootName: 'فارسی' },
      { title: 'شهداد', description: 'آفریده خداوند', rootName: 'فارسی' },
      { title: 'شیث', description: ' از پیامبران الهی', rootName: 'عربی' },
      { title: 'شاهو', description: 'شکوهمند چون شاه', rootName: 'فارسی' },
      { title: 'شوذب', description: 'نیکو خوی ', rootName: 'عربی' },
      { title: 'شَهيار', description: 'بلندمرتبه', rootName: 'فارسی ' },
      { title: 'شائق', description: 'مشتاق ', rootName: 'عربی' },
      { title: 'شهان', description: ' پادشاهان', rootName: 'فارسی' },
      { title: 'شَعيا', description: 'نام یکی از پیامبران بنی اسرائیل', rootName: 'عبری' },
      { title: 'شَهنور', description: 'نور خدا ', rootName: 'فارسی' },
      { title: 'شروین', description: 'نام انوشیروان دادگر', rootName: 'فارسی' },
      { title: 'شَنتيا', description: 'پیروز', rootName: 'عبری' },
      { title: 'شایراد', description: 'هاله و خرمن ماه ', rootName: 'فارسی' },
      { title: 'شایگان', description: 'گرانبها', rootName: 'فارسی' },
      { title: 'شایار', description: 'یار پدر', rootName: 'فارسی' },
      { title: 'شَهبُد ', description: ' صاحب اختیار ', rootName: 'فارسی' },
      { title: 'شاهان', description: 'منسوب به شاه', rootName: 'فارسی' },
    ],
  },
  S3: {
    category: 'ص',
    list: [
      { title: 'صدرا', description: 'بلندمرتبه', rootName: 'عربی' },
      { title: 'صنعان', description: 'شيخي عارف در ادبيات ايران', rootName: 'عربی' },
      { title: 'صُهَيب', description: ' از صحابه پيامبر اسلام(ص) ', rootName: 'عربی' },
      { title: 'صانِع', description: 'آفریننده', rootName: 'عربی' },
      { title: 'صامِد', description: 'باصلابت', rootName: 'عربی' },
      { title: 'صائِب', description: 'راستی و درستی', rootName: 'عربی' },
    ],
  },
  Z3: {
    category: 'ض',
    list: [
      { title: 'ضَرغام', description: 'شیر درنده', rootName: 'عربی' },
      { title: 'ضِيغم', description: 'شیر قوی', rootName: 'عربی' },
      { title: 'ضیا', description: 'روشنایی', rootName: 'عربی' },
    ],
  },
  T2: {
    category: 'ط',
    list: [
      { title: 'طوفان', description: 'هیاهو', rootName: 'عربی' },
      { title: 'طرفان', description: 'دو طرف چيزي ', rootName: 'عربی' },
      { title: 'طَهور', description: 'پاک کننده از آلودگیها', rootName: 'عربی' },
      { title: 'طورگ', description: 'از شخصیتهای شاهنامه', rootName: 'فارسی' },
      { title: 'طَرحان', description: 'گنج و ثروت', rootName: 'فارسی' },
      { title: 'طُغان', description: 'شاهین', rootName: 'ترکی' },
    ],
  },
  Z4: {
    category: 'ظ',
    list: [
      { title: 'ظهير', description: 'پشتیبان', rootName: 'عربی' },
      { title: 'ظافِر', description: 'پیروز', rootName: 'عربی' },
    ],
  },
  A2: {
    category: 'ع',
    list: [
      { title: 'عَلیتا', description: 'همتای علی', rootName: 'فارسی' },
      { title: 'عاکِف', description: 'گوشه گیرنده برای عبادت', rootName: 'عربی' },
      { title: 'علیداد', description: 'داده علی (ع) ', rootName: 'فارسی ' },
      { title: 'عابد', description: 'عبادت کننده', rootName: 'عربی' },
      { title: 'عَمار', description: 'بردبار', rootName: 'عربی' },
      { title: 'عَميد', description: 'عاشق و بی قرار ', rootName: 'عربی' },
      { title: 'عابِس', description: 'شجاع و بی باک', rootName: 'عربی' },
      { title: 'علیجان', description: 'انسان ارزشمند', rootName: 'ترکی' },
      { title: 'علیشاه', description: ' وزیر سلطان محمد خدابنده ', rootName: 'فارسی ' },
      { title: 'علیرام', description: 'مطیع حضرت علی ', rootName: 'عربی' },
      { title: 'علیسان', description: 'علی‌وار', rootName: 'فارسی' },
      { title: 'عَلیهان', description: 'هدیه خدا', rootName: 'ترکی' },
      { title: 'عِمران', description: 'نام پدر حضرت موسي(ع)', rootName: 'عبری' },
      { title: 'عرشیا', description: 'آسمانی و ملکوتی', rootName: 'فارسی' },
      { title: 'عَدنان', description: 'نام يكي از اجداد پیامبر اسلام', rootName: 'عربی' },
      { title: 'علیراد', description: 'بزرگ جوانمرد ', rootName: 'فارسی' },
      { title: 'عامِر', description: 'آباد كننده', rootName: 'عربی' },
      { title: 'عاصِم', description: 'نگه‌دارنده', rootName: 'عربی' },
    ],
  },
  GH1: {
    category: 'غ',
    list: [
      { title: 'غیاث', description: 'فریادرس ', rootName: 'عربی' },
      { title: 'غانِم', description: 'بهره‌مند', rootName: 'عربی' },
      { title: 'غاتفَر', description: 'از شخصیتهای تاریخی شاهنامه', rootName: 'فارسی' },
      { title: 'غفران', description: 'بخشايش ', rootName: 'عربی' },
    ],
  },
  F: {
    category: 'ف',
    list: [
      { title: 'فَرنود', description: 'برهان و دلیل', rootName: 'فارسی' },
      { title: 'فَرهود', description: 'مرد درشت اندام', rootName: 'عربی' },
      { title: 'فَرناد', description: 'توانایی', rootName: 'فارسی' },
      { title: 'فَرِهان', description: 'باشکوه و بزرگ ', rootName: 'فارسی' },
      { title: 'فَراز', description: 'اوج', rootName: 'فارسی' },
      { title: 'فَرهام', description: 'نیک اندیش', rootName: 'فارسی باستان' },
      { title: 'فَرحان', description: ' شاد و مسرور', rootName: 'عربی' },
      { title: 'فَردين', description: 'نگهبان پارسایی و پاکی در آیین زرتشت', rootName: 'فارسی' },
      { title: 'فواد', description: 'دل', rootName: 'عربی' },
      { title: 'فَرداد', description: 'زاده با شکوه ', rootName: 'فارسی' },
      { title: 'فَرسام', description: 'دارای شکوه و عظمتی چون سام ', rootName: 'فارسی' },
      { title: 'فَرنام', description: ' بالاترین نام ', rootName: 'فارسی' },
      { title: 'فَرخان', description: '   نام یکی از سرداران خسروپرویز', rootName: 'فارسی' },
      { title: 'فَربُد', description: 'شکوهمند', rootName: 'فارسی' },
      { title: 'فاروق', description: 'از صحابه پیامبر اسلام', rootName: 'عربی' },
    ],
  },
  GH2: {
    category: 'ق',
    list: [
      { title: 'قُباد', description: 'محبوب', rootName: 'فارسی' },
      { title: 'قائد', description: 'رهبر', rootName: 'عربی' },
      { title: 'قارِن', description: 'نام پسر کاوه آهنگر', rootName: 'فارسی' },
      { title: 'قَيس', description: 'از اصحاب پیامبر اسلام', rootName: 'عربی' },
    ],
  },
  K: {
    category: 'ک',
    list: [
      { title: 'کامبد', description: 'نگهبان آرزوها', rootName: 'فارسی' },
      { title: 'کوشان', description: 'تلاش‌گر', rootName: 'فارسی' },
      { title: 'کایِر', description: 'یاری', rootName: 'مازندرانی' },
      { title: 'کوشاد', description: 'ریشه گیاهی خوشرنگ', rootName: 'فارسی' },
      { title: 'کارِن', description: 'جنگجو', rootName: 'فارسی' },
      { title: 'کياشا', description: 'فرمانروا', rootName: 'فارسی' },
      { title: 'کیارش', description: 'پادشاه و شهریار دلیر', rootName: 'فارسی' },
      { title: 'کِيسان', description: 'از بزرگان و پادشاهان ', rootName: 'فارسی' },
      { title: 'کوهیار', description: 'استوار و پابرجا', rootName: 'فارسی' },
      { title: 'کایان', description: 'آب تندی که از قله کوه جاری میشود', rootName: 'ترکی' },
      { title: 'کاوان', description: 'صخره ', rootName: 'کردی' },
      { title: 'کیارام', description: ' الفت گرفته با پادشاهان  ', rootName: 'فارسی' },
      { title: 'کیاسا', description: 'مانند شاه', rootName: 'فارسی' },
      { title: 'کاریا', description: 'مرد جنگجو', rootName: 'کردی' },
    ],
  },
  G: {
    category: 'گ',
    list: [
      { title: 'گوشیار', description: 'نام حکیمی از فارس ', rootName: 'فارسی' },
      { title: 'گئومات', description: 'پسر کوروش', rootName: 'فارسی' },
      { title: 'گایار', description: 'یار قدرتمند ', rootName: 'کردی' },
      { title: 'گُردیا', description: 'شجاع و دلير ', rootName: 'فارسی' },
      { title: 'گَرشا', description: 'پادشاه كوه ', rootName: 'فارسی باستان' },
      { title: 'گشواد', description: 'نام یک پهلوان ايراني', rootName: 'فارسی' },
    ],
  },
  L: {
    category: 'ل',
    list: [
      { title: 'لیام', description: 'محافظ', rootName: 'فارسی' },
      { title: 'لیوراد', description: 'خورشید جوانمرد ', rootName: 'فارسی' },
      { title: 'لوران', description: 'زاده لر', rootName: 'لری' },
      { title: 'لاهور', description: 'یکتا', rootName: 'کردی' },
      { title: 'لَهاک', description: 'از شخصیتهای شاهنامه ', rootName: 'فارسی' },
    ],
  },
  M: {
    category: 'م',
    list: [
      { title: 'مانیاد', description: ' عزیز و گرامی ', rootName: 'فارسی' },
      { title: 'مِرآت', description: 'آینه', rootName: 'عربی' },
      { title: 'مادیار', description: 'ياور و كمك كننده مادر ', rootName: 'لری' },
      { title: 'مِهداد', description: 'داده ماه ', rootName: 'فارسی' },
      { title: 'میلان', description: ' آرزو', rootName: 'عربی' },
      { title: 'مَرتيا', description: 'جوانمرد', rootName: 'فارسی' },
      { title: 'مِهربد', description: 'نگهبان مهربانی', rootName: 'فارسی' },
      { title: 'معيد', description: ' ماهر', rootName: 'عربی' },
      { title: 'ماجد', description: 'بزرگوار ', rootName: 'عربی' },
      { title: 'مِهياد', description: 'دارای چهره‌ای زیبا چون ماه ', rootName: 'فارسی' },
      { title: 'میراث', description: 'ارث', rootName: 'عربی' },
      { title: 'مِهرزاد', description: 'زاده خورشید  ', rootName: 'فارسی' },
      { title: 'مَهزيار', description: ' صاحب کوهستان', rootName: 'فارسی' },
      { title: 'ماهِد', description: 'یکی از نام‌های خداوند ', rootName: 'عربی' },
      { title: 'میران', description: 'شاهانه', rootName: 'عربی' },
      { title: 'ماکان', description: 'شجاع', rootName: 'فارسی' },
      { title: 'مانیار', description: 'یار ماندگار ', rootName: 'فارسی' },
      { title: 'مَهبد', description: ' نگه‌دارنده ماه', rootName: 'فارسی' },
      { title: 'مَهديار', description: 'یار حضرت مهدی (عج) ', rootName: 'عربی' },
      { title: 'مسیحا', description: 'لقب حضرت عیسی (ع) ', rootName: 'فارسی' },
    ],
  },
  N: {
    category: 'ن',
    list: [
      { title: 'نویان', description: 'شاهزاده', rootName: 'ترکی' },
      { title: 'نیهاد', description: ' سرشت', rootName: 'کردی' },
      { title: 'نیکراد', description: 'جوانمرد صالح ', rootName: 'فارسی' },
      { title: 'نیکسام', description: ' پسر خورشید ', rootName: 'فارسی' },
      { title: 'نَريمان', description: 'از شخصیت‌های شاهنامه', rootName: 'فارسی باستان' },
      { title: 'نيکمِهر', description: ' داراي مهر و محبت ', rootName: 'فارسی' },
      { title: 'نیواد', description: 'شجاعت و دلیری', rootName: 'فارسی' },
      { title: 'نیکاد', description: 'خوشنام', rootName: 'ترکی' },
      { title: 'نوحا', description: 'راهنما ', rootName: 'عبری' },
      { title: 'نیاراد', description: 'از خاندان جوانمرد', rootName: 'فارسی' },
      { title: 'نیروان', description: 'رهایی از زندگی مادی', rootName: 'سانسکریت' },
      { title: 'نامبد', description: 'صاحب نام ', rootName: 'فارسی' },
      { title: 'نوتاش', description: 'همیشگی', rootName: 'فارسی' },
      { title: 'نیوراد', description: 'پهلوان جوانمرد ', rootName: 'فارسی' },
      { title: 'نیوسا', description: 'مانند پهلوان ', rootName: 'فارسی' },
      { title: 'ناسیکو', description: 'شکست ناپذیر', rootName: 'کردی' },
      { title: 'نیشام', description: 'فرشته نگهبان آذرخش ', rootName: 'فارسی' },
      { title: 'نامین', description: 'مشهور', rootName: 'فارسی' },
      { title: 'نیوزاد', description: ' زاده دلیر و شجاع  ', rootName: 'فارسی' },
      { title: 'نوژَن', description: 'صنوبر', rootName: 'فارسی' },
    ],
  },
  V: {
    category: 'و',
    list: [
      { title: 'ویهان', description: 'نیکان', rootName: 'فارسی  ' },
      { title: 'وِسام', description: 'خوبرویان', rootName: ' عربی ' },
      { title: 'والا', description: ' دارنده مقام و مرتبه مهم', rootName: 'فارسی' },
      { title: 'ویام', description: 'یاری کننده', rootName: 'فارسی باستان' },
      { title: 'وانیار', description: 'باسواد', rootName: 'کردی' },
      { title: 'وِداد', description: 'دوستی', rootName: 'عربی' },
      { title: 'وِهاد', description: 'مسیر مطمئن', rootName: 'عربی' },
      { title: 'وانتیار', description: 'نام پسر ایرج ', rootName: 'فارسی' },
      { title: 'وَهنیا', description: 'کسی که از نسل خوبان است ', rootName: 'فارسی' },
      { title: 'واتیار', description: 'سخنگو', rootName: 'کردی' },
      { title: 'وارتان', description: ' نام پسر بلاش اول پادشاه اشکانی ', rootName: 'ارمنی' },
      { title: 'وَسپار', description: 'آفریننده همه ', rootName: 'فارسی' },
      { title: 'وِریا', description: 'حقیقت', rootName: 'لاتین' },
      { title: 'والی', description: 'پادشاه', rootName: 'عربی' },
      { title: 'وَهان', description: 'جمع خوبان', rootName: 'فارسی' },
      { title: 'وَنداد', description: 'بشارت دهنده پیروزی', rootName: 'فارسی باستان' },
      { title: 'وَسیم', description: '  دارای نشان زیبایی', rootName: 'عربی' },
      { title: 'وَهرِز', description: ' نام سردار ایرانی ', rootName: 'فارسی' },
    ],
  },
  H2: {
    category: 'ه',
    list: [
      { title: 'هیرمان', description: 'به یاد ماندنی ', rootName: 'لری' },
      { title: 'هایان', description: 'پشتیبان', rootName: 'ترکی' },
      { title: 'هورزاد', description: 'زاده خورشید ', rootName: 'فارسی' },
      { title: 'هورداد', description: 'تابنده', rootName: 'فارسی' },
      { title: 'هودین', description: 'آئين نيك ', rootName: 'فارسی' },
      { title: 'هوپاد', description: 'نيك سرشت ', rootName: 'فارسی' },
      { title: 'هیرساد', description: 'خورشید پاک', rootName: 'فارسی' },
      { title: 'هیمن', description: 'موقر', rootName: 'کردی' },
      { title: 'هورام', description: 'پیرو نیکی ', rootName: 'عبری' },
      { title: 'هیروان', description: 'حافظ و نگهبان آتش ', rootName: 'فارسی' },
      { title: 'هامون', description: 'دشت و زمین هموار ', rootName: 'فارسی' },
      { title: 'هومان', description: 'دارنده‌ی روح خوب ', rootName: 'فارسی' },
      { title: 'هوراد', description: ' مرد نیک‌نام ', rootName: 'فارسی' },
      { title: 'هامین', description: 'تابستان', rootName: 'فارسی باستان' },
      { title: 'هاکان', description: 'امپراطور', rootName: 'ترکی' },
      { title: 'هیراد', description: 'خوشرو', rootName: 'فارسی' },
      { title: 'هيربَد', description: 'آموزگار', rootName: 'فارسی باستان' },
      { title: 'هارون', description: '  نگهبان', rootName: 'عبری' },
    ],
  },

  Y: {
    category: 'ی',
    list: [
      { title: 'یَلسان', description: 'مانند پهلوان', rootName: 'فارسی' },
      { title: 'یاشار', description: 'جاویدان', rootName: 'ترکی' },
      { title: 'یارا', description: 'توانایی', rootName: 'فارسی' },
      { title: 'يَزدان', description: ' ایزد', rootName: 'فارسی' },
      { title: 'یونا', description: ' نام دیگر حضرت یونس(ع) ', rootName: 'عبری' },
      { title: 'یاوان', description: 'نوه پسری نوح پیامبر', rootName: 'عبری' },
      { title: 'یاردا', description: 'یار مادر ', rootName: 'لری' },
      { title: 'یاشام', description: 'عمر و زندگی ', rootName: 'ترکی' },
    ],
  },
};

export const NAME_SELECTION_BANNER_NAME_2 = 'name2';
