import { AlphabetBtnsListTypes } from '@components/SelectName/AlphabetBtns/types';

export const PERSIAN_BOY_NAME_DICTIONARY: AlphabetBtnsListTypes = {
  ا: {
    category: 'ا',
    list: [
      { title: 'ابراهیم', description: 'دوست خدا، پدر قوم‌ها', rootName: 'پارسی، عبری' },
      { title: 'اردوان', description: 'مرد عادل، نگهبان حقیقت', rootName: 'پارسی' },
      { title: 'اردشیر', description: 'پادشاه نیک', rootName: 'پارسی' },
      { title: 'ارژنگ', description: 'ارزشمند، گران‌بها', rootName: 'پارسی' },
      { title: 'اسفندیار', description: 'نام شخصیت قهرمانی در شاهنامه، مقدس', rootName: 'پارسی' },
      { title: 'اشکان', description: 'بنیان‌گذار، مرتبط با سلسله اشکانیان', rootName: 'پارسی' },
      { title: 'امید', description: 'آرزو،  انتظار مثبت', rootName: 'پارسی' },
      { title: 'اردلان', description: 'مرد نیک، حقیقت مقدس', rootName: 'پارسی، کردی' },
      { title: 'اورنگ', description: 'تخت پادشاهی، شکوه و عظمت', rootName: 'پارسی' },
      { title: 'امان', description: 'آرامش، امنیت، پناه', rootName: 'پارسی' },
      { title: 'اَنوش', description: 'جاویدان، ابدی', rootName: 'پارسی' },
      { title: 'اَردا', description: 'مقدس، پاک', rootName: 'پارسی' },
      { title: 'امرتات', description: 'جاودانگی، بی‌مرگی، نام مقدس در فرهنگ زرتشتی', rootName: 'پارسی، اوستایی' },
      { title: 'اهورا', description: 'نام خدایان ایرانیان باستان و زرتشتیان، خداوند', rootName: 'پارسی، اوستایی' },
    ],
  },
  آ: {
    category: 'آ',
    list: [
      {
        title: 'آبان',
        description: 'نام روز دهم از هر ماه شمسی ایرانی، نام فرشته موکل آب و تدبیر امور مسائل آبان ماه',
        rootName: 'پارسی',
      },
      { title: 'آبتین', description: 'نیکوکار، نام پدر فریدون پادشاه پیشدادی', rootName: 'پارسی' },
      {
        title: 'آتروپات',
        description: 'آذرپناه، نگهبان آتش، یکی از سرداران هخامنشی و پارسی',
        rootName: 'پهلوی و اوستایی',
      },
      {
        title: 'آترین',
        description: 'شبیه به آتش، درخشان یا مقدس، نام پسر اوپدرم در زمان داريوش بزرگ.',
        rootName: 'پارسی',
      },
      {
        title: 'آذرباد',
        description: 'نگهبان آتش، کسی که مانند آتش نیرومند است، نام موبد موبدان روزگار شاپور دوم.',
        rootName: 'پارسی و اوستایی',
      },
      { title: 'آذرخش', description: 'رعد و برق، صاعقه', rootName: 'پارسی' },
      { title: 'آذین', description: 'زیور، آراستن، نام فرمانده لشکر بابک خرمدین', rootName: 'پارسی' },
      {
        title: 'آراد',
        description:
          'آزاد، سخاوتمند، نام فرشته‌ موکل بر دین و تدبیر امور روز آراد، نام روز بیست و پنجم ماه شمسی، (در پهلوی) آرای، آراینده',
        rootName: 'پارسی',
      },
      { title: 'آرتین', description: 'منسوب به آرت، پاکی و تقدس، نام هفتمین پادشاه ماد', rootName: 'پارسی' },
      {
        title: 'آرش',
        description: 'درخشنده، قهرمان اسطوره‌ای ایرانی که تیرانداز معروف داستان‌هاست.',
        rootName: 'پارسی و اوستایی',
      },
      {
        title: 'آرشام',
        description: 'قدرت و عظمت آریایی، نام پدر ویشتاسب، یکی از پادشاهان هخامنشی.',
        rootName: 'پارسی',
      },
      { title: 'آرشان', description: 'مرد، نام پسر اردشیر دوم پادشاه هخامنشی', rootName: 'پارسی' },
      { title: 'آرمان', description: 'آرزو، هدف، خواسته بزرگ', rootName: 'پارسی' },
      { title: 'آرمین', description: 'آرام، صلح‌جو، نام یکی از شخصیت‌های تاریخی پارسی.', rootName: 'پارسی' },
      {
        title: 'آریا',
        description: 'نجیب، اصیل، شریف، آزاد، فرمانده ارتش ایران در زمان کوروش',
        rootName: 'پارسی و اوستایی',
      },
      { title: 'آریو', description: 'شریف، نجیب، کوتاه‌شده آریوبرزن (سردار هخامنشی).', rootName: 'پارسی' },
      {
        title: 'آریوبرزن',
        description: 'آتش ایرانی، شکوه آریایی، دلاور و پهلوان، نام سردار هخامنشی، داریوش سوم',
        rootName: 'پارسی',
      },
      { title: 'آریامنش', description: 'دارای خوی و رفتار آریایی، نام پسر داریوش', rootName: 'پارسی' },
      { title: 'آرمیا', description: 'آرامش‌بخش، صلح‌جو', rootName: 'پارسی' },
      { title: 'آزاد', description: 'رها، صاحب اختیار', rootName: 'پارسی' },
      { title: 'آریاسب', description: 'دارنده اسب‌های نجیب، نام شخصیتی در اوستا.', rootName: 'پارسی و اوستایی' },
      {
        title: 'آریامهر',
        description: 'برخوردار از محبت آریایی، نام یکی از سرداران داریوش سوم پادشاه هخامنشی',
        rootName: 'پارسی',
      },
      { title: 'آوید', description: 'دانش و خرد، مشتاق', rootName: 'پارسی' },
    ],
  },
  B: {
    category: 'ب',
    list: [
      { title: 'بابک', description: 'پدر کوچک، نام قهرمان تاریخی ایرانی (بابک خرمدین).', rootName: 'پارسی' },
      { title: 'بارْبَد', description: 'نگهبان روشنی، نام نوازنده معروف دوره ساسانی.', rootName: 'پارسی' },
      { title: 'بامداد', description: 'سحرگاه، صبح زود، نام پدر مزدک', rootName: 'پارسی' },
      { title: 'بارمان', description: 'شایسته، با شکوه.', rootName: 'پارسی' },
      { title: 'بامشاد', description: 'شاد در سحر، نام یکی از موسیقی‌دانان دوره ساسانی', rootName: 'پارسی' },
      {
        title: 'بختیار',
        description: 'خوشبخت، دارای بخت و اقبال، از فرزندان رستم در روزگار خسرو پرویز',
        rootName: 'پارسی',
      },
      { title: 'برازمان', description: 'بلند اندیشه، شایسته و باشکوه', rootName: 'پارسی' },
      { title: 'بردیا', description: 'والا، نام پسر کوروش بزرگ و یکی از پادشاهان هخامنشی', rootName: 'پارسی' },
      { title: 'برزو', description: 'بلندقامت، نام پسر سهراب در شاهنامه', rootName: 'پارسی' },
      { title: 'برسام', description: 'آتش بزرگ، دارای شکوه و عظمت', rootName: 'پارسی' },
      { title: 'برمک', description: 'شکوهمند یا دارای عظمت، نام وزیر شیروی ساسانی', rootName: 'پارسی' },
      {
        title: 'بزرگمهر',
        description:
          'مهر والا، خورشید بزرگ، نام شخصیت تاریخی  معروف دوره ساسانی، بزرگمهر بن بختگان، وزیر و مشاور خردمند انوشیروان (خسرو اول)',
        rootName: 'پارسی',
      },
      {
        title: 'بهمن',
        description: 'نیک‌اندیش، نام ماه یازدهم تقویم ایرانی و ایزد نیک‌خواهی.',
        rootName: 'ریشه پارسی و اوستایی',
      },
      { title: 'بهراد', description: 'نیکی‌بخش، نیک‌مرد', rootName: 'پارسی' },
      {
        title: 'بهرام',
        description: 'پیروز، فاتح؛ نام ستاره مریخ و یکی از ایزدان زرتشتی.',
        rootName: 'ریشه پارسی و اوستایی',
      },
      { title: 'بهروز', description: 'روزگار نیک و خوش', rootName: 'پارسی' },
      { title: 'بهزاد', description: 'نیک‌زاده، کسی که از نژاد خوب است.', rootName: 'پارسی' },
      { title: 'بهمرد', description: 'مرد نیک، انسان شریف و خوب', rootName: 'پارسی' },
      { title: 'بهنام', description: 'نیک‌نام، دارای شهرت خوب.', rootName: 'پارسی' },
      { title: 'بیژن', description: 'جوانمرد، نام پسر گیو، یکی از پهلوانان شاهنامه', rootName: 'پارسی' },
      { title: 'بهشاد', description: 'شاد و نیک، دارای شادی و خیر', rootName: 'پارسی' },
    ],
  },
  P: {
    category: 'پ',
    list: [
      { title: 'پادرا', description: 'سرزمین باشکوه، نگهبان آتش', rootName: 'پارسی' },
      { title: 'پارسا', description: 'پرهیزکار، پاکدامن، پارسا و متدین', rootName: 'پارسی' },
      { title: 'پارسیا', description: 'متعلق به پارس، نجیب، شریف', rootName: 'پارسی' },
      { title: 'پاکان', description: 'پاکیزه، نیکوکار', rootName: 'پارسی' },
      { title: 'پاکزاد', description: 'زاده پاک، از نژاد نیک', rootName: 'پارسی' },
      { title: 'پاکمهر', description: 'دارای محبت پاک، شخص مهربان و نیک', rootName: 'پارسی' },
      { title: 'پدرام', description: 'نام نبیره سام؛ درود، شادباش، آراسته', rootName: 'پارسی' },
      { title: 'پرشان', description: 'رزمجو، پرشکوه، دارای عظمت و جلال', rootName: 'پارسی' },
      { title: 'پرشنگ', description: 'درخشان، پرنور، شاد و سرزنده', rootName: 'پارسی' },
      { title: 'پرهام', description: 'فرشته خوبی، صورت پارسی نام ابراهیم', rootName: 'پارسی، اوستایی' },
      { title: 'پرویز', description: 'شکست‌ناپذیر و پیروزمند؛ کنیه خسرو دوم ساسانی', rootName: 'پارسی' },
      { title: 'پژمان', description: 'دلتنگ، غمگین', rootName: 'پارسی' },
      {
        title: 'پوریا',
        description: 'پسر آریایی، پر از نور، شجاع، نام پهلوان معروف ایرانی، پوریای ولی',
        rootName: 'پارسی',
      },
      { title: 'پویا', description: 'جوینده، فعال، سرزنده و پرتحرک', rootName: 'پارسی' },
      { title: 'پوژان', description: 'پویا، سرزنده، گاهی به معنای جستجوگر', rootName: 'پارسی' },
      { title: 'پولاد', description: 'فولاد، نام پهلوانی در زمان کیقباد', rootName: 'پارسی' },
      { title: 'پیمان', description: 'عهد، سوگند، وعده؛ نماد وفاداری', rootName: 'پارسی' },
      { title: 'پیام', description: 'الهام، وحی، پیغام', rootName: 'پارسی' },
      { title: 'پیروز', description: 'فاتح، نام پادشاه ساسانی', rootName: 'پارسی' },
      { title: 'پیلتن', description: 'نیرومند، پهلوانی بوده از فرزندان رستم زال', rootName: 'پارسی' },
    ],
  },
  T1: {
    category: 'ت',
    list: [
      { title: 'تخشا', description: 'کوشنده، تلاشگر', rootName: 'پارسی' },
      {
        title: 'تَنسَر',
        description: 'نام موبد موبدان روزگار اردشیر بابکان، روحانی برجسته زرتشتی در دوره ساسانی',
        rootName: 'پارسی',
      },
      { title: 'تهماسب', description: 'طهماسب، به معنی دارنده اسب قوی', rootName: 'پارسی' },
      { title: 'تهمتن', description: 'بزرگ‌پیکر، نیرومند، لقب رستم پهلوان داستانی شاهنامه', rootName: 'پارسی' },
      { title: 'تهمین', description: 'پهلوان، شجاع، از القاب رستم پهلوان شاهنامه', rootName: 'پارسی' },
      { title: 'تهمورس', description: 'نیرومند، دلیر و پهلوان؛ نام دومین پادشاه خردمند پیشدادی', rootName: 'پارسی' },
      { title: 'تارخ', description: 'تاریک، شب، گاهی به معنای اسرارآمیز', rootName: 'پارسی' },
      { title: 'تامراد', description: 'آرزوی کامل، کسی که به اهدافش می‌رسد', rootName: 'پارسی' },
      { title: 'تاووس', description: 'پرنده طاووس، نماد زیبایی و شکوه', rootName: 'پارسی' },
      { title: 'ترسا', description: 'پاک‌دامن، پرهیزکار', rootName: 'پارسی' },
      { title: 'تیران', description: 'نام پسر اردشیر سوم، نامی اشکانی به معنای تیرانداز', rootName: 'پارسی' },
      { title: 'تیرداد', description: 'زاده‌شده در تیر، بخشنده تیر، نام پادشاه اشکانی', rootName: 'پارسی' },
      { title: 'تورج', description: 'دلیر، پهلوان؛ نام پسر بزرگ فریدون', rootName: 'پارسی' },
      { title: 'توس', description: 'نام پسر نوذر، پهلوان نامی ایران در شاهنامه', rootName: 'پارسی' },
      { title: 'توانا', description: 'نیرومند، زورمند', rootName: 'پارسی' },
    ],
  },
  J: {
    category: 'ج',
    list: [
      {
        title: 'جاماسب',
        description: 'دارنده اسب درخشان، نام یکی از شخصیت‌های شاهنامه و اوستا، برادر گشتاسب',
        rootName: 'پارسی و اوستایی',
      },
      {
        title: 'جامشید',
        description: 'پادشاه درخشان، نام پادشاه اسطوره‌ای پیشدادی در شاهنامه، بنیان‌گذار نوروز',
        rootName: 'پارسی و اوستایی',
      },
      { title: 'جان‌نثار', description: 'فداکار، کسی که جان خود را نثار می‌کند', rootName: 'پارسی' },
      { title: 'جاوید', description: 'ابدی، جاودان', rootName: 'پارسی' },
      { title: 'جهان', description: 'گیتی، عالم', rootName: 'پارسی' },
      { title: 'جهانگیر', description: 'فاتح جهان، نام پسر رستم زال', rootName: 'پارسی' },
      { title: 'جانان', description: 'محبوب، دلیر، عزیز، روح و جان', rootName: 'پارسی' },
      { title: 'جهانشاه', description: 'پادشاه جهان، نامی با حس عظمت', rootName: 'پارسی' },
      { title: 'جمشید', description: 'از پادشاهان پیشدادی', rootName: 'پارسی' },
    ],
  },
  CH: {
    category: 'چ',
    list: [
      { title: 'چابک', description: 'سریع، فرز، چالاک', rootName: 'پارسی' },
      { title: 'چاوش', description: 'پیشرو، راهنما، کاروان‌سالار', rootName: 'پارسی' },
      { title: 'چهرزاد', description: 'زاده چهره زیبا، دارای ظاهر نیکو', rootName: 'پارسی' },
      { title: 'چینوَد', description: 'چگونه زیستن', rootName: 'ریشه پارسی اوستایی' },
    ],
  },
  H1: {
    category: 'ح',
    list: [
      { title: 'حانان', description: 'مهربان، عاشق، معشوق', rootName: 'پارسی' },
      { title: 'حامد', description: 'ستایشگر، شکرگزار', rootName: 'ریشه عربی و فارسی' },
      { title: 'حامی', description: 'پشتیبان، حامی، نگهبان', rootName: 'ریشه عربی و فارسی' },
      { title: 'حسام', description: 'شمشیر بران، نماد شجاعت و قدرت', rootName: 'ریشه عربی و فارسی' },
    ],
  },
  KH: {
    category: 'خ',
    list: [
      { title: 'خداداد', description: 'داده‌شده توسط خدا، نعمت الهی', rootName: 'پارسی' },
      { title: 'خدابخش', description: 'بخشیده‌شده توسط خدا، هدیه الهی', rootName: 'پارسی' },
      { title: 'خاور', description: 'شرق، مشرق، نماد طلوع خورشید و روشنایی', rootName: 'پارسی' },
      { title: 'خدیو', description: 'سرور، بلند جایگاه', rootName: 'پارسی' },
      { title: 'خردمند', description: 'نام یکی از پیروان دستور آذرکیوان', rootName: 'پارسی' },
      { title: 'خرم', description: 'شادمان، خوش', rootName: 'پارسی' },
      { title: 'خسرو', description: 'نیک آواز، نام پادشاه ساسانی', rootName: 'پارسی' },
      { title: 'خشایار', description: 'شاه دلیر، پادشاه قهرمان', rootName: 'ریشه پارسی و اوستایی' },
    ],
  },
  D: {
    category: 'د',
    list: [
      { title: 'داتام', description: 'آفریننده و مخلوق، نام یکی از فرماندهان پارسی کاپادوکیه', rootName: 'پارسی' },
      { title: 'داتیس', description: 'سرداری از مردم ماد و از سرداران داریوش هخامنشی', rootName: 'پارسی' },
      { title: 'دادمهر', description: 'عدالت دوست؛ نام چند تن از امیر زادگان و شاهزادگان در تاریخ', rootName: 'پارسی' },
      { title: 'دارا', description: 'برخوردار از چیزی، صاحب، مالک، ثروتمند', rootName: 'پارسی' },
      { title: 'دامون', description: 'دشت و صحرا؛ از حکمای قدیم یونان و از فیثاغوریان', rootName: 'پارسی' },
      { title: 'دانا', description: 'دارای عقل و تجربه، خردمند، عاقل، عالم', rootName: 'پارسی' },
      { title: 'دانوش', description: 'نام شخصی در داستان وامق و عذرا', rootName: 'پارسی' },
      { title: 'دایان', description: 'سرافرازی، تکیه گاه', rootName: 'پارسی' },
    ],
  },
  R: {
    category: 'ر',
    list: [
      { title: 'رَسام', description: 'رسم کننده، طراح، نقاش', rootName: 'پارسی' },
      { title: 'رَها', description: 'نجات یافته و آزاد، آزادانه، رهایی', rootName: 'پارسی' },
      { title: 'رُهام', description: 'نام پهلوان ایرانی در شاهنامه', rootName: 'پارسی' },
      { title: 'راتین', description: 'رادترین، نام یکی از سرداران اردشیر دوم پادشاه ساسانی', rootName: 'پارسی' },
      {
        title: 'رادمان',
        description: 'رادمنش، کریم، با‌سخاوت، نام سرداری معاصر خسرو پرویز ساسانی.',
        rootName: 'پارسی',
      },
      { title: 'رادمهر', description: 'خورشید بخشنده، بخشنده همچون خورشید', rootName: 'پارسی' },
      { title: 'رادنوش', description: 'مرکب از راد (جوانمرد، بخشنده) + نوش (نیوشنده)', rootName: 'پارسی' },
      { title: 'رادوین', description: 'جوانمرد کوچک', rootName: 'پارسی' },
      { title: 'رادین', description: 'بخشنده، جوانمرد', rootName: 'پارسی' },
      {
        title: 'راژان',
        description: 'خوابیدن، جنبیدن گهواره، روستایی در بخش سیلوانا شهرستان ارومیه',
        rootName: 'پارسی و کردی',
      },
      { title: 'راستین', description: 'حقیقی، واقعی، راست قامت', rootName: 'پارسی' },
      { title: 'رامبُد', description: 'رئیس رامشگران؛ آرامش دهنده، فرشته', rootName: 'پارسی' },
      { title: 'رامتین', description: 'نوازنده، سازنده؛ نام شخصی که واضع چنگ بوده', rootName: 'پارسی' },
      { title: 'رامسین', description: 'گونه‌ی کهنه رامتین به معنی سازنده و نوازنده است.', rootName: 'پارسی' },
      { title: 'رایان', description: 'باهوش و دانشمند، نگهبان آسمان', rootName: 'پارسی' },
      {
        title: 'رستاک',
        description: 'شاخه‌ی تازه‌ای که از بیخ درخت برآید، زاده‌ی درخت مو، رویشگاه',
        rootName: 'پارسی',
      },
    ],
  },
  Z2: {
    category: 'ز',
    list: [
      {
        title: 'زامیاد',
        description: 'زاده فرشتگان، نگهبان زمین، نام روز بیست و هشتم از هر ماه شمسی در قدیم',
        rootName: 'پارسی',
      },
      { title: 'زانکو', description: 'به دنبال دانش و علم، شبیه به کوه', rootName: 'پارسی و کردی' },
      { title: 'زانیار', description: 'یار دانا و دانشمند', rootName: 'پارسی و کردی' },
      { title: 'زادان', description: 'زاده‌شده، فرزند', rootName: 'پارسی' },
      { title: 'زادمهر', description: 'زاده مهر، فرزند خورشید یا محبت', rootName: 'پارسی' },
      { title: 'زال', description: 'سپیدمو، نام پدر رستم در شاهنامه', rootName: 'پارسی' },
      { title: 'زرتشت', description: 'دارنده شتر زرین، نام پیامبر آیین زرتشتی.', rootName: 'پارسی و اوستایی' },
    ],
  },
  ZH: {
    category: 'ژ',
    list: [
      { title: 'ژاوه', description: 'نوعی گیاهی وحشی از تیره کاکوتی', rootName: 'پارسی و کردی' },
      {
        title: 'ژاماسب',
        description: 'جاماسب، از شخصیتهای شاهنامه، نام خردمندی ایرانی، وزیر و راهنمای لهراسپ و گشتاسپ پادشاهان کیانی',
        rootName: 'پارسی',
      },
      { title: 'ژاو', description: 'خالص و چکیده هر چیز', rootName: 'پارسی و کردی' },
      { title: 'ژوان', description: 'میعادگاه عاشق و معشوق', rootName: 'پارسی و کردی' },
      {
        title: 'ژوپین',
        description: 'ژوپین، نیزه کوچک که در جنگهای قدیم به سوی دشمن پرتاب می‌کردند.',
        rootName: 'پارسی',
      },
      { title: 'ژیار', description: 'شهرنشینی، تمدن؛ زندگی شهروندان', rootName: 'پارسی و کردی' },
      { title: 'ژیان', description: 'خشمناک و غضبناک؛ بی‌باک و شجاع', rootName: 'پارسی و کردی' },
      { title: 'ژیوار', description: 'زندگی، نام کوهی در اورامان', rootName: 'پارسی و کردی' },
    ],
  },
  S2: {
    category: 'س',
    list: [
      {
        title: 'ساتیار',
        description: 'از نامهای زرتشتی که گونه‌ی دیگر آن به نظر میرسد سادیار باشد، نام یکی از سرداران داریوش.',
        rootName: 'پارسی',
      },
      { title: 'ساشا', description: 'مدافع و محافظ مردان', rootName: 'پارسی' },
      {
        title: 'سام',
        description: 'آتش، از شخصیت‌های شاهنامه، نام پهلوان ایرانی پسر نریمان و پدر زال',
        rootName: 'پارسی',
      },
      {
        title: 'سامان',
        description: 'سرزمین، ناحیه، محل، مکان، ترتیب و روش چیزی یا کاری، ثروت، دارایی، قوت، توانایی؛ صبر، آرام و قرار',
        rootName: 'پارسی',
      },
      { title: 'سامی', description: 'عالی، بلند مرتبه، بلند؛ منسوب به سام پسر نوح نبی (ع)', rootName: 'پارسی' },
      { title: 'سامیار', description: 'ثروتمند', rootName: 'پارسی' },
      { title: 'سپنتا', description: 'پاک و مقدس', rootName: 'پارسی' },
      { title: 'سپهر', description: 'آسمان، روزگار', rootName: 'پارسی' },
      { title: 'سپهراد', description: 'جوانمرد سپاه و لشکر، شجاع و دلیر', rootName: 'پارسی' },
      {
        title: 'سورن',
        description: 'دلیر و توانا، نام سردار ایرانی، نام یکی از خاندانهای هفتگانه ممتاز در زمان اشکانیان',
        rootName: 'پارسی',
      },
      { title: 'سروش', description: 'فروغ اهورایی، پیام‌آور الهی یا الهام', rootName: 'پارسی' },
      { title: 'سورنا', description: 'سردار دلیر پارتی معاصر اشک سیزدهم', rootName: 'پارسی' },
      { title: 'سیاوش', description: 'دارنده‌ اسب نر سیاه، پسر کیکاووس پادشاه کیانی', rootName: 'پارسی' },
    ],
  },
  SH: {
    category: 'ش',
    list: [
      { title: 'شادمهر', description: 'دارای شادی و مهربانی', rootName: 'پارسی' },
      { title: 'شارونا', description: 'سرزمین پربار و حاصلخیز', rootName: 'آشوری' },
      {
        title: 'شاها',
        description: 'نام قلعه‌ای که هولاکوخان اموال و خزاین خود را آنجا گذاشته بود.',
        rootName: 'پارسی',
      },
      { title: 'شاهرخ', description: 'دارای رخساری چون شاه، شاه منظر، شاه سیما', rootName: 'پارسی' },
      { title: 'شاهین', description: 'نوعی پرنده‌ی شکاری از خانواده‌ی باز؛ برج میزان', rootName: 'پارسی' },
      { title: 'شایان', description: 'شایسته، سزاوار، در خور؛ فراوان', rootName: 'پارسی' },
      {
        title: 'شروین',
        description: 'معشوق مردمان، پایدار و نامی، نام قلعه‌ی شروان؛ نام انوشیروان دادگر',
        rootName: 'پارسی',
      },
      {
        title: 'شهاب',
        description:
          'پدیده‌ای به شکل خطی درخشان که به علت برخورد سنگ آسمانی با جو زمین و سوختن سریع آن به طور ناگهانی در آسمان دیده می‌شود، بزرگی و جلال',
        rootName: 'پارسی',
      },
      { title: 'شهراد', description: 'پادشاهِ جوانمرد', rootName: 'پارسی' },
      { title: 'شهنام', description: 'بزرگ نام و دارنده‌ی نامِ شاهانه؛ نیکنام، نکونام', rootName: 'پارسی' },
      { title: 'شهیاد', description: 'مرکب از شه (شاد) + یاد (خاطره)', rootName: 'پارسی' },
      { title: 'شهیار', description: 'همدم، همنشین و مونس شاه؛ نظیر و همتای شاه، بلند مرتبه', rootName: 'پارسی' },
    ],
  },
  S3: {
    category: 'ص',
    list: [
      { title: 'صابر', description: 'صبور، صبر کننده، شکیبا؛ از نامهای خداوند', rootName: 'پارسی و عربی' },
      {
        title: 'صاحب',
        description: 'دارنده، مالک، دارا، همنشین و همصحبت، یار، فرمانروا و حاکم',
        rootName: 'پارسی و عربی',
      },
      { title: 'صانع', description: 'سازنده، آفریننده؛ صنعتگر؛ آفریدگار، خداوند', rootName: 'پارسی و عربی' },
      { title: 'صدرا', description: 'منسوب به صدر', rootName: 'پارسی و عربی' },
    ],
  },
  T2: {
    category: 'ط',
    list: [
      { title: 'طهماسب', description: 'دارنده‌ی اسب قوی - نام دو تن از پادشاهان صفوی', rootName: 'پارسی' },
      {
        title: 'طُوُرْگ',
        description:
          'از شخصیت‌های شاهنامه، نام دلاوری تورانی از فرماندهان سپاه افراسیاب تورانی، نیز نام سرداری ایرانی در زمان کیخسرو پادشاه کیانی',
        rootName: 'پارسی',
      },
      { title: 'طینوش', description: 'از شخصیت‌های شاهنامه', rootName: 'پارسی' },
      {
        title: 'طاهر',
        description: 'پاک، پاکیزه، بی‌گناه، معصوم، نام چهارمین امیر سلسله‌ی طاهریان',
        rootName: 'پارسی و عربی',
      },
    ],
  },
  A2: {
    category: 'ع',
    list: [
      { title: 'عرشام', description: 'قوی، نیرومند', rootName: 'پارسی' },
      { title: 'عرشیا', description: 'پادشاه راستین، دارای تخت و تاج', rootName: 'پارسی' },
    ],
  },
  GH1: {
    category: 'غ',
    list: [
      {
        title: 'غاتفَر',
        description: 'از شخصیت‌های شاهنامه، نام پادشاه هیتال در زمان انوشیروان پادشاه ساسانی، نام شهری در آسیای میانه',
        rootName: 'پارسی',
      },
      { title: 'غوغا', description: 'هیاهو، شور و شوق', rootName: 'پارسی' },
    ],
  },
  F: {
    category: 'ف',
    list: [
      { title: 'فارناک', description: 'فارناس، نام برادر همسر داریوش سوم پادشاه هخامنشی', rootName: 'پارسی' },
      { title: 'فرابرز', description: 'نام پهلوانی ایرانی از سپه داران و رایزنان دارا', rootName: 'پارسی' },
      { title: 'فرابین', description: 'بلندنظر و عاقبت اندیش', rootName: 'پارسی' },
      { title: 'فراد', description: 'گشایش، بخشش', rootName: 'پارسی' },
      { title: 'فرادین', description: 'دیندار، متدین', rootName: 'پارسی' },
      {
        title: 'فراز',
        description: 'بلندترین بخش از جایی، بلندی، در قدیم مجاز از خوبی و خوشیِ حال و وضع',
        rootName: 'پارسی',
      },
      { title: 'فرازین', description: 'بالایی، فرازی', rootName: 'پارسی' },
      { title: 'فربد', description: 'نگهبان یا محافظِ شکوه و جلال', rootName: 'پارسی' },
      { title: 'فربین', description: 'بیننده‌ی شکوه و جلال', rootName: 'پارسی' },
      { title: 'فرجاد', description: 'فاضل و دانشمند', rootName: 'پارسی' },
      { title: 'فرداد', description: 'شکوه، زیبایی و جلال', rootName: 'پارسی' },
      { title: 'فرزاد', description: 'زاده شکوه و جلال', rootName: 'پارسی' },
      { title: 'فرزام', description: 'لایق، درخور، شایسته', rootName: 'پارسی' },
      { title: 'فرسام', description: 'دارای شکوه و عظمت', rootName: 'پارسی' },
      { title: 'فرمند', description: 'دارای شکوه و وقار', rootName: 'پارسی' },
      { title: 'فرنود', description: 'برهان، دلیل', rootName: 'پارسی' },
      { title: 'فرهان', description: 'منسوب به فره، با شکوه و بزرگ', rootName: 'پارسی' },
      { title: 'فراهین', description: 'موجب شکوه آیین، فرآیین', rootName: 'پارسی' },
      { title: 'فریور', description: 'راست و درست', rootName: 'پارسی' },
    ],
  },
  GH2: {
    category: 'ق',
    list: [
      { title: 'قهرمان', description: 'دلاور', rootName: 'پارسی، عربی' },
      {
        title: 'قارُن',
        description: 'از خاندان‌های اشرافی ایران در دوره‌ اشکانیان و ساسانیان - نام پسر کاوه‌ آهنگر',
        rootName: 'پارسی',
      },
      { title: 'قباد', description: 'محبوب، شاه محبوب، سرور گرامی', rootName: 'پارسی، عربی' },
    ],
  },
  K: {
    category: 'ک',
    list: [
      { title: 'کابوک', description: 'آشیانه پرندگان', rootName: 'پارسی' },
      { title: 'کابی', description: 'معرب منسوب به کاوه آهنگر', rootName: 'پارسی' },
      { title: 'کارا', description: 'مفید، مؤثر', rootName: 'پارسی' },
      {
        title: 'کارِن',
        description:
          'شجاع و دلیر، نام فرزند کاوه آهنگر و همچنین نام سردار لشکر مهرداد شاهزاده اشکانی که علیه اشک بیستم (گودرز) قیام کرد.',
        rootName: 'پارسی',
      },
      { title: 'کارون', description: 'نام رودی در جنوب غربی ایران', rootName: 'پارسی' },
      { title: 'کامبین', description: 'نیک‌بخت، سعادتمند، توانگر، کامیاب، خوشدل و بهره‌مند', rootName: 'پارسی' },
      { title: 'کامراد', description: 'نام وزیر و مشاور آبتین نام پارسی', rootName: 'پارسی' },
      { title: 'کامروز', description: 'خوشبخت', rootName: 'پارسی' },
      { title: 'کامین', description: 'آرزو، قصد', rootName: 'پارسی' },
      { title: 'کهزاد', description: 'زاده کوه', rootName: 'پارسی' },
      { title: 'کوشا', description: 'ریشه گیاهی خوشرنگ', rootName: 'پارسی' },
      { title: 'کیاراد', description: 'جوانمرد', rootName: 'پارسی' },
      { title: 'کیارش', description: 'از شخصیتهای شاهنامه، نام دومین پسر کیقباد پادشاه کیانی', rootName: 'پارسی' },
      { title: 'کیازاد', description: 'پادشاه زاده', rootName: 'پارسی' },
      { title: 'کیاشا', description: 'پادشاه، سلطان، حاکم', rootName: 'پارسی' },
    ],
  },
  G: {
    category: 'گ',
    list: [
      {
        title: 'گرازه',
        description: 'از شخصیت‌های شاهنامه، نام سردار ایرانی در سپاه کیکاووس پادشاه کیانی',
        rootName: 'پارسی',
      },
      {
        title: 'گراهون',
        description: 'از شخصیت‌های شاهنامه، نام دلاوری زابلی در سپاه گرشاسپ پادشاه کیانی',
        rootName: 'پارسی',
      },
      {
        title: 'گرداب',
        description: 'از شخصیت‌های گرشاسب‌نامه، نام پهلوانی ایرانی در سپاه گرشاسب پهلوان نامدار',
        rootName: 'پارسی',
      },
      { title: 'گرآزاد', description: 'پهلوان آزاده، از پهلوانان حماسه ملی ایران', rootName: 'پارسی' },
      { title: 'گردیا', description: 'مبارز، دلاور', rootName: 'پارسی' },
      { title: 'گَرَستون', description: 'از شخصیت‌های شاهنامه، نام سردار سپاه ماهوی سوری', rootName: 'پارسی' },
      { title: 'گرشاه', description: 'گلشاه، لقب کیومرث، پادشاه کوه', rootName: 'پارسی' },
      { title: 'گرمائیل', description: 'نام یکی از دو برادر نیکوکار ضحاک', rootName: 'پارسی' },
      {
        title: 'گشتاسب',
        description: 'نام پسر لهراسب پادشاه کیان که خواهان پادشاهی از پدر بود، و نام پدر داریوش بزرگ پادشاه هخامنشی',
        rootName: 'پارسی',
      },
      { title: 'گلپاد', description: 'نگهبان، محافظ', rootName: 'پارسی' },
      { title: 'گویا', description: 'گوینده، سخنگو، مجاز از رسا و روشن', rootName: 'پارسی' },
    ],
  },
  L: {
    category: 'ل',
    list: [
      { title: 'لاهور', description: 'یکتا', rootName: 'پارسی' },
      { title: 'لاشار', description: 'نام طایفه ای از طوایف بلوچ', rootName: 'پارسی' },
      { title: 'لیام', description: 'حامی و محافظ', rootName: 'پارسی' },
      { title: 'لاوین', description: 'نام منطقه‌ مرزی در غرب ایران', rootName: 'پارسی' },
      { title: 'لهراسب', description: 'نام سومین پادشاه سلسله کیانی، صاحب اسب تندرو', rootName: 'پارسی، اوستایی' },
      { title: 'لوران', description: 'لُر‌زاده', rootName: 'پارسی' },
      { title: 'لهاک', description: 'از شخصیت‌های شاهنامه', rootName: 'پارسی' },
      { title: 'لیشام', description: 'نام یکی از وطن پرستان دیلمی', rootName: 'پارسی، اوستایی' },
    ],
  },
  M: {
    category: 'م',
    list: [
      { title: 'ماتیار', description: 'کمک‌کننده', rootName: 'پارسی' },
      { title: 'ماراب', description: 'بخت و دولت تازه', rootName: 'پارسی' },
      { title: 'مازیار', description: 'ایزدیار', rootName: 'پارسی' },
      { title: 'مانی', description: 'اندیشمند، جاودانگی', rootName: 'پارسی' },
      { title: 'مانیاد', description: 'عزیز و گرامی', rootName: 'پارسی' },
      { title: 'مهشاد', description: 'خوش سیما', rootName: 'پارسی' },
      { title: 'ماهان', description: 'نام پسر کیخسرو', rootName: 'پارسی' },
      { title: 'ماهبد', description: 'نگهبان ماه', rootName: 'پارسی' },
      { title: 'ماهداد', description: 'داده و بخشیده ماه', rootName: 'پارسی' },
      { title: 'ماهفر', description: 'دارای فر و شکوه', rootName: 'پارسی' },
      { title: 'مرتیا', description: 'جوانمرد', rootName: 'پارسی' },
      { title: 'مهبود', description: 'وزیر و گنجور بیدار دل انوشیروان که دلی پر خرد و درست داشت', rootName: 'پارسی' },
      { title: 'مهداد', description: 'بزرگ‌زاده', rootName: 'پارسی' },
      { title: 'مهرآزاد', description: 'نام یکی از اجداد رستم', rootName: 'پارسی' },
      { title: 'مهرداد', description: 'داده مهر، آفریده شده در مهر', rootName: 'پارسی' },
      { title: 'مهرسام', description: 'پسر خونگرم و مهربان', rootName: 'پارسی' },
      { title: 'مهرشاد', description: 'خورشید هدایت‌کننده', rootName: 'پارسی' },
      { title: 'مهراد', description: 'جوانمرد', rootName: 'پارسی' },
      { title: 'مهرام', description: 'خوشبخت', rootName: 'پارسی' },
      { title: 'مهران', description: 'دارنده مهر', rootName: 'پارسی' },
      { title: 'مهیاد', description: 'بزرگ‌تر', rootName: 'پارسی' },
      {
        title: 'مهیار',
        description: 'ماهیار، پهلوان ایرانی که نام او دو بار در گرشاسب نامه‌ اسدی طوسی آمده.',
        rootName: 'پارسی',
      },
    ],
  },
  N: {
    category: 'ن',
    list: [
      { title: 'ناردان', description: 'دانه ترش انار', rootName: 'پارسی' },
      { title: 'ناروان', description: 'درخت انار', rootName: 'پارسی' },
      { title: 'نامجو', description: 'مجاز از نامدار، مشهور', rootName: 'پارسی' },
      { title: 'نامدار', description: 'دارای آوازه و شهرت', rootName: 'پارسی' },
      { title: 'نامی', description: 'مشهور و معروف', rootName: 'پارسی' },
      { title: 'نامین', description: 'مشهور', rootName: 'پارسی' },
      { title: 'نریمان', description: 'مرد سرشت و دلیر و پهلوان', rootName: 'پارسی، اوستایی' },
      { title: 'نَستَهَن', description: 'نام پهلوان تورانی', rootName: 'پارسی' },
      { title: 'نهاد', description: 'سرشت، طبیعت', rootName: 'پارسی' },
      {
        title: 'نوذر',
        description:
          'در شاهنامه نام پسر منوچهر، یکی از پادشاهان کیانی که پس از او به سلطنت رسید و به دست افراسیاب گرفتار و سپس کشته شد.',
        rootName: 'پارسی',
      },
      { title: 'نوراهان', description: 'تحفه، سوغات', rootName: 'پارسی' },
      { title: 'نوژن', description: 'نوعی کاج، صنوبر', rootName: 'پارسی' },
      { title: 'نوشاد', description: 'مجاز از جوان نورسته‌ی شاداب', rootName: 'پارسی' },
      { title: 'نوشفر', description: 'دارای فر و شکوه جاوید', rootName: 'پارسی' },
      {
        title: 'نوشیار',
        description: 'یار شیرین چون عسل، یار بی مرگ، نام پسرعموی گرشاسپ در گرشاسپ نامه',
        rootName: 'پارسی',
      },
      { title: 'نوید', description: 'خبر خوش', rootName: 'پارسی' },
      { title: 'نوین', description: 'جدید', rootName: 'پارسی' },
      { title: 'نیاسان', description: 'شبیه به نیاکان', rootName: 'پارسی' },
      { title: 'نیاوند', description: 'مجاز از از نژاد نیاکان، از نسل اجداد', rootName: 'پارسی' },
      {
        title: 'نیروان',
        description: 'نام رودخانه‌ای در شهرستان سقز که از مجموع دو رودخانه‌ی سلیمان بیک و بوین تشکیل می‌شود.',
        rootName: 'پارسی',
      },
      { title: 'نیرشام', description: 'نام فرشته نگهبان آذرخش', rootName: 'پارسی' },
      { title: 'نیک آرا', description: 'آراینده خوبی و نیکی', rootName: 'پارسی' },
      { title: 'نیک داد', description: 'داده‌ی نیک', rootName: 'پارسی' },
      { title: 'نیک روز', description: 'خوشبخت', rootName: 'پارسی' },
      { title: 'نیک نام', description: 'دارای آبرو و اعتبار، خوشنام', rootName: 'پارسی' },
      { title: 'نیکان', description: 'شخص نیک', rootName: 'پارسی' },
      { title: 'نیک‌یار', description: 'صالح و شایسته', rootName: 'پارسی' },
      { title: 'نیما', description: 'نام‌آور، نام یکی از اسپهبدان تبرستان', rootName: 'پارسی' },
      { title: 'نیوان', description: 'پهلوان و دلیر و شجاع', rootName: 'پارسی' },
    ],
  },
  V: {
    category: 'و',
    list: [
      { title: 'وادان', description: 'نام روستایی در نزدیکی دماوند', rootName: 'پارسی' },
      { title: 'وادگان', description: 'نام شخصی در وندیداد', rootName: 'پارسی' },
      { title: 'واردان', description: 'نام دادوری در زمان اردشیر بابکان پادشاه ساسانی', rootName: 'پارسی' },
      { title: 'والایار', description: 'یارِ والامقام و بلندمرتبه', rootName: 'پارسی' },
      { title: 'وانان', description: 'نام روستایی در نزدیکی شهرکرد، نام یکی از پادشاهان اشکانی', rootName: 'پارسی' },
      { title: 'وانتیار', description: 'نام پسر ایرج به نوشته بندهشن', rootName: 'پارسی' },
      {
        title: 'ورازداد',
        description:
          'دارنده زور و نیرومندی، نام یکی از شاهزادگان اشکانی فرماندار ارمنستان در زمان بهرام گور پادشاه ساسانی',
        rootName: 'پارسی',
      },
      { title: 'ورازمهر', description: 'از نام‌های دوره ساسانیان', rootName: 'پارسی' },
      { title: 'ورزاک', description: 'نام پدر مهرترسه وزیر یزدگرد اول پادشاه ساسانی', rootName: 'پارسی' },
      { title: 'وریا', description: 'قوی و درشت هیکل، چکش آهنی بزرگ', rootName: 'پارسی، کردی' },
      { title: 'وَسپور', description: 'واسپور، لقب نجبا و شاهزادگان اشکانی و ساسانی', rootName: 'پارسی' },
      { title: 'وهزاد', description: 'نام اسب سیاوش، زاده خوب و نیکو', rootName: 'پارسی' },
      { title: 'وهنیا', description: 'بهنیا، کسی که از نسل خوبان است', rootName: 'پارسی' },
      { title: 'ویهان', description: 'وهان، نیکان- در پهلوی به معنی بهانه، علت، سبب', rootName: 'پارسی' },
    ],
  },
  H2: {
    category: 'ه',
    list: [
      { title: 'هارپاک', description: 'مرواریدی که در یک رشته کشیده شده باشد', rootName: 'پارسی' },
      { title: 'هامان', description: 'نام وزیر خشایارشاه', rootName: 'پارسی' },
      { title: 'هامون', description: 'دشت و زمین هموار', rootName: 'پارسی' },
      { title: 'هامی', description: 'سرگشته و حیران', rootName: 'پارسی' },
      { title: 'هامین', description: 'تابستان در اوستا', rootName: 'پارسی' },
      { title: 'هِرواک', description: 'نام دیگر خسروپرویز پادشاه ساسانی', rootName: 'پارسی، اوستایی' },
      {
        title: 'هزاره',
        description: 'یکی از شخصیتهای شاهنامه، لقب کوت از سرداران رومی سپاه خسروپرویز پادشاه ساسانی',
        rootName: 'پارسی',
      },
      { title: 'هژیز', description: 'خوب، پسندیده', rootName: 'پارسی' },
      { title: 'هماوند', description: 'از نامهای امروزی زرتشتیان', rootName: 'پارسی' },
      { title: 'همایون', description: 'خجسته، مبارک', rootName: 'پارسی' },
      {
        title: 'همراد',
        description: 'ویژگی دو کس که در همت، سخاوت، شجاعت و جوانمردی و کرم شبیه به هم باشند.',
        rootName: 'پارسی',
      },
      { title: 'همنواد', description: 'از شخصیتهای شاهنامه در زمان ساسانیان', rootName: 'پارسی' },
      { title: 'هوپاد', description: 'نگهبان خوب، نیک‌سرشت', rootName: 'پارسی' },
      { title: 'هوتن', description: 'خوب‌تن، نیک‌اندام', rootName: 'پارسی' },
      { title: 'هوراد', description: 'جوانمرد', rootName: 'پارسی' },
      { title: 'هورداد', description: 'داده خورشید', rootName: 'پارسی' },
      { title: 'هورزاد', description: 'فرزند خورشید، مجاز از دارای زیبایی و شکوه', rootName: 'پارسی' },
      { title: 'هورشاد', description: 'شاد و خوشحال', rootName: 'پارسی' },
      { title: 'هورمن', description: 'اندیشه و فکر روشن', rootName: 'پارسی' },
      { title: 'هورمند', description: 'دارای درخشندگی و روشنی', rootName: 'پارسی' },
      { title: 'هوریار', description: 'یار و دوست خورشید', rootName: 'پارسی' },
      { title: 'هوشبام', description: 'بامداد، فلق', rootName: 'پارسی' },
      { title: 'هوشمند', description: 'عاقل، با‌خرد', rootName: 'پارسی' },
      {
        title: 'هومن',
        description: 'دارنده‌ روح خوب و نیک اندیش، نام پسر ویسه و برادران پیران و یکی از سرداران افراسیاب',
        rootName: 'پارسی',
      },
      { title: 'هومهر', description: 'دارای عشق و محبت خوب، نیک مهر', rootName: 'پارسی' },
      { title: 'هونام', description: 'نیک‌نام، خوش‌نام', rootName: 'پارسی' },
      { title: 'هویدا', description: 'روشن، آشکار', rootName: 'پارسی' },
      { title: 'هیراد', description: 'خود را به مردم تازه روی و خوشحال وانمود کردن', rootName: 'پارسی' },
      { title: 'هیربد', description: 'آموزگار، معلم، رئیس آتشکده در دین زرتشتی', rootName: 'پارسی' },
      { title: 'هیرسا', description: 'پارسا و پاکدامن', rootName: 'پارسی' },
      { title: 'هیرود', description: 'نام یکی از پادشاهان پارت (اشکانی)', rootName: 'پارسی' },
    ],
  },
  Y: {
    category: 'ی',
    list: [
      { title: 'یارا', description: 'توانایی، قدرت', rootName: 'پارسی' },
      { title: 'یاران', description: 'دوستان، رفیقان', rootName: 'پارسی' },
      { title: 'یارتا', description: 'همتای یار، همچون یار', rootName: 'پارسی' },
      { title: 'یارمند', description: 'دارای دوست و یار', rootName: 'پارسی' },
      { title: 'یارور', description: 'یاریگر، یاور', rootName: 'پارسی' },
      { title: 'یاسان', description: 'از برساخته‌های فرقه‌ی آذرکیوان', rootName: 'پارسی' },
      { title: 'یاور', description: 'کمک‌کننده', rootName: 'پارسی' },
      { title: 'یاوند', description: 'فرمانروا، پادشاه', rootName: 'پارسی' },
      { title: 'یزدان', description: 'خداوند، ایزد، در ادیان و در مذاهب ثنوی، خدای خیر و نیکی', rootName: 'پارسی' },
      { title: 'یزدان‌مهر', description: 'مهر خدایی، نشانه‌ی مهر و محبت ایزدی', rootName: 'پارسی' },
      {
        title: 'یزدیار',
        description: 'نام پدر دستور بهمنیار، از موبدان کرمان در زمان یزدگرد پادشاه ساسانی',
        rootName: 'پارسی',
      },
      { title: 'یَشتار', description: 'پرستنده، نمازگزار', rootName: 'پارسی' },
    ],
  },
};

export const NAME_SELECTION_BANNER_NAME_2 = 'name2';
