export const data = [
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 1,
    rateAvg: 0.9,
    description: 'توضیحات پریود - کم وزن',
    title: 'ویجت پریود - کم وزن',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/DR2.png',
    writerName: 'دکتر راحله ابراهیمی',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'مشاهده',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=67502c58753c0d901b61aff3&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '674db1c8f848faa492547bc1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 2,
    rateAvg: 4.67,
    description: 'test',
    title: 'با همه چیز',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/Mask%20group.png',
    writerName: 'نگار رمضان پور',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'test',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=687cd8b87c62ddc436fc1740&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '673d97aa6f3e0999b36f83f1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 4,
    rateAvg: 0.83,
    description: 'توضیحات مربوط به روتین روز یک تا هفت پریود را در این بخش مشاهده می فرمایید. ',
    title: 'روتین روز یک تا هفت پریود',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/Mask%20group.png',
    writerName: 'نگار رمضان پور',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'دکمه ی روتین',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=6746c1c035426ded8af402e5&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '673d97aa6f3e0999b36f83f1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 5,
    rateAvg: 2.18,
    description:
      ' این رژیم، یک روتین غذاییه که مناسب با یه دوره ی پریود سه روزه طراحی شده. با رعایت کردنش بیشتر از همیشه از خودت مراقبت کن.',
    title: 'رژیم غذایی سه روزه ی پریود',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/Mask%20group.png',
    writerName: 'نگار رمضان پور',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'دیدن رژیم ',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=674db411f848faa492547bdb&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '673d97aa6f3e0999b36f83f1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 3,
    rateAvg: 2.22,
    description: 'برای اینکه تو روزهای پریود راحت تر باشی و حس بهتری به خوت داشته باشی',
    title: 'استایل دوران پریود',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/styleroutin/IMG_20241221_145625_203.jpg',
    writerName: 'رویا راد',
    writerSpeciality: 'استایلیست و طراح لباس',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'مشاهده',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=6766b15a0900827a2b36f078&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '6766a9270900827a2b3600e7',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 3,
    rateAvg: 2.5,
    description: '5',
    title: '1',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/DR2.png',
    writerName: 'دکتر راحله ابراهیمی',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: '4',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=684fa2405c627208a6e18df3&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '674db1c8f848faa492547bc1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 1,
    rateAvg: 3.33,
    description: 'توضیحات ',
    title: 'روتین',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/Mask%20group.png',
    writerName: 'نگار رمضان پور',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'روتین',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=685142b8121a7e3cb717967c&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '673d97aa6f3e0999b36f83f1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 1,
    rateAvg: 3,
    description: 'فلتبغتببیتسقئفقغعئبالی',
    title: 'روتین بدرد نخور',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/DR2.png',
    writerName: 'دکتر راحله ابراهیمی',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'مشاهده',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=685a6a83565dcfa5b100e981&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '674db1c8f848faa492547bc1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 0,
    rateAvg: 3,
    description: 'کلی',
    title: 'کلی',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/Mask%20group.png',
    writerName: 'نگار رمضان پور',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'کلی',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=687218eaa979667ebb4ca202&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '673d97aa6f3e0999b36f83f1',
    bmiTitle: 'BMI شما: 27.343748',
  },
  {
    completeTitle: '',
    completeRatio: 0,
    isBookmarked: false,
    commentCount: 0,
    rateAvg: 0,
    description: '',
    title: '111111111',
    writerIcon: 'https://s3.ir-tbz-sh1.arvanstorage.ir/impo/writing-pic/Mask%20group.png',
    writerName: 'نگار رمضان پور',
    writerSpeciality: 'جراح و متخصص زنان، زایمان و نازایی',
    button: {
      backgroundColor: '0xFFE54E7F',
      foregroundColor: '0xFFFFFFFF',
      text: 'مشاهده',
      action: {
        actionType: 1,
        actionTypes: [],
        internal: '/diet?id=68ac0b17c04f81bc6eca5d05&WomanStatus=1',
        api: '',
        nextStep: {
          type: 0,
          data: {},
          isDismissible: false,
          delaySecond: 0,
        },
      },
    },
    bmiDescription: '673d97aa6f3e0999b36f83f1',
    bmiTitle: 'BMI شما: 27.343748',
  },
];
