import { PackagesTypes } from './types';

export const INITAIL_PACKAGE: PackagesTypes = {
  amount: '',
  code: '',
  desciption: '',
  discount: 0,
  discountText: '',
  id: '',
  inAppPurchase: false,
  isFree: false,
  isSpecial: false,
  //   isSpecific: false,
  markdown: '',
  payBtnText: '',
  //   payButtonText: '',
  //   realValue: 0,
  realValueText: '',
  specialText: '',
  //   specificText: '',
  subTitle: '',
  text: '',
  title: '',
  totalAmount: '',
  totalPay: 0,
  totalPayText: '',
  totalText: '',
  totalUnit: '',
  unit: '',
  value: 0,
  valueText: '',
  vat: 0,
  //   vatText: '',
  viewId: '',
};
