export const Comments = [
  {
    userName: 'hengameh',
    userAvatar: '/assets/images/clinicLanding/avatar.webp',
    userText: 'فوق العاده صبور و مهربون و پاسخ جامع و کامل، ازشون سپاسگزارم😍😍',
    userRate: 5,
    drAvatar: '/assets/images/clinicLanding/drAvatar.webp',
    drBio: 'ویزیت زنان، زایمان و نازایی با دکتر پروانه حسینی',
  },
  {
    userName: 'ریحانه',
    userAvatar: '/assets/images/clinicLanding/avatar1.webp',
    userText: 'یه مشاور عالی و فوق‌العاده هستین',
    userRate: 5,
    drAvatar: '/assets/images/clinicLanding/drAvatar1.webp',
    drBio: 'ویزیت اختلالات جنسی با سکس تراپیست مرجان طوسانی',
  },
  {
    userName: 'سارا',
    userAvatar: '/assets/images/clinicLanding/avatar2.webp',
    userText: 'خیلی خوب بودن با صبوری به همه سوالات پاسخ دادن، این دکتر بهتون پیشنهاد میکنم حتما',
    userRate: 5,
    drAvatar: '/assets/images/clinicLanding/drAvatar2.webp',
    drBio: 'ویزیت مامایی با کارشناس مامایی، عالمه جهانی',
  },
  {
    userName: 'نگار',
    userAvatar: '/assets/images/clinicLanding/avatar3.webp',
    userText: 'در اسرع وقت پاسخ دادند و باعث آرامشم شدند',
    userRate: 5,
    drAvatar: '/assets/images/clinicLanding/drAvatar3.webp',
    drBio: 'ویزیت روان‌شناسی با روانشناس بالینی، پریسا بابالو',
  },
  {
    userName: 'آذر',
    userAvatar: '/assets/images/clinicLanding/avatar4.webp',
    userText: 'هنوز داروهایی که تجویز کردن رو استفاده نکردم ولی رفتار محترمانه‌شون منو جذب کرد و همه چیز خوب بود',
    userRate: 4,
    drAvatar: '/assets/images/clinicLanding/drAvatar4.webp',
    drBio: 'ویزیت روان‌پزشکی با روانشناس بالینی، الهه رعیت‌نواز',
  },
];
