export const WHEEL_PICKER_CELL_HEIGHT = 45;
export const WHEEL_PICKER_TOTAL_CELLS = 5;
export const WHEEL_PICKER_EXTRA_CELLS = 2;
export const WHEEL_PICKER_HANDLE_INITIAL_SLIDE_DELAY = 0.1;
export const WHEEL_PICKER_MIN_ITEMS = WHEEL_PICKER_EXTRA_CELLS * 2 + 1;
