import { AlphabetBtnsListTypes } from '@components/SelectName/AlphabetBtns/types';

export const PERSIAN_NAME_DICTIONARY: AlphabetBtnsListTypes = {
  ا: {
    category: 'ا',
    list: [
      { title: 'الناز', description: 'ناز بیش از حد', rootName: 'فارسی' },
      { title: 'الیکا', description: 'گل همیشه بهار', rootName: 'فارسی' },
      { title: 'انوشا', description: 'جاودانه و خوشبخت', rootName: 'اوستایی' },
      { title: 'اهورا', description: 'خداوند', rootName: 'اوستایی' },
      { title: 'ایوانا', description: 'شکوفایی و زندگی', rootName: 'فارسی' },
      { title: 'انوشک', description: 'کوچک جاوید', rootName: 'اوستایی' },
      { title: 'ایران‌دخت', description: 'دختر ایران', rootName: 'شاهنامه' },
    ],
  },
  آ: {
    category: 'آ',
    list: [
      { title: 'آوا', description: 'نغمه، آواز خوش', rootName: 'فارسی' },
      { title: 'آریانا', description: 'سرزمین آریایی‌ها، ایران', rootName: 'اوستایی' },
      { title: 'آریادخت', description: 'دختر ایران', rootName: 'فارسی' },
      { title: 'آوید', description: 'آواز، نوای خوش', rootName: 'فارسی' },
      { title: 'آرام', description: 'دل‌آرام و روح مطمئن', rootName: 'فارسی' },
      { title: 'آوینا', description: 'زلال و روان همچون چشمه', rootName: 'فارسی' },
      { title: 'آناهید', description: 'ایزدبانوی آب‌ها، نماد پاکی', rootName: 'شاهنامه' },
      { title: 'آوانه', description: 'بانوی نغمه و آهنگ', rootName: 'فارسی' },
      { title: 'آذین‌دخت', description: 'دختری آراسته و زیبا همچون شعله‌ی آتش، دختر آذین', rootName: 'شاهنامه' },
    ],
  },
  B: {
    category: 'ب',
    list: [
      { title: 'بارانا', description: 'بارانی که زمین را زنده می‌کند', rootName: 'فارسی' },
      { title: 'بیداریس', description: 'روشنایی و فروغ', rootName: 'فارسی' },
      { title: 'بهرانوش', description: 'شیرینی زندگی', rootName: 'فارسی' },
      { title: 'بیتا', description: 'بی‌مانند و یگانه', rootName: 'فارسی' },
      { title: 'بانو', description: 'زنی بزرگوار و اصیل', rootName: 'فارسی' },
      { title: 'بهنوش', description: 'نوش پاک و زندگی‌بخش', rootName: 'فارسی' },
      { title: 'باران', description: 'بارش آسمانی، نماد پاکی', rootName: 'فارسی' },
    ],
  },
  P: {
    category: 'پ',
    list: [
      { title: 'پرنیا', description: 'دختری لطیف و زیبا، همچون گل', rootName: 'فارسی' },
      { title: 'پرتو', description: 'نوری که روشنی می‌بخشد', rootName: 'فارسی' },
      { title: 'پریماه', description: 'زیبا و درخشان، مانند ماه', rootName: 'فارسی' },
      { title: 'پریان', description: 'فرشتگان، زیبا و روح‌انگیز', rootName: 'فارسی' },
      { title: 'پرواز', description: 'آزاد، نماد رهایی و حرکت', rootName: 'فارسی' },
      { title: 'پریسا', description: 'زیبا و افسونگر مثل پری', rootName: 'شاهنامه' },
      { title: 'پریا', description: 'موجودی زیبا و افسانه‌ای', rootName: 'فارسی' },
      { title: 'پردیس', description: 'بهشت', rootName: 'فارسی' },
      { title: 'پرناز', description: 'جلوه‌ای از زیبایی، ظرافت و ناز', rootName: 'فارسی' },
    ],
  },
  T1: {
    category: 'ت',
    list: [
      { title: 'تابان', description: 'درخشان و نورانی', rootName: 'فارسی' },
      { title: 'تارا', description: 'ستاره', rootName: 'فارسی' },
      { title: 'تانیا', description: 'یگانه و بی‌همتا', rootName: 'فارسی' },
      { title: 'تیسا', description: 'پاک و روشن', rootName: 'فارسی' },
      { title: 'تیدا', description: 'خورشید کوچک، روشنی‌بخش', rootName: 'فارسی' },
      { title: 'تهمیسا', description: 'زنی دلیر و قدرتمند', rootName: 'فارسی' },
      { title: 'تینارا', description: 'نورانی و روشن', rootName: 'فارسی' },
      { title: 'توسا', description: 'دختری با قلب پاک و آرامش‌بخش', rootName: 'فارسی' },
      { title: 'تندیس', description: 'مجسمه و زیبایی جاودان', rootName: 'فارسی' },
      { title: 'تیاناز', description: 'نازنین و لطیف', rootName: 'فارسی' },
    ],
  },
  S1: {
    category: 'ث',
    list: [
      { title: 'ثنا', description: 'ستایش و تحسین', rootName: 'فارسی' },
      { title: 'ثمین', description: 'گوهری نایاب و ارزشمند', rootName: 'فارسی' },
      { title: 'ثریسا', description: 'فروزان و درخشان', rootName: 'فارسی' },
      { title: 'ثیلا', description: 'نرم و لطیف مانند نسیم بهاری', rootName: 'فارسی' },
      { title: 'ثناپارس', description: 'دختر اصیل و ستایشگر ایرانی', rootName: 'فارسی' },
      { title: 'ثناویر', description: 'پر از ستایش و زیبایی', rootName: 'فارسی' },
    ],
  },
  J: {
    category: 'ج',
    list: [
      { title: 'جانان', description: 'دختری با روح ماندگار، جاودانه', rootName: 'فارسی' },
      { title: 'جان‌آرا', description: 'دلربا و زیبا', rootName: 'فارسی' },
      { title: 'جان‌سو', description: 'زندگی‌بخش', rootName: 'فارسی' },
      { title: 'جان‌میسا', description: 'زندگی‌بخش و آرامش‌دهنده', rootName: 'فارسی' },
      { title: 'جانا', description: 'عزیز و محبوب', rootName: 'فارسی' },
      { title: 'جویا', description: 'کنجکاو و آزاد', rootName: 'فارسی' },
    ],
  },
  CH: {
    category: 'چ',
    list: [
      { title: 'چکامه', description: 'شعر و سرود', rootName: 'فارسی' },
      { title: 'چمن', description: 'سرسبز و خوشبو', rootName: 'فارسی' },
      { title: 'چکاوک', description: 'خوش‌صدا و لطیف', rootName: 'فارسی' },
      { title: 'چیستا', description: 'فرشته دانش و خرد', rootName: 'شاهنامه' },
      { title: 'چهرسا', description: 'دلنشین و زیبا', rootName: 'فارسی' },
      { title: 'چهرناز', description: 'دختر با چهره‌ای دلربا و ناز', rootName: 'فارسی' },
      { title: 'چشمه', description: 'پاک و زلال', rootName: 'فارسی' },
    ],
  },
  H1: {
    category: 'ح',
    list: [
      { title: 'حدیث', description: 'سخنی زیبا و دلنشین', rootName: 'فارسی' },
      { title: 'حسنا', description: 'زیبا و نیکو', rootName: 'فارسی' },
      { title: 'حور', description: 'روشن', rootName: 'فارسی' },
      { title: 'حورا', description: 'روشن و فروزان', rootName: 'فارسی' },
      { title: 'حنا', description: 'خوش‌بو و لطیف', rootName: 'فارسی' },
      { title: 'حسینا', description: 'زیبا و بامحبت، شاعری مجنون', rootName: 'فارسی' },
      { title: 'حورسا', description: 'همچون فرشته', rootName: 'فارسی' },
    ],
  },
  KH: {
    category: 'خ',
    list: [
      { title: 'خاتون', description: 'زنی بزرگ', rootName: 'فارسی' },
      { title: 'خوشه', description: 'خوشه گل و گندم، نماد برکت', rootName: 'فارسی' },
      { title: 'خاطره', description: 'یادآوری شیرین', rootName: 'فارسی' },
      { title: 'خرم', description: 'شاد و خوشحال', rootName: 'فارسی' },
      { title: 'خرشا', description: 'خورشید', rootName: 'شاهنامه' },
      { title: 'خزان', description: 'فصل پاییز، نماد تغییر و زیبایی', rootName: 'فارسی' },
      { title: 'خورشیدا', description: 'خورشید کوچک، نماد روشنایی و امید', rootName: 'فارسی' },
    ],
  },
  D: {
    category: 'د',
    list: [
      { title: 'دل‌آرا', description: 'کسی که دل‌ها را خوشحال می‌کند', rootName: 'فارسی' },
      { title: 'دل‌آسا', description: 'آرامش‌بخش', rootName: 'فارسی' },
      { title: 'دل‌یار', description: 'همراه دل', rootName: 'فارسی' },
      { title: 'دنیا', description: 'گیتی، جهان', rootName: 'فارسی' },
      { title: 'دلسا', description: 'همچون دل، پرعاطفه', rootName: 'فارسی' },
      { title: 'درسا', description: 'ارزشمند مانند مروارید', rootName: 'فارسی' },
      { title: 'دلارای', description: 'مادر روشنک، زنی که داراب برای او بود', rootName: 'شاهنامه' },
      { title: 'دل افروز', description: 'آورنده شادی و خوشی', rootName: 'شاهنامه' },
    ],
  },
  Z1: {
    category: 'ذ',
    list: [
      { title: 'ذلفا', description: 'دختری با چهره سفید و نورانی', rootName: 'عربی/ایرانی' },
      { title: 'ذریه', description: 'فرزند', rootName: 'قرآن' },
    ],
  },
  R: {
    category: 'ر',
    list: [
      { title: 'راتا', description: 'فرشته بخشش و مهربانی', rootName: 'شاهنامه' },
      { title: 'رکسانا', description: 'نام دختر دارا كه اسكندر با او ازدواج كرد.', rootName: 'شاهنامه' },
      { title: 'روشنک', description: 'نام دیگر رکسانا در شاهنامه', rootName: 'شاهنامه' },
      { title: 'رادیسا', description: 'تابان و درخشان', rootName: 'فارسی' },
      { title: 'راز', description: 'سرّ، رمز و رازی که دل را می‌رباید', rootName: 'فارسی' },
      { title: 'رازینا', description: 'پر از رمز و زیبایی', rootName: 'فارسی' },
      { title: 'رامینا', description: 'دلنشین', rootName: 'فارسی' },
      { title: 'ریتا', description: 'پاک و بی‌گناه', rootName: 'فارسی' },
      { title: 'ریما', description: 'دختر زیبا', rootName: 'فارسی' },
      { title: 'رُمانا', description: 'عاشقانه‌ای دلربا', rootName: 'فارسی' },
      { title: 'رامیس', description: 'آرامش‌بخش', rootName: 'فارسی' },
    ],
  },
  Z2: {
    category: 'ز',
    list: [
      { title: 'زربانو', description: 'دختر رستم', rootName: 'شاهنامه' },
      { title: 'زرتا', description: 'همچون زر', rootName: 'فارسی' },
      { title: 'زویا', description: 'ژر امید و حیات', rootName: 'فارسی' },
      { title: 'زیتا', description: 'خوش‌آوا و لطیف', rootName: 'فارسی' },
      { title: 'زیما', description: 'زمین', rootName: 'فارسی' },
      { title: 'زیوا', description: 'زیبا', rootName: 'فارسی' },
      { title: 'زروان', description: 'زمان و جاودانگی', rootName: 'فارسی' },
    ],
  },
  ZH: {
    category: 'ژ',
    list: [
      { title: 'ژوبین', description: 'نیزه کوچک، نماد ظرافت و قدرت', rootName: 'فارسی' },
      { title: 'ژاله', description: 'قطره شبنم', rootName: 'فارسی' },
      { title: 'ژیرا', description: 'دانا و خردمند', rootName: 'فارسی' },
      { title: 'ژیلا', description: 'باران نرم و لطیف', rootName: 'فارسی' },
      { title: 'ژیندخت', description: 'دختر زندگی', rootName: 'فارسی' },
      { title: 'ژامک', description: 'آینه', rootName: 'فارسی' },
    ],
  },
  S2: {
    category: 'س',
    list: [
      { title: 'ستیا', description: 'جهان هستی، روزگار', rootName: 'فارسی کهن' },
      { title: 'سیندخت', description: 'مادر رودابه، بانوی خردمند', rootName: 'شاهنامه' },
      { title: 'سمن‌ناز', description: 'زیبا و خوش‌چهره', rootName: 'فارسی' },
      { title: 'سوگند', description: 'قسم و اعتراف به سخن راست', rootName: 'فارسی' },
      { title: 'سریرا', description: 'زیبا', rootName: 'شاهنامه' },
      { title: 'سروین', description: 'مانند سرو', rootName: 'فارسی' },
      { title: 'سارینا', description: 'خالص و پاک', rootName: 'فارسی' },
      { title: 'سپینود', description: 'دختر پادشاه هند و همسر بهرام گور', rootName: 'شاهنامه' },
    ],
  },
  SH: {
    category: 'ش',
    list: [
      { title: 'شهرزاد', description: 'شهرزاد قصه‌گو، زاده شهر', rootName: 'فارسی' },
      { title: 'شاینا', description: 'شاهدانه، زیبا و درخشان', rootName: 'فارسی' },
      { title: 'شیدا', description: 'عاشق و دلداده', rootName: 'فارسی' },
      { title: 'شایلی', description: 'بی‌همتا', rootName: 'فارسی' },
      { title: 'شیددخت', description: 'دختر روشنایی و نور', rootName: 'شاهنامه' },
      { title: 'شادان', description: 'شاد و خرم', rootName: 'شاهنامه' },
      { title: 'شیده', description: 'دختر افراسیاب', rootName: 'شاهنامه' },
      { title: 'شادلین', description: 'مهربان و با نشاط', rootName: 'فارسی' },
    ],
  },
  S3: {
    category: 'ص',
    list: [
      { title: 'صبا', description: 'نسیم ملایم صبحگاهی', rootName: 'فارسی/عربی' },
      { title: 'صحرا', description: 'دشتی وسیع', rootName: 'فارسی/عربی' },
      { title: 'صنوبر', description: 'درختی زیبا و بلند', rootName: 'فارسی/عربی' },
      { title: 'صحبا', description: 'سراب سرخ، نماد عشق', rootName: 'فارسی/عربی' },
    ],
  },
  Z3: {
    category: 'ض',
    list: [
      { title: 'ضحی', description: 'روشنایی صبح', rootName: 'عربی/فارسی' },
      { title: 'ضربان', description: 'تپش', rootName: 'فارسی' },
    ],
  },
  T2: {
    category: 'ط',
    list: [
      { title: 'طلا', description: 'زر', rootName: 'فارسی' },
      { title: 'طناز', description: 'دلفریب', rootName: 'فارسی' },
      { title: 'طراوت', description: 'شادابی و تازگی', rootName: 'فارسی' },
      { title: 'طهورا', description: 'پاکی و زلالی', rootName: 'فارسی' },
    ],
  },
  Z4: {
    category: 'ظ',
    list: [{ title: 'ظفردخت', description: 'دختر پیروز', rootName: 'عربی/فارسی' }],
  },
  A2: {
    category: 'ع',
    list: [
      { title: 'عطرین', description: 'خوشبو', rootName: 'فارسی' },
      { title: 'عاطفه', description: 'مهربانی و دلسوزی', rootName: 'عربی/فارسی' },
      { title: 'عشانه', description: 'عشق، دوست داشتن', rootName: 'فارسی کهن' },
    ],
  },
  GH1: {
    category: 'غ',
    list: [
      { title: 'غنچه', description: 'شکوفه', rootName: 'فارسی' },
      { title: 'غزل', description: 'شعر عاشقانه', rootName: 'فارسی' },
      { title: 'غوغا', description: 'شور و هیاهو', rootName: 'فارسی' },
    ],
  },
  F: {
    category: 'ف',
    list: [
      { title: 'فریماه', description: 'دارای شکوهی چون ماه', rootName: 'فارسی' },
      { title: 'فرانک', description: 'زن بهرام گر، پروانه', rootName: 'شاهنامه' },
      { title: 'فریال', description: 'زن خوش‌اندام و زیباچهره', rootName: 'فارسی' },
      { title: 'فرنیا', description: 'اصیل', rootName: 'فارسی' },
      { title: 'فارا', description: 'نام کوهی در غرب فلات ایران', rootName: 'فارسی' },
      { title: 'فوژان', description: 'فریاد', rootName: 'فارسی' },
    ],
  },
  GH2: {
    category: 'ق',
    list: [
      { title: 'قاصدک', description: 'گیاهی که با باد پرواز می‌کند', rootName: 'فارسی' },
      { title: 'قیدافه', description: 'از شخصیت‌های شاهنامه', rootName: 'شاهنامه' },
      { title: 'قشنگ', description: 'زیبا و دلپسند', rootName: 'فارسی' },
      { title: 'قمرناز', description: 'ماه زیبا', rootName: 'فارسی' },
      { title: 'قمرسیما', description: 'زیبا همچون ماه', rootName: 'فارسی' },
    ],
  },
  K: {
    category: 'ک',
    list: [
      { title: 'کیمیا', description: 'نادر و کمیاب', rootName: 'فارسی' },
      { title: 'کیانا', description: 'جوهر و اصل هر چیزی', rootName: 'فارسی' },
      { title: 'کمند', description: 'گیسوی بلند', rootName: 'فارسی' },
      { title: 'کیارا', description: 'روشن و پاک', rootName: 'فارسی' },
      { title: 'کوشانه', description: 'بانوی تلاشگر', rootName: 'شاهنامه' },
      { title: 'کی‌دخت', description: 'شاهزاده خانم', rootName: 'شاهنامه' },
      { title: 'کتایون', description: 'همسر گشتاسپ پادشاه کیانی و مادر اسفندیار', rootName: 'شاهنامه' },
    ],
  },
  G: {
    category: 'گ',
    list: [
      { title: 'گلسا', description: 'مانند گل', rootName: 'فارسی' },
      { title: 'گیسا', description: 'عالم هستی', rootName: 'فارسی' },
      { title: 'گلارین', description: 'پاک و زلال', rootName: 'فارسی' },
      { title: 'گیتا', description: 'گیتی، آفرینش', rootName: 'فارسی کهن' },
      { title: 'گُلنوش', description: 'شهد گل', rootName: 'فارسی' },
      { title: 'گلرو', description: 'زیبا چون گل', rootName: 'فارسی' },
      { title: 'گلبرگ', description: 'برگ گل', rootName: 'فارسی' },
    ],
  },
  L: {
    category: 'ل',
    list: [
      { title: 'لیانا', description: 'بانوی درخشان', rootName: 'فارسی' },
      { title: 'لیان', description: 'تابان و نورانی', rootName: 'فارسی' },
      { title: 'لنا', description: 'نور و درخشندگی', rootName: 'فارسی' },
      { title: 'لیوسا', description: 'مثل خورشید', rootName: 'فارسی' },
      { title: 'لبخند', description: 'تبسم، خنده ملیح', rootName: 'فارسی' },
      { title: 'لنیا', description: 'دختر ملیح و بانمک', rootName: 'فارسی' },
      { title: 'لادن', description: 'گل زینتی به رنگ زرد، قرمز یا نارنجی', rootName: 'فارسی' },
    ],
  },
  M: {
    category: 'م',
    list: [
      { title: 'مهدیس', description: 'ماهرو', rootName: 'فارسی' },
      { title: 'مهرسا', description: 'شبیه خورشید، زیبارو', rootName: 'فارسی' },
      { title: 'مانلی', description: 'بمان برایم', rootName: 'فارسی' },
      { title: 'ملورین', description: 'دختری زیبا با چهره شفاف', rootName: 'فارسی' },
      { title: 'مهتا', description: 'مانند ماه', rootName: 'فارسی' },
      { title: 'مهرناز', description: 'دارای محبت و ناز', rootName: 'شاهنامه' },
      { title: 'ماندانا', description: 'مادر کورش کبیر', rootName: 'شاهنامه' },
      { title: 'مینو', description: 'بهشت', rootName: 'فارسی' },
      { title: 'مایا', description: 'بخشنده و نیک منش', rootName: 'فارسی کهن' },
      { title: 'مهگل', description: 'گل ماه، لطیف و زیبا', rootName: 'فارسی' },
    ],
  },
  N: {
    category: 'ن',
    list: [
      { title: 'نیکا', description: 'نیک و خوش', rootName: 'فارسی' },
      { title: 'نیاز', description: 'حاجت، دعا', rootName: 'فارسی' },
      { title: 'نیکی', description: 'خوبی و شایستگی', rootName: 'فارسی' },
      { title: 'نیروانا', description: 'آخرین مرحله سلوک عرفانی', rootName: 'فارسی' },
      { title: 'نازگل', description: 'دختری که مانند گل زیبا و ناز است', rootName: 'فارسی' },
      { title: 'نورسان', description: 'همچون نور، درخشان', rootName: 'فارسی' },
      { title: 'نیلا', description: 'به رنگ نیل', rootName: 'فارسی' },
      { title: 'نوشه', description: 'انوشه، جاویدان', rootName: 'شاهنامه' },
      { title: 'نایریکا', description: 'برگزیده', rootName: 'فارسی کهن' },
      { title: 'نوشید', description: 'تازگی و درخشندگی', rootName: 'فارسی کهن' },
      { title: 'نوژا', description: 'باطراوت', rootName: 'فارسی' },
    ],
  },
  V: {
    category: 'و',
    list: [
      { title: 'ورنا', description: 'جوانی', rootName: 'فارسی' },
      { title: 'ویدا', description: 'مظهر خرد و دانش', rootName: 'فارسی' },
      { title: 'ویشکا', description: 'جوانه، نو و تازه', rootName: 'فارسی' },
      { title: 'ویستا', description: 'دانش و فرهنگ', rootName: 'فارسی' },
      { title: 'والا', description: 'بالامقام و بلند مرتبه', rootName: 'فارسی' },
      { title: 'ویرا', description: 'هوشمندی', rootName: 'فارسی' },
    ],
  },
  H2: {
    category: 'ه',
    list: [
      { title: 'همیلا', description: 'بانوی زیبا', rootName: 'فارسی' },
      { title: 'هانا', description: 'شبیه به شکوفه‌ی درخت هِل، زیبا و خوشبو', rootName: 'فارسی' },
      { title: 'هلسا', description: 'همانند هل', rootName: 'فارسی' },
      { title: 'هستی', description: 'زندگی', rootName: 'فارسی' },
      { title: 'همتا', description: 'نظیر و مانند', rootName: 'فارسی' },
      { title: 'هیلا', description: 'نوعی پرنده', rootName: 'فارسی' },
      { title: 'همراز', description: 'محرم اسرار', rootName: 'فارسی' },
      { title: 'هیلدا', description: 'توانا و قوی', rootName: 'فارسی' },
      { title: 'هورمهر', description: 'زیباروی مهربان', rootName: 'فارسی' },
    ],
  },
  Y: {
    category: 'ی',
    list: [
      { title: 'یارین', description: 'خوشحالی', rootName: 'فارسی' },
      { title: 'یاسمینا', description: 'منسوب به یاسمن، گلی خوشبو', rootName: 'فارسی' },
      { title: 'یارناز', description: 'یار زیبا', rootName: 'فارسی' },
      { title: 'یاس', description: 'گلی زینتی و خوشبو', rootName: 'فارسی' },
      { title: 'یارا', description: 'یاری‌رسان', rootName: 'فارسی' },
      { title: 'یسنا', description: 'نیایش', rootName: 'فارسی' },
      { title: 'یاران', description: 'دوستان، نماد وفاداری', rootName: 'فارسی' },
      { title: 'یکتا', description: 'بی‌همتا', rootName: 'فارسی' },
    ],
  },
};

export const NAME_SELECTION_BANNER_NAME_1 = 'name1';
