export const PERSIAN_NAME_DICTIONARY = {
  ا: {
    category: 'ا',
    list: [
      { title: 'الوان', description: 'زیبا و دل\u200cنشین', rootName: 'کردی' },
      { title: 'الیزه', description: 'بهشتی', rootName: 'فرانسوی' },
      { title: 'النا', description: 'روشنایی', rootName: 'عبری' },
      { title: 'الیکا', description: 'گل سرخ', rootName: 'فارسی' },
      { title: 'الیسا', description: 'حقیقت جو', rootName: 'عبری' },
      { title: 'الماز', description: 'سیب / گوهر', rootName: 'ترکی' },
      { title: 'الهان', description: 'لطیف', rootName: 'ترکی' },
      { title: 'الیزابت', description: 'دختری وقف خدا', rootName: 'عبری' },
      { title: 'الیتا', description: 'برگزیده', rootName: 'لاتین' },
      { title: 'الوا', description: 'فرشته', rootName: 'عبری' },
      { title: 'الریما', description: 'آهوی سفید', rootName: 'عربی' },
      { title: 'الیف', description: 'نجیب', rootName: 'ترکی' },
      { title: 'الماز', description: 'درخشان', rootName: 'عربی' },
      { title: 'الور', description: 'شاد ', rootName: 'ترکی' },
      { title: 'الورا', description: 'شکوه طبیعی', rootName: 'ایتالیایی' },
      { title: 'الیسیا', description: 'نجات یافته', rootName: 'یونانی' },
      { title: 'الیمه', description: 'ترکیبی از الهه و نعمت', rootName: 'ترکی' },
      { title: 'الیا', description: 'به سوی خدا', rootName: 'عبری' },
      { title: 'افسون', description: 'جذابیت فریبنده', rootName: 'فارسی' },
      { title: 'ارغوان', description: 'گل سرخ رنگ', rootName: 'فارسی' },
    ],
  },
  آ: {
    category: 'آ',
    list: [
      { title: 'آنیسا', description: 'مونس و همدم', rootName: 'عبری/عربی' },
      { title: 'آرتمیس', description: 'الهه شکار و ماه در اساطیر یونان باستان', rootName: 'یونانی' },
      { title: 'آیسل', description: 'نور ماه', rootName: 'ترکی' },
      { title: 'آنیلا', description: 'نسیم پاک', rootName: 'سانسکریت' },
      { title: 'آیه', description: 'معجزه', rootName: 'عربی' },
      { title: 'آلا', description: 'شادمان', rootName: 'ترکی' },
      { title: 'آیماه', description: 'ماه مهربان', rootName: 'ترکی' },
      { title: 'آرشیدا', description: 'بانوی شجاع', rootName: 'فارسی' },
      { title: 'آترینا', description: 'درخشان', rootName: 'فارسی' },
      { title: 'آیتک', description: 'یکتا', rootName: 'ترکی' },
      { title: 'آناهیتا', description: 'الهه آب', rootName: 'فارسی باستان' },
      { title: 'آنید', description: 'امیدواری', rootName: 'فارسی' },
      { title: 'آیسانا', description: 'مثل ماه', rootName: 'ترکی' },
      { title: 'آتاناز', description: 'همیشه درخشان', rootName: 'فارسی' },
      { title: 'آماندا', description: 'سزاوار عشق', rootName: 'لاتین' },
      { title: 'آتین', description: 'دختری از نور', rootName: 'فارسی ' },
      { title: 'آبگین', description: 'شفاف و بلورین', rootName: 'فارسی ' },
      { title: 'آباندخت', description: 'دختر آب', rootName: 'فارسی ' },
      { title: 'آذردخت', description: 'آتش آسمانی', rootName: 'فارسی ' },
      { title: 'آیگل', description: 'درخشان مانند ماه', rootName: 'ترکی' },
    ],
  },
  B: {
    category: 'ب',
    list: [
      { title: 'بَسرا', description: 'دختر زیبا و جوان', rootName: 'عربی' },
      { title: 'بهدیس', description: 'چهره نیکو', rootName: 'فارسی' },
      { title: 'بهنیسا', description: 'زن برتر', rootName: 'فارسی' },
      { title: 'بهین', description: 'شایسته', rootName: 'فارسی' },
      { title: 'بهینا', description: 'دختری نیک نهاد', rootName: 'فارسی' },
      { title: 'بلین', description: 'عهد و قرار ', rootName: 'کردی' },
      { title: 'بنیتا', description: 'دختر بی همتای من', rootName: 'فارسی' },
      { title: 'باوان', description: 'جگر گوشه و عزیز', rootName: 'کردی' },
      { title: 'بهارناز', description: 'موجب فخر و ناز بهار', rootName: 'فارسی' },
      { title: 'بژین', description: 'زندگی خوش', rootName: 'کردی' },
      { title: 'بَرفین', description: 'سفید و زیبا مانند برف', rootName: 'فارسی' },
      { title: 'بنیسا', description: 'دختر نیکوکار', rootName: 'فارسی' },
      { title: 'بارانا', description: 'ای باران', rootName: 'فارسی' },
      { title: 'برگین', description: 'مانند برگ گل', rootName: 'ترکی' },
      { title: 'بهنوش', description: 'گوارا', rootName: 'فارسی' },
      { title: 'به گل', description: 'زیباتر از گل', rootName: 'فارسی' },
      { title: 'بهدیس', description: 'مانند خوبی', rootName: 'فارسی' },
      { title: 'بهکامه', description: 'آرزوی خوبتر', rootName: 'فارسی' },
      { title: 'بهناز', description: 'دلبرا و ظریف', rootName: 'فارسی' },
      { title: 'بیتا', description: 'بی همتا', rootName: 'فارسی' },
    ],
  },
  P: {
    category: 'پ',
    list: [
      { title: 'پناه', description: 'محل امن', rootName: 'فارسی' },
      { title: 'پرنسا', description: 'ملکه', rootName: 'فارسی' },
      { title: 'پارمیس', description: 'نوعی گوهر زیبا', rootName: 'فارسی' },
      { title: 'پریا', description: 'جمع پری، مانند فرشته', rootName: 'فارسی' },
      { title: 'پانیذ', description: 'نگهبان', rootName: 'فارسی' },
      { title: 'پنار', description: 'چشمه آب', rootName: 'ترکی' },
      { title: 'پریزاد', description: 'زاده پری', rootName: 'فارسی' },
      { title: 'پریماه', description: 'ماه مانند پری', rootName: 'فارسی' },
      { title: 'پرواز', description: 'پرواز', rootName: 'فارسی' },
      { title: 'پریهان', description: 'شکوه پری', rootName: 'فارسی' },
      { title: 'پارمیدا', description: 'دارنده\u200cی جایگاه والا', rootName: 'فارسی' },
      { title: 'پریمهر', description: 'مهربان', rootName: 'فارسی' },
      { title: 'پریچهر', description: 'زیباروی مانند پری', rootName: 'فارسی' },
      { title: 'پری رخ', description: 'زیباروی مانند پری', rootName: 'فارسی' },
      { title: 'پری گل', description: 'گل رویی چون فرشته', rootName: 'فارسی' },
      { title: 'پریوش', description: 'فرشته نویددهنده', rootName: 'فارسی' },
      { title: 'پانیدا', description: 'محافظ', rootName: 'فارسی' },
      { title: 'پژوان', description: 'پرتو نور', rootName: 'کردی' },
      { title: 'پرستش', description: 'عبادت', rootName: 'فارسی' },
      { title: 'پوپک', description: 'نام نوعی پرنده کوچک و زیبا', rootName: 'فارسی' },
    ],
  },
  T1: {
    category: 'ت',
    list: [
      { title: 'تیارا', description: 'آراینده چشم/ زیبا', rootName: 'لری' },
      { title: 'تیدا', description: 'دختر خورشید', rootName: 'فارسی' },
      { title: 'تیانا', description: 'بسیار زیبا', rootName: 'لاتین' },
      { title: 'تیام', description: 'عزیز و گرامی', rootName: 'لری' },
      { title: 'تانیا', description: 'ملکه مهربان', rootName: 'کردی' },
      { title: 'تبسم', description: 'لبخند', rootName: 'عربی' },
      { title: 'تلما', description: 'گندمگون', rootName: 'عربی' },
      { title: 'تابان', description: 'درخشان', rootName: 'فارسی' },
      { title: 'تالیا', description: 'تلاوت کننده قران', rootName: 'عربی' },
      { title: 'ترگل', description: 'گل تازه و شاداب', rootName: 'فارسی' },
      { title: 'تیادا', description: 'نور چشم مادر', rootName: 'لری' },
      { title: 'تیهو', description: 'پرنده ای خوش صدا', rootName: 'فارسی' },
      { title: 'تارا', description: 'ستاره', rootName: 'فارسی' },
      { title: 'ترنم', description: 'آواز خوش', rootName: 'عربی' },
      { title: 'ترانه', description: 'نغمه', rootName: 'فارسی' },
      { title: 'تکا', description: 'پرنده ای خوش خوان', rootName: 'فارسی' },
      { title: 'تالین', description: 'لطافت', rootName: 'لاتین' },
      { title: 'تامینه', description: 'آرامش بخش', rootName: 'ترکی' },
      { title: 'تینا', description: 'گل سرخ', rootName: 'فارسی' },
      { title: 'تارامهر', description: 'ستاره و خورشید', rootName: 'فارسی' },
    ],
  },
  S1: {
    category: 'ث',
    list: [
      { title: 'ثنا', description: 'ستایش', rootName: 'عربی' },
      { title: 'ثمین', description: 'گرانبها', rootName: 'عربی' },
      { title: 'ثمره', description: 'نتیجه و حاصل ', rootName: 'عربی' },
      { title: 'ثریا', description: 'خوشه پروین', rootName: 'عربی' },
      { title: 'ثمیلا', description: 'سرمه کشیده ', rootName: 'عربی' },
      { title: 'ثمینا', description: 'ارزشمند', rootName: 'عربی' },
      { title: 'ثمینه', description: 'نفیس و گرانبها', rootName: 'عربی' },
      { title: 'ثمن', description: 'ارزش', rootName: 'عربی' },
    ],
  },
  J: {
    category: 'ج',
    list: [
      { title: 'جانان', description: 'معشوق', rootName: 'فارسی' },
      { title: 'جواهر', description: 'گوهر', rootName: 'عربی' },
      { title: 'جیران', description: 'آهوی زیبا', rootName: 'ترکی' },
      { title: 'جانا', description: 'ای جان', rootName: 'فارسی' },
      { title: 'جانسو', description: 'زندگی بخش', rootName: 'ترکی' },
      { title: 'جان افروز', description: 'روشن کننده جان', rootName: 'فارسی' },
      { title: 'جیلان', description: 'غزال', rootName: 'ترکی' },
      { title: 'جوانه', description: 'شکوفه تازه روییده', rootName: 'فارسی' },
      { title: 'جانسا', description: 'بانشاط', rootName: 'ترکی' },
      { title: 'جانیار', description: 'همراه صمیمی', rootName: 'ترکی' },
      { title: 'جلوه', description: 'درخشندگی', rootName: 'فارسی' },
      { title: 'جسیکا', description: 'روشن بین', rootName: 'عبری' },
      { title: 'جیدا', description: 'دختر شاد', rootName: 'لاتین' },
      { title: 'جمیلا', description: 'دختر زیبا', rootName: 'عربی' },
      { title: 'جاسمینا', description: 'گل یاسمن', rootName: 'لاتین' },
      { title: 'جیوا', description: 'زندگی', rootName: 'سانسکریت' },
      { title: 'جانینا', description: 'مهربان', rootName: 'عبری' },
      { title: 'جانلی', description: 'جاندار', rootName: 'ترکی' },
      { title: 'جلیا', description: 'روشنایی', rootName: 'عربی' },
      { title: 'جیلا', description: 'نجیب', rootName: 'فارسی' },
    ],
  },
  CH: {
    category: 'چ',
    list: [
      { title: 'چهرآذر', description: 'دارای چهره ای چون اتش', rootName: 'فارسی' },
      { title: 'چمن رخ', description: 'زیبارو', rootName: 'فارسی' },
      { title: 'چیدا', description: 'مانند مادر', rootName: 'لری' },
      { title: 'چاوان', description: 'چشم ها', rootName: 'کردی' },
      { title: 'چیستا', description: 'فرزانگی', rootName: 'فارسی' },
      { title: 'چمانه', description: 'ساغر', rootName: 'فارسی' },
      { title: 'چهرزاد', description: 'دارای چهره زیبا', rootName: 'فارسی' },
      { title: 'چشمه', description: 'زلالی، پاکی', rootName: 'فارسی' },
      { title: 'چکاوک', description: 'پرنده ای خوش آواز', rootName: 'فارسی' },
      { title: 'چکامه', description: 'شعر', rootName: 'فارسی' },
      { title: 'چمن چهر', description: 'خوش سیما', rootName: 'فارسی' },
      { title: 'چیترا', description: 'روشن', rootName: 'سانسکریت' },
      { title: 'چهرمینو', description: 'دارای زیبایی چون بهشت', rootName: 'فارسی' },
      { title: 'چیکا', description: 'نوعی پرنده', rootName: 'ترکی' },
      { title: 'چهرآرا', description: 'آراینده صورت', rootName: 'فارسی' },
      { title: 'چهرافروز', description: 'روشن کننده چهره ها', rootName: 'فارسی' },
      { title: 'چیاوان', description: 'زندگی بخش', rootName: 'سانسکریت' },
      { title: 'چیماه', description: 'مانند ماه', rootName: 'فارسی' },
      { title: 'چشمک', description: 'شیرین و بازیگوش', rootName: 'فارسی' },
      { title: 'چمن دخت', description: 'دختری با نشاط', rootName: 'فارسی' },
    ],
  },
  H1: {
    category: 'ح',
    list: [
      { title: 'حریرگل', description: 'گل ابریشم', rootName: 'فارسی' },
      { title: 'حورسا', description: 'مانند فرشته', rootName: 'فارسی' },
      { title: 'حوراماه', description: 'زن زیبای بهشتی', rootName: 'فارسی' },
      { title: 'حصنا', description: 'زن پارسا', rootName: 'عربی' },
      { title: 'حیات', description: 'زندگی', rootName: 'عربی' },
      { title: 'حوریه', description: 'زن زیبا ', rootName: 'عربی' },
      { title: 'حنیسه', description: 'زن شجاع', rootName: 'عربی' },
      { title: 'حمیرا', description: 'زن سرخ روی', rootName: 'عربی' },
      { title: 'حوراوش', description: 'همچون زنان زیبای بهشتی', rootName: 'فارسی' },
      { title: 'حورناز', description: 'زن زیبا دارای ناز و کرشمه', rootName: 'فارسی' },
      { title: 'حوریسا', description: 'همانند حوری و پری', rootName: 'فارسی' },
      { title: 'حمیده', description: 'ستوده', rootName: 'عربی' },
      { title: 'حسانه', description: 'دختر نیکو', rootName: 'عربی' },
      { title: 'حدیثه', description: 'حکایت و داستان', rootName: 'عربی' },
      { title: 'حدیث', description: 'روایت', rootName: 'عربی' },
      { title: 'حسیبا', description: 'دختر پاک و اصیل', rootName: 'عربی' },
      { title: 'حانیه', description: 'مهربان', rootName: 'عربی' },
      { title: 'حنا', description: 'نام یک گیاه', rootName: 'عربی' },
      { title: 'حلما', description: 'دختر صبور', rootName: 'عربی' },
      { title: 'حسنا', description: 'شایسته', rootName: 'عربی' },
    ],
  },
  KH: {
    category: 'خ',
    list: [
      { title: 'خاطره', description: 'یادبود', rootName: 'فارسی' },
      { title: 'خورشید', description: 'خورشید اسمان ها', rootName: 'فارسی باستان' },
      { title: 'خزان', description: 'پاییز', rootName: 'عربی' },
      { title: 'خجسته', description: 'سعادتمند', rootName: 'فارسی' },
      { title: 'خاتون', description: 'لقب زنان اشرافی', rootName: 'ترکی' },
      { title: 'خوشناز', description: 'زیبا و با کرشمه', rootName: 'فارسی' },
      { title: 'خوشه', description: 'تعدادی دانه', rootName: 'فارسی' },
      { title: 'خانم گل', description: 'زنی به لطافات گل', rootName: 'فارسی' },
      { title: 'خورشید مهر', description: 'زیبارو', rootName: 'فارسی' },
      { title: 'خوشین', description: 'خوش و زیبا', rootName: 'فارسی' },
      { title: 'خوبان', description: 'خوب ها', rootName: 'فارسی' },
      { title: 'خورشیدرخ', description: 'چهره درخشان چون خورشید', rootName: 'فارسی' },
      { title: 'خندیس', description: 'بانویی خندان', rootName: 'فارسی' },
      { title: 'خرم\u200cدخت', description: 'دختر شاد', rootName: 'فارسی' },
      { title: 'خشایاندخت', description: 'دخترِ بزرگ\u200cمنش', rootName: 'فارسی' },
      { title: 'خاوران', description: 'سرزمین شرق', rootName: 'فارسی' },
      { title: 'خرم چهر', description: 'خوش\u200cسیما', rootName: 'فارسی' },
      { title: 'خَلقا', description: 'خوش\u200cخلقی', rootName: 'عربی' },
      { title: 'خرمناز', description: 'باوقار و زیبا', rootName: 'فارسی' },
      { title: 'خونسا', description: 'دختر زیبا', rootName: 'کردی' },
    ],
  },
  D: {
    category: 'د',
    list: [
      { title: 'دلارام', description: 'آرامش\u200cدهنده دل', rootName: 'فارسی' },
      { title: 'دنیا', description: 'جهان', rootName: 'عربی' },
      { title: 'دینا', description: 'عدالت', rootName: 'عبری' },
      { title: 'دایانا', description: 'الهه شکار', rootName: 'لاتین' },
      { title: 'دریا', description: 'دریا', rootName: 'فارسی' },
      { title: 'دلنیا', description: 'دلنشین', rootName: 'فارسی' },
      { title: 'دلبر', description: 'محبوب', rootName: 'فارسی' },
      { title: 'دلسا', description: 'آرامبخش دل', rootName: 'فارسی' },
      { title: 'دلنواز', description: 'مهربان', rootName: 'فارسی' },
      { title: 'دوسا', description: 'دوست داشتنی', rootName: 'کردی' },
      { title: 'دلوین', description: 'رباینده دل', rootName: 'کردی' },
      { title: 'دلانا', description: 'عزیز مادر', rootName: 'ترکی' },
      { title: 'دنیز', description: 'دریا', rootName: 'ترکی' },
      { title: 'درنیکا', description: 'گرانبها', rootName: 'فارسی' },
      { title: 'درسا', description: 'مانند مروارید', rootName: 'فارسی' },
      { title: 'دلین', description: 'آسوده', rootName: 'کردی' },
      { title: 'دلوان', description: 'دختر مهربان', rootName: 'کردی' },
      { title: 'دیبا', description: 'پارچه ابریشمی', rootName: 'فارسی' },
      { title: 'دیماه', description: 'زیبارو مانند ماه', rootName: 'فارسی' },
      { title: 'درسین', description: 'مروارید آسمان', rootName: 'کردی' },
    ],
  },
  Z1: {
    category: 'ذ',
    list: [
      { title: 'ذلفا', description: 'دختری با گیسوان زیبا', rootName: 'عربی' },
      { title: 'ذریه ', description: 'فرزندان', rootName: 'عربی' },
      { title: 'ذکا', description: 'هوشمند', rootName: 'عربی' },
      { title: 'ذیانه', description: 'دانا', rootName: 'عربی' },
      { title: 'ذیهانا', description: 'باهوش', rootName: 'عربی' },
      { title: 'ذوقیه', description: 'دارای استعداد', rootName: 'عربی' },
      { title: 'ذکیه', description: 'پاکیزه', rootName: 'عربی' },
    ],
  },
  R: {
    category: 'ر',
    list: [
      { title: 'رستا', description: 'کامیاب', rootName: 'فارسی' },
      { title: 'رونیا', description: 'اصیل', rootName: 'فارسی' },
      { title: 'روشنا', description: 'نور', rootName: 'فارسی' },
      { title: 'روشا', description: 'شاداب', rootName: 'فارسی' },
      { title: 'رونیکا', description: 'دختر خورشید', rootName: 'فارسی' },
      { title: 'روژان', description: 'زندگی', rootName: 'کردی' },
      { title: 'رمیصا', description: 'ستاره ای درخشان', rootName: 'عربی' },
      { title: 'رزانا', description: 'باوقار', rootName: 'فارسی' },
      { title: 'رومینا', description: 'پاک', rootName: 'فارسی' },
      { title: 'رائیکا', description: 'پسندیده', rootName: 'فارسی باستان' },
      { title: 'رکسانه', description: 'زیبارو', rootName: 'فارسی باستان' },
      { title: 'ری\u200cرا ', description: 'زن دلفریب', rootName: 'گیلکی' },
      { title: 'رزیتا', description: 'گل رز کوچک', rootName: 'فرانسوی' },
      { title: 'روژیار', description: 'خورشید', rootName: 'کردی' },
      { title: 'رانیا', description: 'نام یک گل', rootName: 'عربی' },
      { title: 'رشا', description: 'بچه آهو', rootName: 'عبری' },
      { title: 'رامیسا', description: 'گل رز سفید', rootName: 'عربی' },
      { title: 'راما', description: 'مانوس', rootName: 'سانسکریت' },
      { title: 'رابو', description: 'نام گل بهاری', rootName: 'فارسی' },
      { title: 'ریما', description: 'آهوی سفید', rootName: 'عربی' },
    ],
  },
  Z2: {
    category: 'ز',
    list: [
      { title: 'زلفا', description: 'زیبایی زلف معشوق', rootName: 'فارسی' },
      { title: 'زینا', description: 'نام دختر نوح نبی', rootName: 'عبری' },
      { title: 'زرین مهر', description: 'خورشید طلایی', rootName: 'فارسی' },
      { title: 'زیبادخت', description: 'دختر زیبا', rootName: 'فارسی' },
      { title: 'زرسا', description: 'مانند زر', rootName: 'فارسی' },
      { title: 'زرقا', description: 'به رنگ آسمان', rootName: 'عربی' },
      { title: 'زویا', description: 'زندگی', rootName: 'لاتین' },
      { title: 'زرگل', description: 'زرین گل', rootName: 'فارسی' },
      { title: 'زیما', description: 'زمین', rootName: 'فارسی باستان' },
      { title: 'زرماه', description: 'ماه طلایی', rootName: 'فارسی' },
      { title: 'زیبا', description: 'خوش سیما', rootName: 'فارسی' },
      { title: 'زرشام', description: 'نام دختری از خاندان جمشید', rootName: 'فارسی باستان' },
      { title: 'زرتا', description: 'مانند زر', rootName: 'فارسی' },
      { title: 'زرگیسو', description: 'گیسوطلایی', rootName: 'فارسی' },
      { title: 'زمرد', description: 'نام سنگ قیمتی با رنگ سبز', rootName: 'عربی' },
      { title: 'زارا', description: 'زلال', rootName: 'کردی' },
      { title: 'زلیا', description: 'آوای لطیف', rootName: 'فارسی' },
      { title: 'زارینا', description: 'طلایی و باشکوه', rootName: 'روسی' },
      { title: 'زرلین', description: 'درخشان مانند زر', rootName: 'فرانسوی' },
      { title: 'زوانا ', description: 'بانوی سخنور', rootName: 'فارسی' },
    ],
  },
  ZH: {
    category: 'ژ',
    list: [
      { title: 'ژیرا', description: 'زیرک', rootName: 'کردی' },
      { title: 'ژیراکو', description: 'دختر مهربان', rootName: 'کردی' },
      { title: 'ژیوار', description: 'آرامگاه دل', rootName: 'کردی' },
      { title: 'ژینا', description: 'زندگی دهنده', rootName: 'کردی' },
      { title: 'ژیلا', description: 'شبنم صبحگاهی', rootName: 'فارسی' },
      { title: 'ژاله', description: 'شبنم', rootName: 'فارسی' },
      { title: 'ژوان', description: 'میعادگاه عاشق و معشوق', rootName: 'کردی' },
      { title: 'ژیوا', description: 'نگاه به زندگی', rootName: 'کردی' },
      { title: 'ژینوس', description: 'دختر باهوش', rootName: 'فرانسوی' },
      { title: 'ژالان', description: 'شبنم گل ها', rootName: 'کردی' },
      { title: 'ژانیتا', description: 'هدیه ای از سوی خدا', rootName: 'یونانی' },
      { title: 'ژاوین', description: 'سرزندگی', rootName: 'کردی' },
      { title: 'ژینو', description: 'زندگی بخش', rootName: 'کردی' },
      { title: 'ژالین', description: 'شعله آتش', rootName: 'ترکی' },
      { title: 'ژیانا', description: 'دارای زندگی', rootName: 'کردی' },
      { title: 'ژالیا', description: 'الهه زیبایی', rootName: 'کردی' },
      { title: 'ژامک', description: 'آینه', rootName: 'فارسی' },
      { title: 'ژیوانا', description: 'حافظ زندگی', rootName: 'کردی' },
      { title: 'ژانین', description: 'نام دریاچه', rootName: 'فرانسوی' },
      { title: 'ژیا', description: 'زندگی', rootName: 'کردی' },
    ],
  },
  S2: {
    category: 'س',
    list: [
      { title: 'سلین', description: 'مانند سیل خروشان', rootName: 'ترکی' },
      { title: 'سلنا', description: 'الهه ماه', rootName: 'یونانی' },
      { title: 'سلما', description: 'زن صلح طلب', rootName: 'عربی' },
      { title: 'ستیا', description: 'جهان طلب', rootName: 'فارسی باستان' },
      { title: 'سارینا', description: 'پاک', rootName: 'فارسی' },
      { title: 'سوین', description: 'عشق و محبت', rootName: 'ترکی' },
      { title: 'ستین', description: 'عزیز', rootName: 'لری' },
      { title: 'سلوا', description: 'مایه ارامش', rootName: 'عربی' },
      { title: 'سها', description: 'نام ستاره', rootName: 'عربی' },
      { title: 'سلدا', description: 'یاور', rootName: 'ترکی' },
      { title: 'سدنا', description: 'سجده کننده بر خانه خدا', rootName: 'عربی' },
      { title: 'سروین', description: 'مانند سرو', rootName: 'کردی' },
      { title: 'سوده', description: 'زن بزرگوار', rootName: 'عربی' },
      { title: 'سوما', description: 'نور ماه', rootName: 'کردی' },
      { title: 'سوفیا', description: 'حکیم و دانا', rootName: 'یونانی' },
      { title: 'سمن دخت', description: 'دختر سفیدچهره', rootName: 'فارسی' },
      { title: 'سروناز', description: 'دختری خوش قامت و ناز', rootName: 'فارسی' },
      { title: 'سایماه', description: 'سایه ماه', rootName: 'فارسی' },
      { title: 'سولماز', description: 'همیشه شاداب', rootName: 'ترکی' },
      { title: 'سالومه', description: 'صلح و آرامش', rootName: 'عبری' },
    ],
  },
  SH: {
    category: 'ش',
    list: [
      { title: 'شان آی', description: 'شکوه و عظمت ماه', rootName: 'ترکی' },
      { title: 'شمین', description: 'خوشبو', rootName: 'فارسی' },
      { title: 'شیوا', description: 'دلنشین', rootName: 'فارسی' },
      { title: 'شرمین', description: 'باحجب و حیا', rootName: 'فارسی' },
      { title: 'شمینا', description: 'عطرآگین', rootName: 'فارسی' },
      { title: 'شارمینا', description: 'خجسته', rootName: 'فارسی باستان' },
      { title: 'شاهیکا', description: 'قله', rootName: 'ترکی' },
      { title: 'شمامه', description: 'بوی خوش', rootName: 'عربی' },
      { title: 'شمسا', description: 'نور و روشنایی', rootName: 'فارسی باستان' },
      { title: 'شمیس', description: 'نور ', rootName: 'عربی' },
      { title: 'شیرین زاد', description: 'عزیز و گرامی', rootName: 'فارسی' },
      { title: 'شانلی', description: 'پرافتخار', rootName: 'ترکی' },
      { title: 'شوکا', description: 'نوعی گوزن', rootName: 'فارسی' },
      { title: 'شانای', description: 'ماه پر افتخار', rootName: 'ترکی' },
      { title: 'شیده', description: 'آفتاب', rootName: 'فارسی باستان' },
      { title: 'شاینا', description: 'شاهدانه', rootName: 'فارسی' },
      { title: 'شادلین', description: 'شادروی ارام', rootName: 'فارسی' },
      { title: 'شانا', description: 'مقام و منزلت', rootName: 'کردی' },
      { title: 'شایلین ', description: 'بی همتا', rootName: 'ترکی' },
      { title: 'شیرین دخت', description: 'دختر شیرین و زیبا', rootName: 'فارسی' },
    ],
  },
  S3: {
    category: 'ص',
    list: [
      { title: 'صبا', description: 'باد ملایم', rootName: 'عربی' },
      { title: 'صحرا', description: 'بیابان', rootName: 'عربی' },
      { title: 'صنم', description: 'معشوق زیبارو', rootName: 'عربی' },
      { title: 'صهبا', description: 'شراب انگور', rootName: 'عربی' },
      { title: 'صاینا', description: 'پرهیزکار', rootName: 'عربی' },
      { title: 'صونا', description: 'پارسایی', rootName: 'عربی' },
      { title: 'صدف', description: 'نام سه ستاره', rootName: 'عربی' },
      { title: 'صاحبه', description: 'هم صحبت', rootName: 'عربی' },
      { title: 'صبرا', description: 'صبور', rootName: 'عربی' },
      { title: 'صبورا', description: 'بردبار', rootName: 'عربی' },
      { title: 'صنیعا', description: 'ساخته شده', rootName: 'عربی' },
      { title: 'صفیا', description: 'خالص و یگانه', rootName: 'عربی' },
      { title: 'صبیه', description: 'دختربچه', rootName: 'عربی' },
      { title: 'صایما', description: 'زن روزه دار', rootName: 'عربی' },
      { title: 'صفورا', description: 'گنجشک ماده', rootName: 'عربی' },
      { title: 'صنم گل', description: 'معشوق چون گل', rootName: 'عربی' },
      { title: 'صمیمه', description: 'بسیار بامحبت', rootName: 'عربی' },
      { title: 'صهباگل', description: 'گل مستی آور', rootName: 'عربی/فارسی' },
      { title: 'صوفیا', description: 'دانایی', rootName: 'یونانی' },
      { title: 'صمیما', description: 'بامحبت', rootName: 'عربی' },
    ],
  },
  Z3: {
    category: 'ض',
    list: [
      { title: 'ضحا', description: 'خورشید', rootName: 'عربی' },
      { title: 'ضیا', description: 'روشنی', rootName: 'عربی' },
      { title: 'ضیفانه', description: 'مهمان نواز', rootName: 'عربی' },
      { title: 'ضحوفه', description: 'آرام و ملایم', rootName: 'عربی' },
      { title: 'ضراریا', description: 'دختر آزاده', rootName: 'عربی' },
      { title: 'ضوءیه', description: 'درخشان', rootName: 'عربی' },
      { title: 'ضابیه', description: 'آهو', rootName: 'عربی' },
      { title: 'ضامنه', description: 'محافظ', rootName: 'عربی' },
    ],
  },
  T2: {
    category: 'ط',
    list: [
      { title: 'طنین', description: 'انعکاس صوت', rootName: 'عربی' },
      { title: 'طناز', description: 'بسیار زیبا', rootName: 'عربی' },
      { title: 'طراوت', description: 'شادابی و تازگی', rootName: 'عربی' },
      { title: 'طرلان', description: 'زیبا', rootName: 'ترکی' },
      { title: 'طیلا', description: 'نوعی شراب', rootName: 'فارسی' },
      { title: 'طنان', description: 'بلندآوازه', rootName: 'عربی' },
      { title: 'طلوع', description: 'برآمدن خورشید', rootName: 'عربی' },
      { title: 'طلاگون', description: 'مانند زر', rootName: 'فارسی' },
      { title: 'طلا', description: 'زر', rootName: 'عربی' },
      { title: 'طاووس', description: 'نوعی پرنده زیبا', rootName: 'عربی' },
      { title: 'طلیحه', description: 'پیشرو', rootName: 'عربی' },
      { title: 'طهورا', description: 'بسیار پاک', rootName: 'عربی' },
    ],
  },
  Z4: {
    category: 'ظ',
    list: [
      { title: 'ظریفه', description: 'باظرافت', rootName: 'عربی' },
      { title: 'ظهیره', description: 'پشتیبان', rootName: 'عربی' },
      { title: 'ظفردخت', description: 'دختر پیروز', rootName: 'فارسی' },
      { title: 'ظهیرا', description: 'یاور', rootName: 'عربی' },
      { title: 'ظافره', description: 'پیروز', rootName: 'عربی' },
      { title: 'ظرافت', description: 'ظریف', rootName: 'عربی' },
      { title: 'ظهوره', description: 'آشکارشده', rootName: 'عربی' },
      { title: 'ظفیره', description: 'همیشه برنده', rootName: 'عربی' },
      { title: 'ظلیفه', description: 'زن عزیز', rootName: 'عربی' },
      { title: 'ظهیما', description: 'شریک و یاور', rootName: 'عربی' },
      { title: 'ظلالا', description: 'خنکی سایه', rootName: 'عربی' },
      { title: 'ظفره', description: 'کامیابی', rootName: 'عربی' },
      { title: 'ظبا', description: 'دختری شجاع', rootName: 'عربی' },
      { title: 'ظمیا', description: 'لطافت', rootName: 'عربی' },
      { title: 'ظلیمت', description: 'برازنده', rootName: 'عربی' },
    ],
  },
  A2: {
    category: 'ع',
    list: [
      { title: 'عسل', description: 'بسیار دوست داشتنی', rootName: 'عربی' },
      { title: 'عما', description: 'ابر باران ریز', rootName: 'عربی' },
      { title: 'عروشا', description: 'دختر بهشتی', rootName: 'عربی' },
      { title: 'عطوفت', description: 'مهربانی بسیار', rootName: 'عربی' },
      { title: 'علیما', description: 'دانا', rootName: 'عربی' },
      { title: 'عاتکه', description: 'زن خوشبو', rootName: 'عربی' },
      { title: 'عفرا', description: 'نوعی آهو', rootName: 'عربی' },
      { title: 'عطرین', description: 'خوشبو', rootName: 'فارسی' },
      { title: 'عیدا', description: 'کسی که شادی می آورد', rootName: 'عربی' },
      { title: 'عدیله', description: 'درستکار', rootName: 'عربی' },
      { title: 'عریسا', description: 'عروس', rootName: 'عربی' },
    ],
  },
  GH1: {
    category: 'غ',
    list: [
      { title: 'غزل', description: 'شعر عاشقانه', rootName: 'عربی' },
      { title: 'غنچه', description: 'جوانه گل', rootName: 'فارسی' },
      { title: 'غادیه', description: 'نسیم صبحگاهی', rootName: 'عربی' },
      { title: 'غنیمه', description: 'بهره و سود', rootName: 'عربی' },
      { title: 'غنود', description: 'خواب آرام', rootName: 'عربی' },
    ],
  },
  F: {
    category: 'ف',
    list: [
      { title: 'فاطیما', description: 'رانده شده از آتش', rootName: 'لاتین' },
      { title: 'فادیا', description: 'منجی', rootName: 'عربی' },
      { title: 'فرنیا', description: 'اصیل', rootName: 'فارسی' },
      { title: 'فیدان', description: 'شکوفه و غنچه', rootName: 'ترکی' },
      { title: 'فریال', description: 'زیباروی', rootName: 'عربی' },
      { title: 'فرنوش', description: 'دارای شکوه جاودان', rootName: 'فارسی' },
    ],
  },
  GH2: {
    category: 'ق',
    list: [
      { title: 'قمر', description: 'زن زیبا', rootName: 'عربی' },
      { title: 'قاصدک', description: 'نوعی گیاه', rootName: 'فارسی' },
      { title: 'قمرسیما', description: 'زیبارو چون ماه', rootName: 'فارسی' },
      { title: 'قشنگ', description: 'زیبا', rootName: 'فارسی' },
      { title: 'قمرناز', description: 'ماه ناز', rootName: 'فارسی' },
      { title: 'قیدافه', description: 'از شخصیتهای شاهنامه', rootName: 'فارسی' },
      { title: 'قدیسه', description: 'زن پاک', rootName: 'عربی' },
    ],
  },
  K: {
    category: 'ک',
    list: [
      { title: 'کلارا', description: 'نور چشم', rootName: 'کردی' },
      { title: 'کالین', description: 'دخترجوان با مو روشن', rootName: 'کردی' },
      { title: 'کارینا', description: 'یکی از سرزمینهای پارت', rootName: 'فارسی' },
      { title: 'کیانا', description: 'طبیعت', rootName: 'فارسی' },
      { title: 'کایرا', description: 'لطف و احسان', rootName: 'ترکی' },
      { title: 'کایلین', description: 'خالص و پاک', rootName: 'لاتین' },
      { title: 'کمند', description: 'گیسو', rootName: 'فارسی' },
      { title: 'کاملیا', description: 'نوعی درختچه ای زینتی', rootName: 'فرانسوی' },
      { title: 'کاترین', description: 'پاک و بی آلایش', rootName: 'فرانسوی' },
      { title: 'کارمیلا', description: 'شکوفه زار', rootName: 'لاتین' },
      { title: 'کامیشا', description: 'خوشحال و سرزنده', rootName: 'فارسی' },
      { title: 'کرشمه', description: 'ناز و عشوه ', rootName: 'فارسی' },
      { title: 'کارنا', description: 'بانو پاکدامن', rootName: 'فارسی' },
      { title: 'کاژین', description: 'سرچشمه زندگی', rootName: 'کردی' },
    ],
  },
  G: {
    category: 'گ',
    list: [
      { title: 'گونش', description: 'آفتابی', rootName: 'ترکی' },
      { title: 'گلناز', description: 'لطیف مثل گل', rootName: 'فارسی' },
      { title: 'گلرو', description: 'زیبارو چون گل', rootName: 'فارسی' },
      { title: 'گلیدا', description: 'گل مادر', rootName: 'لری' },
      { title: 'گلارا', description: 'آراینده گل', rootName: 'فارسی' },
      { title: 'گیسیا', description: 'دارای گیسوان بلند و سیاه', rootName: 'کردی' },
      { title: 'گلبرگ', description: 'برگ گل', rootName: 'فارسی' },
      { title: 'گلرخ', description: 'زیبارو', rootName: 'فارسی' },
      { title: 'گندم', description: 'برکت', rootName: 'فارسی باستان' },
      { title: 'گیسو', description: 'نام نوعی صورت فلکی', rootName: 'فارسی' },
      { title: 'گونای', description: 'آفتابی', rootName: 'ترکی' },
      { title: 'گلاره', description: 'نورچشمی', rootName: 'کردی' },
      { title: 'گلارین', description: 'پاک و زلال', rootName: 'فارسی' },
      { title: 'گیل ماه', description: 'زیبارو', rootName: 'گیلکی' },
      { title: 'گیسا', description: 'جهان', rootName: 'فارسی باستان' },
      { title: 'گلباش', description: 'دختر نیکو چون گل', rootName: 'کردی' },
      { title: 'گیلوا', description: 'دختر زیبای گیلانی', rootName: 'گیلکی' },
      { title: 'گلاسا', description: 'مانند گل', rootName: 'فارسی' },
      { title: 'گلاریس', description: 'زیبا و آراسته', rootName: 'کردی' },
      { title: 'گیلناز', description: 'زیباروی مردم گیلان', rootName: 'گیلکی' },
    ],
  },
  L: {
    category: 'ل',
    list: [
      { title: 'لیزدا', description: 'آرامش مادر', rootName: 'لری' },
      { title: 'لیلماه', description: 'ماه شب', rootName: 'فارسی' },
      { title: 'لیونا', description: 'دلیر و شجاع', rootName: 'لاتین' },
      { title: 'لورا', description: 'چنگ', rootName: 'یونانی' },
      { title: 'لیدا', description: 'بانوی محترم', rootName: 'ارمنی' },
      { title: 'لینا', description: 'مهربانتر', rootName: 'عربی' },
      { title: 'لیانا', description: 'بانوی زیبارو', rootName: 'فارسی' },
      { title: 'لنا', description: 'دختر زیبا', rootName: 'لاتین' },
      { title: 'لارا', description: 'پری دریایی', rootName: 'ترکی' },
      { title: 'لاوین', description: 'نوازشگر', rootName: 'کردی' },
      { title: 'لیدیا', description: 'بانوی دارا', rootName: 'فرانسوی' },
      { title: 'لاریسا', description: 'نفیس و باارزش', rootName: 'فارسی' },
      { title: 'لیوسا', description: 'مانند خورشید', rootName: 'فارسی' },
      { title: 'لیندا', description: 'قشنگ و زیبا', rootName: 'لاتین' },
      { title: 'لیزا', description: 'بنده خاص خدا', rootName: 'عبری' },
      { title: 'لانیا', description: 'آشیانه خوشبختی', rootName: 'کردی' },
      { title: 'لیسا', description: 'ستوده شده', rootName: 'فارسی' },
      { title: 'لما', description: 'درخشش', rootName: 'عربی' },
      { title: 'لبینا', description: 'بانوی نجیب', rootName: 'عبری' },
      { title: 'لیرینا', description: 'آرام و لطیف', rootName: 'یونانی' },
    ],
  },
  M: {
    category: 'م',
    list: [
      { title: 'ماهلین', description: 'هاله ماه', rootName: 'فارسی' },
      { title: 'مرسانا', description: 'هدیه خداوند', rootName: 'کردی' },
      { title: 'مهوا', description: 'ماه شب چهارده', rootName: 'فارسی' },
      { title: 'ماهورا', description: 'زیباتر از ماه', rootName: 'کردی' },
      { title: 'مهرسانا', description: 'همانند خورشید', rootName: 'فارسی' },
      { title: 'مهنا', description: 'شایسته', rootName: 'عربی' },
      { title: 'مانلی', description: 'نام شخصیتی در شعر یوشیج', rootName: 'مازندرانی' },
      { title: 'مهدا', description: 'آرامش شب', rootName: 'عربی' },
      { title: 'ملورین', description: 'در بلورین', rootName: 'فارسی' },
      { title: 'محیصا', description: 'رستگارشده', rootName: 'عربی' },
      { title: 'مایسا', description: 'دختری با زیبایی چشمگیر', rootName: 'ترکی' },
      { title: 'ماتینا', description: 'گل سرخ', rootName: 'مازندرانی' },
      { title: 'مهرانا', description: 'دارنده مهر', rootName: 'فارسی' },
      { title: 'مهرو', description: 'زیبارو چون ماه', rootName: 'فارسی' },
      { title: 'مدیسا', description: 'زیبارو', rootName: 'عبری' },
      { title: 'مایا', description: 'بخشنده', rootName: 'یونانی' },
      { title: 'مهری ماه', description: 'ماه مهربان', rootName: 'فارسی' },
      { title: 'مانیا', description: 'خانه', rootName: 'یونانی' },
      { title: 'مانیسا', description: 'دانشمند', rootName: 'فارسی' },
      { title: 'مهدیا', description: 'بانوی هدایت شده', rootName: 'عربی' },
    ],
  },
  N: {
    category: 'ن',
    list: [
      { title: 'نیروانا', description: 'انسان کامل', rootName: 'فارسی باستان' },
      { title: 'نوژان', description: 'صدای بلند', rootName: 'فارسی' },
      { title: 'نیلان', description: 'فرشته باران', rootName: 'یونانی' },
      { title: 'نازلی', description: 'دارای ناز', rootName: 'ترکی' },
      { title: 'ناردین', description: 'گیسو', rootName: 'فارسی' },
      { title: 'نغمه', description: 'آهنگ و ملودی', rootName: 'عربی' },
      { title: 'نارمیلا', description: 'غنچه', rootName: 'ترکی' },
      { title: 'نلا', description: 'درخشان', rootName: 'یونانی' },
      { title: 'نیلای', description: 'ماه نیلی', rootName: 'ترکی' },
      { title: 'نورسا', description: 'شبیه به نور', rootName: 'فارسی' },
      { title: 'نوژا', description: 'باطراوت', rootName: 'فارسی' },
      { title: 'ناروین', description: 'سرخگون', rootName: 'عربی' },
      { title: 'نگارشید', description: 'نقش و نگار درخشان', rootName: 'فارسی' },
      { title: 'نازیلا', description: 'دخترطناز', rootName: 'ترکی' },
      { title: 'نرمین', description: 'مهربان', rootName: 'فارسی' },
      { title: 'نوژین', description: 'زندگی تازه', rootName: 'کردی' },
      { title: 'ناژین', description: 'فناناپذیر', rootName: 'کردی' },
      { title: 'ناردانه', description: 'دانه انار', rootName: 'فارسی' },
      { title: 'نشمین', description: 'دختر زیبارو', rootName: 'کردی' },
      { title: 'نگارین', description: 'زیبا و آراسته', rootName: 'فارسی' },
    ],
  },
  V: {
    category: 'و',
    list: [
      { title: 'وندا', description: 'آرزو', rootName: 'فارسی باستان ' },
      { title: 'ویانا', description: 'دانایی', rootName: 'فارسی باستان ' },
      { title: 'وانیا', description: 'هدیه با شکوه خدا', rootName: 'عبری' },
      { title: 'ویان', description: 'دلربا', rootName: 'کردی' },
      { title: 'واران', description: 'باران', rootName: 'یونانی' },
      { title: 'ویدا', description: 'یابنده', rootName: 'فارسی' },
      { title: 'ویونا', description: 'عروس زیبا', rootName: 'سانسکریت' },
      { title: 'والریا', description: 'سلامتی', rootName: 'لاتین' },
      { title: 'ویشکا', description: 'بانوی باوقار', rootName: 'فارسی' },
      { title: 'واریشا', description: 'باران', rootName: 'سانسکریت' },
      { title: 'ویرا', description: 'باشهامت', rootName: 'فارسی' },
      { title: 'وهرامیس', description: 'پیروزی', rootName: 'فارسی باستان ' },
      { title: 'ورونیکا', description: 'پیرو راستین', rootName: 'یونانی' },
      { title: 'ورسا', description: 'گل زار', rootName: 'کردی' },
      { title: 'وسنا', description: 'الهه بهار', rootName: 'لاتین' },
      { title: 'وانسا', description: 'جذاب و دلربا', rootName: 'لاتین' },
    ],
  },
  H2: {
    category: 'ه',
    list: [
      { title: 'هلسا', description: 'خوشبو', rootName: 'فارسی' },
      { title: 'هلیا', description: 'دختر خورشید', rootName: 'یونانی' },
      { title: 'هانا', description: 'پناه و امید', rootName: 'ترکی' },
      { title: 'هایلین', description: 'فرشته بهشتی', rootName: 'لاتین' },
      { title: 'هانیسا', description: 'مسرور و شاد', rootName: 'فارسی' },
      { title: 'هیلدا', description: 'نیرومند', rootName: 'لاتین' },
      { title: 'هیما', description: 'بانوی عاشق', rootName: 'عربی' },
      { title: 'هیلا', description: 'نوعی پرنده', rootName: 'فارسی' },
      { title: 'هیلماه', description: 'دختر درخشان', rootName: 'لری' },
      { title: 'هورسا', description: 'مانند خورشید', rootName: 'فارسی' },
      { title: 'هیبا', description: 'هدیه خداوند', rootName: 'عربی' },
      { title: 'هانیدا', description: 'شادی بخش زندگی مادر', rootName: 'لری' },
      { title: 'هانده', description: 'مهربان ترین', rootName: 'ترکی' },
      { title: 'هاوژین', description: 'همدم و یار زندگی', rootName: 'کردی' },
      { title: 'هاویر', description: 'در یاد مانده', rootName: 'لری' },
      { title: 'هورمهر', description: 'زیباروی مهربان', rootName: 'فارسی' },
      { title: 'هوراماه', description: 'دختر زیبای بهشتی', rootName: 'فارسی' },
      { title: 'هیژان', description: 'لایق و سزاوار', rootName: 'کردی' },
      { title: 'هیتا', description: 'خورشید', rootName: 'فارسی' },
      { title: 'هینا', description: 'ماهر', rootName: 'کردی' },
    ],
  },

  Y: {
    category: 'ی',
    list: [
      { title: 'یشیم', description: 'سنگ  گرانبها', rootName: 'ترکی' },
      { title: 'یارن', description: 'دوست و یار نزدیک', rootName: 'ترکی' },
      { title: 'یامور', description: 'باران', rootName: 'ترکی' },
      { title: 'یانا', description: 'نیکی رسان', rootName: 'ترکی' },
      { title: 'یوکابد', description: 'خداوند مجد و بزرگ', rootName: 'عبری' },
      { title: 'یاسمن', description: 'نام گلی خوشبو', rootName: 'فارسی' },
      { title: 'یامین', description: 'نام همسر یعقوب (ع)', rootName: 'عبری' },
      { title: 'یارین', description: 'خوشحالی', rootName: 'عبری' },
      { title: 'یسنا', description: 'ستایش', rootName: 'فارسی باستان' },
      { title: 'یرحا', description: 'نام مادر حضرت موسی (ع)', rootName: 'عبری' },
      { title: 'یارا', description: 'شجاع', rootName: 'کردی' },
      { title: 'یونا', description: 'درخشان', rootName: 'عبری' },
      { title: 'ییلناز', description: 'دختر با ناز', rootName: 'ترکی' },
      { title: 'یوزار', description: 'صبور', rootName: 'ترکی' },
      { title: 'یوناژه', description: 'مهربان', rootName: 'ترکی' },
    ],
  },
};

export const NAME_SELECTION_BANNER_NAME_1 = 'name1';
